// Code generated by "stringer -type=validationErrCode -output=validation_error_string.go"; DO NOT EDIT.

package error

import "fmt"
import "errors"
import "strconv"
import "database/sql/driver"

const _validationErrCode_name = "unknownrequiredlessmorelength_regexunsupportedbadParameterunknownTaginvalidnotMatch_unsupportedTypeduplicatenoBlank_lenTooLong_maxRuneemail_timephoneNopassword_loginnumericnameKananameHiraKanabankAccountKananonblankemailDomainerrMobilePhoneNo"

var _validationErrCode_index = [...]uint8{0, 7, 15, 19, 23, 29, 35, 46, 58, 68, 75, 83, 99, 108, 115, 126, 134, 139, 144, 151, 159, 165, 172, 180, 192, 207, 215, 226, 242}

func (i validationErrCode) String() string {
	if i < 0 || i >= validationErrCode(len(_validationErrCode_index)-1) {
		return "validationErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _validationErrCode_name[_validationErrCode_index[i]:_validationErrCode_index[i+1]]
}

var mvalidationErrCode = map[int]validationErrCode{0: unknown, 1: required, 2: less, 3: more, 4: length, 5: _regex, 6: unsupported, 7: badParameter, 8: unknownTag, 9: invalid, 10: notMatch, 11: _unsupportedType, 12: duplicate, 13: noBlank, 14: _lenTooLong, 15: _maxRune, 16: email, 17: _time, 18: phoneNo, 19: password, 20: _login, 21: numeric, 22: nameKana, 23: nameHiraKana, 24: bankAccountKana, 25: nonblank, 26: emailDomain, 27: errMobilePhoneNo}

func NewvalidationErrCode(value string) (*validationErrCode, error) {

	v, e := strconv.Atoi(value)
	if e != nil {
		return nil, e
	}
	if _, mx := mvalidationErrCode[v]; !mx {
		v, _ := strconv.Atoi(value)
		return nil, errors.New(fmt.Sprintf("invalid enum value.type=validationErrCode, value=%s:%d", value, v))
	}
	a := validationErrCode(v)
	return &a, nil
}
func (i *validationErrCode) Scan(value any) error {

	var x *validationErrCode
	var e error

	switch v := value.(type) {
	case []uint8:
		x, e = NewvalidationErrCode(string(value.([]byte)))
	case int64:
		x, e = NewvalidationErrCode(strconv.Itoa(int(v)))
	default:
		panic(fmt.Sprintf("I don't know about type %T!\n", value))
	}
	if x != nil {
		*i = *x
	}
	return e
}

func (u validationErrCode) Value() (driver.Value, error) {

	return int64(u), nil
}
