// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: user/profile.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state                       protoimpl.MessageState     `protogen:"open.v1"`
	UserId                      *int32                     `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Age                         int32                      `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	AnnualIncome                int32                      `protobuf:"varint,3,opt,name=annual_income,json=annualIncome" json:"annual_income,omitempty"`
	Graduate                    *GraduateInfo              `protobuf:"bytes,4,opt,name=graduate" json:"graduate,omitempty"` // ポインタだがエラー時を除き必ずあるので普通に埋め込む
	Job                         *JobInfo                   `protobuf:"bytes,5,opt,name=job" json:"job,omitempty"`           // ポインタだがエラー時を除き必ずあるので普通に埋め込む
	Experiences                 []*Experience              `protobuf:"bytes,6,rep,name=experiences" json:"experiences,omitempty"`
	Lang                        *LangInfo                  `protobuf:"bytes,7,opt,name=lang" json:"lang,omitempty"` // ポインタだがエラー時を除き必ずあるので普通に埋め込む
	OfficeExcelSkillIds         []int32                    `protobuf:"varint,8,rep,packed,name=office_excel_skill_ids,json=officeExcelSkillIds" json:"office_excel_skill_ids,omitempty"`
	OfficeAccessSkillIds        []int32                    `protobuf:"varint,9,rep,packed,name=office_access_skill_ids,json=officeAccessSkillIds" json:"office_access_skill_ids,omitempty"`
	CompanyNameIds              []int32                    `protobuf:"varint,10,rep,packed,name=company_name_ids,json=companyNameIds" json:"company_name_ids,omitempty"`
	LicenceIds                  []int32                    `protobuf:"varint,11,rep,packed,name=licence_ids,json=licenceIds" json:"licence_ids,omitempty"`
	DriverLicence               *DriverLicence             `protobuf:"bytes,12,opt,name=driver_licence,json=driverLicence" json:"driver_licence,omitempty"`
	HasResume                   bool                       `protobuf:"varint,13,opt,name=has_resume,json=hasResume" json:"has_resume,omitempty"`
	HasPortfolio                bool                       `protobuf:"varint,14,opt,name=has_portfolio,json=hasPortfolio" json:"has_portfolio,omitempty"`
	WorkedAbroad                bool                       `protobuf:"varint,15,opt,name=worked_abroad,json=workedAbroad" json:"worked_abroad,omitempty"`
	Resume                      *Resume                    `protobuf:"bytes,16,opt,name=Resume" json:"Resume,omitempty"`
	Competency                  *Competency                `protobuf:"bytes,17,opt,name=Competency" json:"Competency,omitempty"`
	Bias                        *Bias                      `protobuf:"bytes,18,opt,name=Bias" json:"Bias,omitempty"`
	PrefectureId                int32                      `protobuf:"varint,19,opt,name=prefecture_id,json=prefectureId" json:"prefecture_id,omitempty"`
	BlockAllCompaniesFlg        bool                       `protobuf:"varint,20,opt,name=block_all_companies_flg,json=blockAllCompaniesFlg" json:"block_all_companies_flg,omitempty"`
	HpApplyCompanyIds           []int32                    `protobuf:"varint,21,rep,packed,name=hp_apply_company_ids,json=hpApplyCompanyIds" json:"hp_apply_company_ids,omitempty"`
	RegisteredAt                *timestamppb.Timestamp     `protobuf:"bytes,22,opt,name=registered_at,json=registeredAt" json:"registered_at,omitempty"`
	OutsourcingSearch           *OutsourcingSearch         `protobuf:"bytes,24,opt,name=outsourcing_search,json=outsourcingSearch" json:"outsourcing_search,omitempty"`
	AllCareerJobTypeAndExpTerms []*AllCareerJobTypeExpTerm `protobuf:"bytes,25,rep,name=all_career_job_type_and_exp_terms,json=allCareerJobTypeAndExpTerms" json:"all_career_job_type_and_exp_terms,omitempty"`
	CityId                      int32                      `protobuf:"varint,26,opt,name=city_id,json=cityId" json:"city_id,omitempty"`
	GenderId                    *int32                     `protobuf:"varint,27,opt,name=gender_id,json=genderId" json:"gender_id,omitempty"` // 性別ID
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_user_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetUserId() int32 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *Profile) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Profile) GetAnnualIncome() int32 {
	if x != nil {
		return x.AnnualIncome
	}
	return 0
}

func (x *Profile) GetGraduate() *GraduateInfo {
	if x != nil {
		return x.Graduate
	}
	return nil
}

func (x *Profile) GetJob() *JobInfo {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *Profile) GetExperiences() []*Experience {
	if x != nil {
		return x.Experiences
	}
	return nil
}

func (x *Profile) GetLang() *LangInfo {
	if x != nil {
		return x.Lang
	}
	return nil
}

func (x *Profile) GetOfficeExcelSkillIds() []int32 {
	if x != nil {
		return x.OfficeExcelSkillIds
	}
	return nil
}

func (x *Profile) GetOfficeAccessSkillIds() []int32 {
	if x != nil {
		return x.OfficeAccessSkillIds
	}
	return nil
}

func (x *Profile) GetCompanyNameIds() []int32 {
	if x != nil {
		return x.CompanyNameIds
	}
	return nil
}

func (x *Profile) GetLicenceIds() []int32 {
	if x != nil {
		return x.LicenceIds
	}
	return nil
}

func (x *Profile) GetDriverLicence() *DriverLicence {
	if x != nil {
		return x.DriverLicence
	}
	return nil
}

func (x *Profile) GetHasResume() bool {
	if x != nil {
		return x.HasResume
	}
	return false
}

func (x *Profile) GetHasPortfolio() bool {
	if x != nil {
		return x.HasPortfolio
	}
	return false
}

func (x *Profile) GetWorkedAbroad() bool {
	if x != nil {
		return x.WorkedAbroad
	}
	return false
}

func (x *Profile) GetResume() *Resume {
	if x != nil {
		return x.Resume
	}
	return nil
}

func (x *Profile) GetCompetency() *Competency {
	if x != nil {
		return x.Competency
	}
	return nil
}

func (x *Profile) GetBias() *Bias {
	if x != nil {
		return x.Bias
	}
	return nil
}

func (x *Profile) GetPrefectureId() int32 {
	if x != nil {
		return x.PrefectureId
	}
	return 0
}

func (x *Profile) GetBlockAllCompaniesFlg() bool {
	if x != nil {
		return x.BlockAllCompaniesFlg
	}
	return false
}

func (x *Profile) GetHpApplyCompanyIds() []int32 {
	if x != nil {
		return x.HpApplyCompanyIds
	}
	return nil
}

func (x *Profile) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *Profile) GetOutsourcingSearch() *OutsourcingSearch {
	if x != nil {
		return x.OutsourcingSearch
	}
	return nil
}

func (x *Profile) GetAllCareerJobTypeAndExpTerms() []*AllCareerJobTypeExpTerm {
	if x != nil {
		return x.AllCareerJobTypeAndExpTerms
	}
	return nil
}

func (x *Profile) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *Profile) GetGenderId() int32 {
	if x != nil && x.GenderId != nil {
		return *x.GenderId
	}
	return 0
}

type DriverLicence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasLicence    bool                   `protobuf:"varint,1,opt,name=has_licence,json=hasLicence" json:"has_licence,omitempty"` // HasLicence True: 必須
	IsFull        bool                   `protobuf:"varint,2,opt,name=is_full,json=isFull" json:"is_full,omitempty"`             // IsFull MT車運転可能かどうか
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLicence) Reset() {
	*x = DriverLicence{}
	mi := &file_user_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLicence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLicence) ProtoMessage() {}

func (x *DriverLicence) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLicence.ProtoReflect.Descriptor instead.
func (*DriverLicence) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{1}
}

func (x *DriverLicence) GetHasLicence() bool {
	if x != nil {
		return x.HasLicence
	}
	return false
}

func (x *DriverLicence) GetIsFull() bool {
	if x != nil {
		return x.IsFull
	}
	return false
}

type GraduateInfo struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	Year                                  int32                  `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	SchoolType                            int32                  `protobuf:"varint,2,opt,name=school_type,json=schoolType" json:"school_type,omitempty"`
	SchoolRank                            int32                  `protobuf:"varint,3,opt,name=school_rank,json=schoolRank" json:"school_rank,omitempty"`
	SchoolId                              int32                  `protobuf:"varint,4,opt,name=school_id,json=schoolId" json:"school_id,omitempty"`
	DepartId                              int32                  `protobuf:"varint,5,opt,name=depart_id,json=departId" json:"depart_id,omitempty"`
	ProfessionalTrainingCollegeCategoryId int32                  `protobuf:"varint,6,opt,name=professional_training_college_category_id,json=professionalTrainingCollegeCategoryId" json:"professional_training_college_category_id,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *GraduateInfo) Reset() {
	*x = GraduateInfo{}
	mi := &file_user_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraduateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraduateInfo) ProtoMessage() {}

func (x *GraduateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraduateInfo.ProtoReflect.Descriptor instead.
func (*GraduateInfo) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GraduateInfo) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GraduateInfo) GetSchoolType() int32 {
	if x != nil {
		return x.SchoolType
	}
	return 0
}

func (x *GraduateInfo) GetSchoolRank() int32 {
	if x != nil {
		return x.SchoolRank
	}
	return 0
}

func (x *GraduateInfo) GetSchoolId() int32 {
	if x != nil {
		return x.SchoolId
	}
	return 0
}

func (x *GraduateInfo) GetDepartId() int32 {
	if x != nil {
		return x.DepartId
	}
	return 0
}

func (x *GraduateInfo) GetProfessionalTrainingCollegeCategoryId() int32 {
	if x != nil {
		return x.ProfessionalTrainingCollegeCategoryId
	}
	return 0
}

type JobInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ManagementExpTermId   *int32                 `protobuf:"varint,1,opt,name=management_exp_term_id,json=managementExpTermId" json:"management_exp_term_id,omitempty"`
	ManagementPeopleQtyId int32                  `protobuf:"varint,2,opt,name=management_people_qty_id,json=managementPeopleQtyId" json:"management_people_qty_id,omitempty"`
	ExpCompanyId          int32                  `protobuf:"varint,3,opt,name=exp_company_id,json=expCompanyId" json:"exp_company_id,omitempty"` // 経験社数ID
	RetireMonth           int32                  `protobuf:"varint,4,opt,name=retire_month,json=retireMonth" json:"retire_month,omitempty"`      // 職歴なし離職中は離職月数を0ではなく最大値にしている
	CompanyNameId         int32                  `protobuf:"varint,5,opt,name=company_name_id,json=companyNameId" json:"company_name_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_user_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{3}
}

func (x *JobInfo) GetManagementExpTermId() int32 {
	if x != nil && x.ManagementExpTermId != nil {
		return *x.ManagementExpTermId
	}
	return 0
}

func (x *JobInfo) GetManagementPeopleQtyId() int32 {
	if x != nil {
		return x.ManagementPeopleQtyId
	}
	return 0
}

func (x *JobInfo) GetExpCompanyId() int32 {
	if x != nil {
		return x.ExpCompanyId
	}
	return 0
}

func (x *JobInfo) GetRetireMonth() int32 {
	if x != nil {
		return x.RetireMonth
	}
	return 0
}

func (x *JobInfo) GetCompanyNameId() int32 {
	if x != nil {
		return x.CompanyNameId
	}
	return 0
}

type Experience struct {
	state            protoimpl.MessageState            `protogen:"open.v1"`
	UserCompanyId    int32                             `protobuf:"varint,1,opt,name=user_company_id,json=userCompanyId" json:"user_company_id,omitempty"`          // ユーザー経験企業ID
	CompanyNameId    int32                             `protobuf:"varint,2,opt,name=company_name_id,json=companyNameId" json:"company_name_id,omitempty"`          // 企業NameID
	EmployeeQtyId    int32                             `protobuf:"varint,3,opt,name=employee_qty_id,json=employeeQtyId" json:"employee_qty_id,omitempty"`          // 企業の規模
	EmploymentTypeId int32                             `protobuf:"varint,4,opt,name=employment_type_id,json=employmentTypeId" json:"employment_type_id,omitempty"` // 直近の雇用形態
	IndustrySmallId  *int32                            `protobuf:"varint,5,opt,name=industry_small_id,json=industrySmallId" json:"industry_small_id,omitempty"`    // 業種ID
	IsRecent         bool                              `protobuf:"varint,6,opt,name=is_recent,json=isRecent" json:"is_recent,omitempty"`                           // 直近かどうか
	RetireYear       int32                             `protobuf:"varint,7,opt,name=retire_year,json=retireYear" json:"retire_year,omitempty"`                     // 退職年月
	RetireMonth      int32                             `protobuf:"varint,8,opt,name=retire_month,json=retireMonth" json:"retire_month,omitempty"`                  // とりあえずここが 0 なら RetireYm = nil に
	JobTypes         []*Experience_JobTypeExpTerm      `protobuf:"bytes,9,rep,name=job_types,json=jobTypes" json:"job_types,omitempty"`
	Skills           []*Experience_JobTypeSkillExpTerm `protobuf:"bytes,10,rep,name=skills" json:"skills,omitempty"`
	JoinYear         int32                             `protobuf:"varint,11,opt,name=join_year,json=joinYear" json:"join_year,omitempty"`
	JoinMonth        int32                             `protobuf:"varint,12,opt,name=join_month,json=joinMonth" json:"join_month,omitempty"` // ここが 0 なら JoinYm = nil に
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Experience) Reset() {
	*x = Experience{}
	mi := &file_user_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience) ProtoMessage() {}

func (x *Experience) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience.ProtoReflect.Descriptor instead.
func (*Experience) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{4}
}

func (x *Experience) GetUserCompanyId() int32 {
	if x != nil {
		return x.UserCompanyId
	}
	return 0
}

func (x *Experience) GetCompanyNameId() int32 {
	if x != nil {
		return x.CompanyNameId
	}
	return 0
}

func (x *Experience) GetEmployeeQtyId() int32 {
	if x != nil {
		return x.EmployeeQtyId
	}
	return 0
}

func (x *Experience) GetEmploymentTypeId() int32 {
	if x != nil {
		return x.EmploymentTypeId
	}
	return 0
}

func (x *Experience) GetIndustrySmallId() int32 {
	if x != nil && x.IndustrySmallId != nil {
		return *x.IndustrySmallId
	}
	return 0
}

func (x *Experience) GetIsRecent() bool {
	if x != nil {
		return x.IsRecent
	}
	return false
}

func (x *Experience) GetRetireYear() int32 {
	if x != nil {
		return x.RetireYear
	}
	return 0
}

func (x *Experience) GetRetireMonth() int32 {
	if x != nil {
		return x.RetireMonth
	}
	return 0
}

func (x *Experience) GetJobTypes() []*Experience_JobTypeExpTerm {
	if x != nil {
		return x.JobTypes
	}
	return nil
}

func (x *Experience) GetSkills() []*Experience_JobTypeSkillExpTerm {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Experience) GetJoinYear() int32 {
	if x != nil {
		return x.JoinYear
	}
	return 0
}

func (x *Experience) GetJoinMonth() int32 {
	if x != nil {
		return x.JoinMonth
	}
	return 0
}

type LangInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EngLevel      int32                  `protobuf:"varint,1,opt,name=eng_level,json=engLevel" json:"eng_level,omitempty"`
	EngToeic      int32                  `protobuf:"varint,2,opt,name=eng_toeic,json=engToeic" json:"eng_toeic,omitempty"`
	EngToefli     int32                  `protobuf:"varint,3,opt,name=eng_toefli,json=engToefli" json:"eng_toefli,omitempty"`
	EngToeflp     int32                  `protobuf:"varint,4,opt,name=eng_toeflp,json=engToeflp" json:"eng_toeflp,omitempty"`
	OtherIds      []int32                `protobuf:"varint,5,rep,packed,name=other_ids,json=otherIds" json:"other_ids,omitempty"`
	OtherLevels   []int32                `protobuf:"varint,6,rep,packed,name=other_levels,json=otherLevels" json:"other_levels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LangInfo) Reset() {
	*x = LangInfo{}
	mi := &file_user_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LangInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LangInfo) ProtoMessage() {}

func (x *LangInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LangInfo.ProtoReflect.Descriptor instead.
func (*LangInfo) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{5}
}

func (x *LangInfo) GetEngLevel() int32 {
	if x != nil {
		return x.EngLevel
	}
	return 0
}

func (x *LangInfo) GetEngToeic() int32 {
	if x != nil {
		return x.EngToeic
	}
	return 0
}

func (x *LangInfo) GetEngToefli() int32 {
	if x != nil {
		return x.EngToefli
	}
	return 0
}

func (x *LangInfo) GetEngToeflp() int32 {
	if x != nil {
		return x.EngToeflp
	}
	return 0
}

func (x *LangInfo) GetOtherIds() []int32 {
	if x != nil {
		return x.OtherIds
	}
	return nil
}

func (x *LangInfo) GetOtherLevels() []int32 {
	if x != nil {
		return x.OtherLevels
	}
	return nil
}

type Resume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContents  string                 `protobuf:"bytes,1,opt,name=FileContents" json:"FileContents,omitempty"`
	TextContents  string                 `protobuf:"bytes,2,opt,name=TextContents" json:"TextContents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resume) Reset() {
	*x = Resume{}
	mi := &file_user_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resume) ProtoMessage() {}

func (x *Resume) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resume.ProtoReflect.Descriptor instead.
func (*Resume) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{6}
}

func (x *Resume) GetFileContents() string {
	if x != nil {
		return x.FileContents
	}
	return ""
}

func (x *Resume) GetTextContents() string {
	if x != nil {
		return x.TextContents
	}
	return ""
}

type AllCareerJobTypeExpTerm struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobTypeSmallId int32                  `protobuf:"varint,1,opt,name=job_type_small_id,json=jobTypeSmallId" json:"job_type_small_id,omitempty"`
	ExpTermId      *int32                 `protobuf:"varint,2,opt,name=exp_term_id,json=expTermId" json:"exp_term_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllCareerJobTypeExpTerm) Reset() {
	*x = AllCareerJobTypeExpTerm{}
	mi := &file_user_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllCareerJobTypeExpTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllCareerJobTypeExpTerm) ProtoMessage() {}

func (x *AllCareerJobTypeExpTerm) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllCareerJobTypeExpTerm.ProtoReflect.Descriptor instead.
func (*AllCareerJobTypeExpTerm) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{7}
}

func (x *AllCareerJobTypeExpTerm) GetJobTypeSmallId() int32 {
	if x != nil {
		return x.JobTypeSmallId
	}
	return 0
}

func (x *AllCareerJobTypeExpTerm) GetExpTermId() int32 {
	if x != nil && x.ExpTermId != nil {
		return *x.ExpTermId
	}
	return 0
}

type Competency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vanity        int32                  `protobuf:"varint,1,opt,name=vanity" json:"vanity,omitempty"` // 虚栄心
	Axes          *Competency_Axes       `protobuf:"bytes,2,opt,name=axes" json:"axes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Competency) Reset() {
	*x = Competency{}
	mi := &file_user_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Competency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Competency) ProtoMessage() {}

func (x *Competency) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Competency.ProtoReflect.Descriptor instead.
func (*Competency) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{8}
}

func (x *Competency) GetVanity() int32 {
	if x != nil {
		return x.Vanity
	}
	return 0
}

func (x *Competency) GetAxes() *Competency_Axes {
	if x != nil {
		return x.Axes
	}
	return nil
}

type Bias struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Conformity                    int32                  `protobuf:"varint,1,opt,name=conformity" json:"conformity,omitempty"`                                                                               // 同調度
	ImpulseControl                int32                  `protobuf:"varint,2,opt,name=impulse_control,json=impulseControl" json:"impulse_control,omitempty"`                                                 // 衝動制御
	FramingEffect                 int32                  `protobuf:"varint,3,opt,name=framing_effect,json=framingEffect" json:"framing_effect,omitempty"`                                                    // フレーミング効果
	FocusedAttention              int32                  `protobuf:"varint,4,opt,name=focused_attention,json=focusedAttention" json:"focused_attention,omitempty"`                                           // 焦点的注意
	DividedAttention              int32                  `protobuf:"varint,5,opt,name=divided_attention,json=dividedAttention" json:"divided_attention,omitempty"`                                           // 全体的注意
	NegativeEmotions              int32                  `protobuf:"varint,6,opt,name=negative_emotions,json=negativeEmotions" json:"negative_emotions,omitempty"`                                           // 否定的感情
	SunkCost                      int32                  `protobuf:"varint,7,opt,name=sunk_cost,json=sunkCost" json:"sunk_cost,omitempty"`                                                                   // サンクコスト効果
	Impatience                    int32                  `protobuf:"varint,8,opt,name=impatience" json:"impatience,omitempty"`                                                                               // 時間選好（せっかち度）
	DeclineEvaluationAversion     int32                  `protobuf:"varint,9,opt,name=decline_evaluation_aversion,json=declineEvaluationAversion" json:"decline_evaluation_aversion,omitempty"`              // 評価下落回避
	LossAversion                  int32                  `protobuf:"varint,10,opt,name=loss_aversion,json=lossAversion" json:"loss_aversion,omitempty"`                                                      // 損失回避
	EffortAversion                int32                  `protobuf:"varint,11,opt,name=effort_aversion,json=effortAversion" json:"effort_aversion,omitempty"`                                                // 労力回避
	RegretAversion                int32                  `protobuf:"varint,12,opt,name=regret_aversion,json=regretAversion" json:"regret_aversion,omitempty"`                                                // 失敗回避
	RangeOthers                   int32                  `protobuf:"varint,13,opt,name=range_others,json=rangeOthers" json:"range_others,omitempty"`                                                         // 他人要因
	RangeMyself                   int32                  `protobuf:"varint,14,opt,name=range_myself,json=rangeMyself" json:"range_myself,omitempty"`                                                         // 自己要因
	Empathy                       int32                  `protobuf:"varint,15,opt,name=empathy" json:"empathy,omitempty"`                                                                                    // 共感性
	StatusQuo                     int32                  `protobuf:"varint,16,opt,name=status_quo,json=statusQuo" json:"status_quo,omitempty"`                                                               // 現状維持バイアス
	PredictiveBehavior            int32                  `protobuf:"varint,17,opt,name=predictive_behavior,json=predictiveBehavior" json:"predictive_behavior,omitempty"`                                    // 予測態度
	BiasControl                   int32                  `protobuf:"varint,18,opt,name=bias_control,json=biasControl" json:"bias_control,omitempty"`                                                         // バイアス制御
	AltruismSelfishnessEvaluation int32                  `protobuf:"varint,19,opt,name=altruism_selfishness_evaluation,json=altruismSelfishnessEvaluation" json:"altruism_selfishness_evaluation,omitempty"` // 利他性・利己性の10段階評価
	RiskTolerance                 int32                  `protobuf:"varint,20,opt,name=risk_tolerance,json=riskTolerance" json:"risk_tolerance,omitempty"`                                                   // リスク許容度
	EndsMeans                     int32                  `protobuf:"varint,21,opt,name=ends_means,json=endsMeans" json:"ends_means,omitempty"`                                                               // 目的思考
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Bias) Reset() {
	*x = Bias{}
	mi := &file_user_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bias) ProtoMessage() {}

func (x *Bias) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bias.ProtoReflect.Descriptor instead.
func (*Bias) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{9}
}

func (x *Bias) GetConformity() int32 {
	if x != nil {
		return x.Conformity
	}
	return 0
}

func (x *Bias) GetImpulseControl() int32 {
	if x != nil {
		return x.ImpulseControl
	}
	return 0
}

func (x *Bias) GetFramingEffect() int32 {
	if x != nil {
		return x.FramingEffect
	}
	return 0
}

func (x *Bias) GetFocusedAttention() int32 {
	if x != nil {
		return x.FocusedAttention
	}
	return 0
}

func (x *Bias) GetDividedAttention() int32 {
	if x != nil {
		return x.DividedAttention
	}
	return 0
}

func (x *Bias) GetNegativeEmotions() int32 {
	if x != nil {
		return x.NegativeEmotions
	}
	return 0
}

func (x *Bias) GetSunkCost() int32 {
	if x != nil {
		return x.SunkCost
	}
	return 0
}

func (x *Bias) GetImpatience() int32 {
	if x != nil {
		return x.Impatience
	}
	return 0
}

func (x *Bias) GetDeclineEvaluationAversion() int32 {
	if x != nil {
		return x.DeclineEvaluationAversion
	}
	return 0
}

func (x *Bias) GetLossAversion() int32 {
	if x != nil {
		return x.LossAversion
	}
	return 0
}

func (x *Bias) GetEffortAversion() int32 {
	if x != nil {
		return x.EffortAversion
	}
	return 0
}

func (x *Bias) GetRegretAversion() int32 {
	if x != nil {
		return x.RegretAversion
	}
	return 0
}

func (x *Bias) GetRangeOthers() int32 {
	if x != nil {
		return x.RangeOthers
	}
	return 0
}

func (x *Bias) GetRangeMyself() int32 {
	if x != nil {
		return x.RangeMyself
	}
	return 0
}

func (x *Bias) GetEmpathy() int32 {
	if x != nil {
		return x.Empathy
	}
	return 0
}

func (x *Bias) GetStatusQuo() int32 {
	if x != nil {
		return x.StatusQuo
	}
	return 0
}

func (x *Bias) GetPredictiveBehavior() int32 {
	if x != nil {
		return x.PredictiveBehavior
	}
	return 0
}

func (x *Bias) GetBiasControl() int32 {
	if x != nil {
		return x.BiasControl
	}
	return 0
}

func (x *Bias) GetAltruismSelfishnessEvaluation() int32 {
	if x != nil {
		return x.AltruismSelfishnessEvaluation
	}
	return 0
}

func (x *Bias) GetRiskTolerance() int32 {
	if x != nil {
		return x.RiskTolerance
	}
	return 0
}

func (x *Bias) GetEndsMeans() int32 {
	if x != nil {
		return x.EndsMeans
	}
	return 0
}

type OutsourcingSearch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkAddress    []int32                `protobuf:"varint,1,rep,packed,name=work_address,json=workAddress" json:"work_address,omitempty"`
	WorkingTime    []int32                `protobuf:"varint,2,rep,packed,name=working_time,json=workingTime" json:"working_time,omitempty"`
	ContractPeriod []int32                `protobuf:"varint,3,rep,packed,name=contract_period,json=contractPeriod" json:"contract_period,omitempty"`
	RemoteWork     *int32                 `protobuf:"varint,4,opt,name=remote_work,json=remoteWork" json:"remote_work,omitempty"`
	HourlyFee      *int32                 `protobuf:"varint,5,opt,name=hourly_fee,json=hourlyFee" json:"hourly_fee,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutsourcingSearch) Reset() {
	*x = OutsourcingSearch{}
	mi := &file_user_profile_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutsourcingSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutsourcingSearch) ProtoMessage() {}

func (x *OutsourcingSearch) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutsourcingSearch.ProtoReflect.Descriptor instead.
func (*OutsourcingSearch) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{10}
}

func (x *OutsourcingSearch) GetWorkAddress() []int32 {
	if x != nil {
		return x.WorkAddress
	}
	return nil
}

func (x *OutsourcingSearch) GetWorkingTime() []int32 {
	if x != nil {
		return x.WorkingTime
	}
	return nil
}

func (x *OutsourcingSearch) GetContractPeriod() []int32 {
	if x != nil {
		return x.ContractPeriod
	}
	return nil
}

func (x *OutsourcingSearch) GetRemoteWork() int32 {
	if x != nil && x.RemoteWork != nil {
		return *x.RemoteWork
	}
	return 0
}

func (x *OutsourcingSearch) GetHourlyFee() int32 {
	if x != nil && x.HourlyFee != nil {
		return *x.HourlyFee
	}
	return 0
}

type Experience_JobTypeExpTerm struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobTypeSmallId int32                  `protobuf:"varint,1,opt,name=job_type_small_id,json=jobTypeSmallId" json:"job_type_small_id,omitempty"`
	ExpTermId      *int32                 `protobuf:"varint,2,opt,name=exp_term_id,json=expTermId" json:"exp_term_id,omitempty"`
	IsSpecial      bool                   `protobuf:"varint,3,opt,name=is_special,json=isSpecial" json:"is_special,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Experience_JobTypeExpTerm) Reset() {
	*x = Experience_JobTypeExpTerm{}
	mi := &file_user_profile_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience_JobTypeExpTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience_JobTypeExpTerm) ProtoMessage() {}

func (x *Experience_JobTypeExpTerm) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience_JobTypeExpTerm.ProtoReflect.Descriptor instead.
func (*Experience_JobTypeExpTerm) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Experience_JobTypeExpTerm) GetJobTypeSmallId() int32 {
	if x != nil {
		return x.JobTypeSmallId
	}
	return 0
}

func (x *Experience_JobTypeExpTerm) GetExpTermId() int32 {
	if x != nil && x.ExpTermId != nil {
		return *x.ExpTermId
	}
	return 0
}

func (x *Experience_JobTypeExpTerm) GetIsSpecial() bool {
	if x != nil {
		return x.IsSpecial
	}
	return false
}

type Experience_JobTypeSkillExpTerm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobTypeId     int32                  `protobuf:"varint,1,opt,name=job_type_id,json=jobTypeId" json:"job_type_id,omitempty"` // 6桁とは限らないっぽい
	SkillId       int32                  `protobuf:"varint,2,opt,name=skill_id,json=skillId" json:"skill_id,omitempty"`
	ExpTermId     int32                  `protobuf:"varint,3,opt,name=exp_term_id,json=expTermId" json:"exp_term_id,omitempty"`
	InputSkill    string                 `protobuf:"bytes,4,opt,name=input_skill,json=inputSkill" json:"input_skill,omitempty"`
	IsSpecial     bool                   `protobuf:"varint,5,opt,name=is_special,json=isSpecial" json:"is_special,omitempty"` // 得意なスキル
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Experience_JobTypeSkillExpTerm) Reset() {
	*x = Experience_JobTypeSkillExpTerm{}
	mi := &file_user_profile_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Experience_JobTypeSkillExpTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Experience_JobTypeSkillExpTerm) ProtoMessage() {}

func (x *Experience_JobTypeSkillExpTerm) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Experience_JobTypeSkillExpTerm.ProtoReflect.Descriptor instead.
func (*Experience_JobTypeSkillExpTerm) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Experience_JobTypeSkillExpTerm) GetJobTypeId() int32 {
	if x != nil {
		return x.JobTypeId
	}
	return 0
}

func (x *Experience_JobTypeSkillExpTerm) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *Experience_JobTypeSkillExpTerm) GetExpTermId() int32 {
	if x != nil {
		return x.ExpTermId
	}
	return 0
}

func (x *Experience_JobTypeSkillExpTerm) GetInputSkill() string {
	if x != nil {
		return x.InputSkill
	}
	return ""
}

func (x *Experience_JobTypeSkillExpTerm) GetIsSpecial() bool {
	if x != nil {
		return x.IsSpecial
	}
	return false
}

type Competency_Axes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// パーソナリティ
	ManagementStyle        int32 `protobuf:"varint,1,opt,name=management_style,json=managementStyle" json:"management_style,omitempty"`                       // マネジメントスタイル
	Vitality               int32 `protobuf:"varint,2,opt,name=vitality" json:"vitality,omitempty"`                                                            // 活力
	Sociability            int32 `protobuf:"varint,3,opt,name=sociability" json:"sociability,omitempty"`                                                      // 人あたり
	Teamwork               int32 `protobuf:"varint,4,opt,name=teamwork" json:"teamwork,omitempty"`                                                            // チームワーク
	Creativity             int32 `protobuf:"varint,5,opt,name=creativity" json:"creativity,omitempty"`                                                        // 創造性
	ProblemSolving         int32 `protobuf:"varint,6,opt,name=problem_solving,json=problemSolving" json:"problem_solving,omitempty"`                          // 問題解決力
	PressureTolerance      int32 `protobuf:"varint,7,opt,name=pressure_tolerance,json=pressureTolerance" json:"pressure_tolerance,omitempty"`                 // プレッシャーへの耐性
	Coordination           int32 `protobuf:"varint,8,opt,name=coordination" json:"coordination,omitempty"`                                                    // 調整力
	Leadership             int32 `protobuf:"varint,9,opt,name=leadership" json:"leadership,omitempty"`                                                        // リーダーシップ
	Adaptability           int32 `protobuf:"varint,10,opt,name=adaptability" json:"adaptability,omitempty"`                                                   // 対応力
	Perseverance           int32 `protobuf:"varint,11,opt,name=perseverance" json:"perseverance,omitempty"`                                                   // 粘り強さ
	Focus                  int32 `protobuf:"varint,12,opt,name=focus" json:"focus,omitempty"`                                                                 // 一点集中
	Planning               int32 `protobuf:"varint,13,opt,name=planning" json:"planning,omitempty"`                                                           // 計画性
	InterpersonalInfluence int32 `protobuf:"varint,14,opt,name=interpersonal_influence,json=interpersonalInfluence" json:"interpersonal_influence,omitempty"` // 対人影響
	GoalSetting            int32 `protobuf:"varint,15,opt,name=goal_setting,json=goalSetting" json:"goal_setting,omitempty"`                                  // 目標の立て方
	Decisiveness           int32 `protobuf:"varint,16,opt,name=decisiveness" json:"decisiveness,omitempty"`                                                   // 決断力
	AnalyticalAbility      int32 `protobuf:"varint,17,opt,name=analytical_ability,json=analyticalAbility" json:"analytical_ability,omitempty"`                // 分析力
	Conceptualization      int32 `protobuf:"varint,18,opt,name=conceptualization" json:"conceptualization,omitempty"`                                         // 概念化
	Continuity             int32 `protobuf:"varint,19,opt,name=continuity" json:"continuity,omitempty"`                                                       // 継続力
	RelationshipBuilding   int32 `protobuf:"varint,20,opt,name=relationship_building,json=relationshipBuilding" json:"relationship_building,omitempty"`       // 人間関係の構築
	Empathy                int32 `protobuf:"varint,21,opt,name=empathy" json:"empathy,omitempty"`                                                             // 共感力
	SelfLearning           int32 `protobuf:"varint,22,opt,name=self_learning,json=selfLearning" json:"self_learning,omitempty"`                               // 自学
	// 上司部下適正
	Directive   int32 `protobuf:"varint,23,opt,name=directive" json:"directive,omitempty"`     // 指示型
	Delegation  int32 `protobuf:"varint,24,opt,name=delegation" json:"delegation,omitempty"`   // 委任型
	Listening   int32 `protobuf:"varint,25,opt,name=listening" json:"listening,omitempty"`     // 傾聴型
	Dialogue    int32 `protobuf:"varint,26,opt,name=dialogue" json:"dialogue,omitempty"`       // 対話型
	Negotiation int32 `protobuf:"varint,27,opt,name=negotiation" json:"negotiation,omitempty"` // 交渉型
	Obedient    int32 `protobuf:"varint,28,opt,name=obedient" json:"obedient,omitempty"`       // 従順型
	Autonomous  int32 `protobuf:"varint,29,opt,name=autonomous" json:"autonomous,omitempty"`   // 自律型
	Cooperative int32 `protobuf:"varint,30,opt,name=cooperative" json:"cooperative,omitempty"` // 協調型
	Proactive   int32 `protobuf:"varint,31,opt,name=proactive" json:"proactive,omitempty"`     // 提案型
	Assertive   int32 `protobuf:"varint,32,opt,name=assertive" json:"assertive,omitempty"`     // 主張型
	// ストレス要因
	UncertainSituations           int32 `protobuf:"varint,33,opt,name=uncertain_situations,json=uncertainSituations" json:"uncertain_situations,omitempty"`                                   // 不確実な状況
	ResponseToSuddenChanges       int32 `protobuf:"varint,34,opt,name=response_to_sudden_changes,json=responseToSuddenChanges" json:"response_to_sudden_changes,omitempty"`                   // 急な変化への対応
	HardWork                      int32 `protobuf:"varint,35,opt,name=hard_work,json=hardWork" json:"hard_work,omitempty"`                                                                    // ハードワーク
	LackOfPlanning                int32 `protobuf:"varint,36,opt,name=lack_of_planning,json=lackOfPlanning" json:"lack_of_planning,omitempty"`                                                // 計画性のなさ
	StrictManagement              int32 `protobuf:"varint,37,opt,name=strict_management,json=strictManagement" json:"strict_management,omitempty"`                                            // 厳しい管理
	LackOfEvaluation              int32 `protobuf:"varint,38,opt,name=lack_of_evaluation,json=lackOfEvaluation" json:"lack_of_evaluation,omitempty"`                                          // 評価の欠如
	InabilityToExerciseInitiative int32 `protobuf:"varint,39,opt,name=inability_to_exercise_initiative,json=inabilityToExerciseInitiative" json:"inability_to_exercise_initiative,omitempty"` // 主体性が発揮できない
	ExclusionFromDecisionMaking   int32 `protobuf:"varint,40,opt,name=exclusion_from_decision_making,json=exclusionFromDecisionMaking" json:"exclusion_from_decision_making,omitempty"`       // 意思決定に関与できない
	LowStandards                  int32 `protobuf:"varint,41,opt,name=low_standards,json=lowStandards" json:"low_standards,omitempty"`                                                        // 要求水準が低い
	HighAnalysis                  int32 `protobuf:"varint,42,opt,name=high_analysis,json=highAnalysis" json:"high_analysis,omitempty"`                                                        // 高度な分析
	LackOfLearningOpportunities   int32 `protobuf:"varint,43,opt,name=lack_of_learning_opportunities,json=lackOfLearningOpportunities" json:"lack_of_learning_opportunities,omitempty"`       // 学習機会の不足
	FollowingPrecedents           int32 `protobuf:"varint,44,opt,name=following_precedents,json=followingPrecedents" json:"following_precedents,omitempty"`                                   // 前例踏襲
	RoutineWork                   int32 `protobuf:"varint,45,opt,name=routine_work,json=routineWork" json:"routine_work,omitempty"`                                                           // 定型業務
	DifficultDecisions            int32 `protobuf:"varint,46,opt,name=difficult_decisions,json=difficultDecisions" json:"difficult_decisions,omitempty"`                                      // 困難な決断
	NegotiationTasks              int32 `protobuf:"varint,47,opt,name=negotiation_tasks,json=negotiationTasks" json:"negotiation_tasks,omitempty"`                                            // 交渉業務
	ConsensusBuilding             int32 `protobuf:"varint,48,opt,name=consensus_building,json=consensusBuilding" json:"consensus_building,omitempty"`                                         // 合意形成
	ConflictWithOthers            int32 `protobuf:"varint,49,opt,name=conflict_with_others,json=conflictWithOthers" json:"conflict_with_others,omitempty"`                                    // 周囲との対立
	DryWorkplace                  int32 `protobuf:"varint,50,opt,name=dry_workplace,json=dryWorkplace" json:"dry_workplace,omitempty"`                                                        // ドライな職場
	CaughtInTheMiddle             int32 `protobuf:"varint,51,opt,name=caught_in_the_middle,json=caughtInTheMiddle" json:"caught_in_the_middle,omitempty"`                                     // 板挟み状態
	CollaborativeWork             int32 `protobuf:"varint,52,opt,name=collaborative_work,json=collaborativeWork" json:"collaborative_work,omitempty"`                                         // 共同業務
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Competency_Axes) Reset() {
	*x = Competency_Axes{}
	mi := &file_user_profile_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Competency_Axes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Competency_Axes) ProtoMessage() {}

func (x *Competency_Axes) ProtoReflect() protoreflect.Message {
	mi := &file_user_profile_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Competency_Axes.ProtoReflect.Descriptor instead.
func (*Competency_Axes) Descriptor() ([]byte, []int) {
	return file_user_profile_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Competency_Axes) GetManagementStyle() int32 {
	if x != nil {
		return x.ManagementStyle
	}
	return 0
}

func (x *Competency_Axes) GetVitality() int32 {
	if x != nil {
		return x.Vitality
	}
	return 0
}

func (x *Competency_Axes) GetSociability() int32 {
	if x != nil {
		return x.Sociability
	}
	return 0
}

func (x *Competency_Axes) GetTeamwork() int32 {
	if x != nil {
		return x.Teamwork
	}
	return 0
}

func (x *Competency_Axes) GetCreativity() int32 {
	if x != nil {
		return x.Creativity
	}
	return 0
}

func (x *Competency_Axes) GetProblemSolving() int32 {
	if x != nil {
		return x.ProblemSolving
	}
	return 0
}

func (x *Competency_Axes) GetPressureTolerance() int32 {
	if x != nil {
		return x.PressureTolerance
	}
	return 0
}

func (x *Competency_Axes) GetCoordination() int32 {
	if x != nil {
		return x.Coordination
	}
	return 0
}

func (x *Competency_Axes) GetLeadership() int32 {
	if x != nil {
		return x.Leadership
	}
	return 0
}

func (x *Competency_Axes) GetAdaptability() int32 {
	if x != nil {
		return x.Adaptability
	}
	return 0
}

func (x *Competency_Axes) GetPerseverance() int32 {
	if x != nil {
		return x.Perseverance
	}
	return 0
}

func (x *Competency_Axes) GetFocus() int32 {
	if x != nil {
		return x.Focus
	}
	return 0
}

func (x *Competency_Axes) GetPlanning() int32 {
	if x != nil {
		return x.Planning
	}
	return 0
}

func (x *Competency_Axes) GetInterpersonalInfluence() int32 {
	if x != nil {
		return x.InterpersonalInfluence
	}
	return 0
}

func (x *Competency_Axes) GetGoalSetting() int32 {
	if x != nil {
		return x.GoalSetting
	}
	return 0
}

func (x *Competency_Axes) GetDecisiveness() int32 {
	if x != nil {
		return x.Decisiveness
	}
	return 0
}

func (x *Competency_Axes) GetAnalyticalAbility() int32 {
	if x != nil {
		return x.AnalyticalAbility
	}
	return 0
}

func (x *Competency_Axes) GetConceptualization() int32 {
	if x != nil {
		return x.Conceptualization
	}
	return 0
}

func (x *Competency_Axes) GetContinuity() int32 {
	if x != nil {
		return x.Continuity
	}
	return 0
}

func (x *Competency_Axes) GetRelationshipBuilding() int32 {
	if x != nil {
		return x.RelationshipBuilding
	}
	return 0
}

func (x *Competency_Axes) GetEmpathy() int32 {
	if x != nil {
		return x.Empathy
	}
	return 0
}

func (x *Competency_Axes) GetSelfLearning() int32 {
	if x != nil {
		return x.SelfLearning
	}
	return 0
}

func (x *Competency_Axes) GetDirective() int32 {
	if x != nil {
		return x.Directive
	}
	return 0
}

func (x *Competency_Axes) GetDelegation() int32 {
	if x != nil {
		return x.Delegation
	}
	return 0
}

func (x *Competency_Axes) GetListening() int32 {
	if x != nil {
		return x.Listening
	}
	return 0
}

func (x *Competency_Axes) GetDialogue() int32 {
	if x != nil {
		return x.Dialogue
	}
	return 0
}

func (x *Competency_Axes) GetNegotiation() int32 {
	if x != nil {
		return x.Negotiation
	}
	return 0
}

func (x *Competency_Axes) GetObedient() int32 {
	if x != nil {
		return x.Obedient
	}
	return 0
}

func (x *Competency_Axes) GetAutonomous() int32 {
	if x != nil {
		return x.Autonomous
	}
	return 0
}

func (x *Competency_Axes) GetCooperative() int32 {
	if x != nil {
		return x.Cooperative
	}
	return 0
}

func (x *Competency_Axes) GetProactive() int32 {
	if x != nil {
		return x.Proactive
	}
	return 0
}

func (x *Competency_Axes) GetAssertive() int32 {
	if x != nil {
		return x.Assertive
	}
	return 0
}

func (x *Competency_Axes) GetUncertainSituations() int32 {
	if x != nil {
		return x.UncertainSituations
	}
	return 0
}

func (x *Competency_Axes) GetResponseToSuddenChanges() int32 {
	if x != nil {
		return x.ResponseToSuddenChanges
	}
	return 0
}

func (x *Competency_Axes) GetHardWork() int32 {
	if x != nil {
		return x.HardWork
	}
	return 0
}

func (x *Competency_Axes) GetLackOfPlanning() int32 {
	if x != nil {
		return x.LackOfPlanning
	}
	return 0
}

func (x *Competency_Axes) GetStrictManagement() int32 {
	if x != nil {
		return x.StrictManagement
	}
	return 0
}

func (x *Competency_Axes) GetLackOfEvaluation() int32 {
	if x != nil {
		return x.LackOfEvaluation
	}
	return 0
}

func (x *Competency_Axes) GetInabilityToExerciseInitiative() int32 {
	if x != nil {
		return x.InabilityToExerciseInitiative
	}
	return 0
}

func (x *Competency_Axes) GetExclusionFromDecisionMaking() int32 {
	if x != nil {
		return x.ExclusionFromDecisionMaking
	}
	return 0
}

func (x *Competency_Axes) GetLowStandards() int32 {
	if x != nil {
		return x.LowStandards
	}
	return 0
}

func (x *Competency_Axes) GetHighAnalysis() int32 {
	if x != nil {
		return x.HighAnalysis
	}
	return 0
}

func (x *Competency_Axes) GetLackOfLearningOpportunities() int32 {
	if x != nil {
		return x.LackOfLearningOpportunities
	}
	return 0
}

func (x *Competency_Axes) GetFollowingPrecedents() int32 {
	if x != nil {
		return x.FollowingPrecedents
	}
	return 0
}

func (x *Competency_Axes) GetRoutineWork() int32 {
	if x != nil {
		return x.RoutineWork
	}
	return 0
}

func (x *Competency_Axes) GetDifficultDecisions() int32 {
	if x != nil {
		return x.DifficultDecisions
	}
	return 0
}

func (x *Competency_Axes) GetNegotiationTasks() int32 {
	if x != nil {
		return x.NegotiationTasks
	}
	return 0
}

func (x *Competency_Axes) GetConsensusBuilding() int32 {
	if x != nil {
		return x.ConsensusBuilding
	}
	return 0
}

func (x *Competency_Axes) GetConflictWithOthers() int32 {
	if x != nil {
		return x.ConflictWithOthers
	}
	return 0
}

func (x *Competency_Axes) GetDryWorkplace() int32 {
	if x != nil {
		return x.DryWorkplace
	}
	return 0
}

func (x *Competency_Axes) GetCaughtInTheMiddle() int32 {
	if x != nil {
		return x.CaughtInTheMiddle
	}
	return 0
}

func (x *Competency_Axes) GetCollaborativeWork() int32 {
	if x != nil {
		return x.CollaborativeWork
	}
	return 0
}

var File_user_profile_proto protoreflect.FileDescriptor

const file_user_profile_proto_rawDesc = "" +
	"\n" +
	"\x12user/profile.proto\x12\x1cmiidas.user.marketvalue.user\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\v\n" +
	"\aProfile\x12\x1e\n" +
	"\auser_id\x18\x01 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x06userId\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x05R\x03age\x12#\n" +
	"\rannual_income\x18\x03 \x01(\x05R\fannualIncome\x12F\n" +
	"\bgraduate\x18\x04 \x01(\v2*.miidas.user.marketvalue.user.GraduateInfoR\bgraduate\x127\n" +
	"\x03job\x18\x05 \x01(\v2%.miidas.user.marketvalue.user.JobInfoR\x03job\x12J\n" +
	"\vexperiences\x18\x06 \x03(\v2(.miidas.user.marketvalue.user.ExperienceR\vexperiences\x12:\n" +
	"\x04lang\x18\a \x01(\v2&.miidas.user.marketvalue.user.LangInfoR\x04lang\x123\n" +
	"\x16office_excel_skill_ids\x18\b \x03(\x05R\x13officeExcelSkillIds\x125\n" +
	"\x17office_access_skill_ids\x18\t \x03(\x05R\x14officeAccessSkillIds\x12(\n" +
	"\x10company_name_ids\x18\n" +
	" \x03(\x05R\x0ecompanyNameIds\x12\x1f\n" +
	"\vlicence_ids\x18\v \x03(\x05R\n" +
	"licenceIds\x12R\n" +
	"\x0edriver_licence\x18\f \x01(\v2+.miidas.user.marketvalue.user.DriverLicenceR\rdriverLicence\x12\x1d\n" +
	"\n" +
	"has_resume\x18\r \x01(\bR\thasResume\x12#\n" +
	"\rhas_portfolio\x18\x0e \x01(\bR\fhasPortfolio\x12#\n" +
	"\rworked_abroad\x18\x0f \x01(\bR\fworkedAbroad\x12<\n" +
	"\x06Resume\x18\x10 \x01(\v2$.miidas.user.marketvalue.user.ResumeR\x06Resume\x12H\n" +
	"\n" +
	"Competency\x18\x11 \x01(\v2(.miidas.user.marketvalue.user.CompetencyR\n" +
	"Competency\x126\n" +
	"\x04Bias\x18\x12 \x01(\v2\".miidas.user.marketvalue.user.BiasR\x04Bias\x12#\n" +
	"\rprefecture_id\x18\x13 \x01(\x05R\fprefectureId\x125\n" +
	"\x17block_all_companies_flg\x18\x14 \x01(\bR\x14blockAllCompaniesFlg\x12/\n" +
	"\x14hp_apply_company_ids\x18\x15 \x03(\x05R\x11hpApplyCompanyIds\x12?\n" +
	"\rregistered_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x12^\n" +
	"\x12outsourcing_search\x18\x18 \x01(\v2/.miidas.user.marketvalue.user.OutsourcingSearchR\x11outsourcingSearch\x12}\n" +
	"!all_career_job_type_and_exp_terms\x18\x19 \x03(\v25.miidas.user.marketvalue.user.AllCareerJobTypeExpTermR\x1ballCareerJobTypeAndExpTerms\x12\x17\n" +
	"\acity_id\x18\x1a \x01(\x05R\x06cityId\x12\"\n" +
	"\tgender_id\x18\x1b \x01(\x05B\x05\xaa\x01\x02\b\x01R\bgenderId\"I\n" +
	"\rDriverLicence\x12\x1f\n" +
	"\vhas_licence\x18\x01 \x01(\bR\n" +
	"hasLicence\x12\x17\n" +
	"\ais_full\x18\x02 \x01(\bR\x06isFull\"\xf8\x01\n" +
	"\fGraduateInfo\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vschool_type\x18\x02 \x01(\x05R\n" +
	"schoolType\x12\x1f\n" +
	"\vschool_rank\x18\x03 \x01(\x05R\n" +
	"schoolRank\x12\x1b\n" +
	"\tschool_id\x18\x04 \x01(\x05R\bschoolId\x12\x1b\n" +
	"\tdepart_id\x18\x05 \x01(\x05R\bdepartId\x12X\n" +
	")professional_training_college_category_id\x18\x06 \x01(\x05R%professionalTrainingCollegeCategoryId\"\xef\x01\n" +
	"\aJobInfo\x12:\n" +
	"\x16management_exp_term_id\x18\x01 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x13managementExpTermId\x127\n" +
	"\x18management_people_qty_id\x18\x02 \x01(\x05R\x15managementPeopleQtyId\x12$\n" +
	"\x0eexp_company_id\x18\x03 \x01(\x05R\fexpCompanyId\x12!\n" +
	"\fretire_month\x18\x04 \x01(\x05R\vretireMonth\x12&\n" +
	"\x0fcompany_name_id\x18\x05 \x01(\x05R\rcompanyNameId\"\xe5\x06\n" +
	"\n" +
	"Experience\x12&\n" +
	"\x0fuser_company_id\x18\x01 \x01(\x05R\ruserCompanyId\x12&\n" +
	"\x0fcompany_name_id\x18\x02 \x01(\x05R\rcompanyNameId\x12&\n" +
	"\x0femployee_qty_id\x18\x03 \x01(\x05R\remployeeQtyId\x12,\n" +
	"\x12employment_type_id\x18\x04 \x01(\x05R\x10employmentTypeId\x121\n" +
	"\x11industry_small_id\x18\x05 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x0findustrySmallId\x12\x1b\n" +
	"\tis_recent\x18\x06 \x01(\bR\bisRecent\x12\x1f\n" +
	"\vretire_year\x18\a \x01(\x05R\n" +
	"retireYear\x12!\n" +
	"\fretire_month\x18\b \x01(\x05R\vretireMonth\x12T\n" +
	"\tjob_types\x18\t \x03(\v27.miidas.user.marketvalue.user.Experience.JobTypeExpTermR\bjobTypes\x12T\n" +
	"\x06skills\x18\n" +
	" \x03(\v2<.miidas.user.marketvalue.user.Experience.JobTypeSkillExpTermR\x06skills\x12\x1b\n" +
	"\tjoin_year\x18\v \x01(\x05R\bjoinYear\x12\x1d\n" +
	"\n" +
	"join_month\x18\f \x01(\x05R\tjoinMonth\x1a\x81\x01\n" +
	"\x0eJobTypeExpTerm\x12)\n" +
	"\x11job_type_small_id\x18\x01 \x01(\x05R\x0ejobTypeSmallId\x12%\n" +
	"\vexp_term_id\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\texpTermId\x12\x1d\n" +
	"\n" +
	"is_special\x18\x03 \x01(\bR\tisSpecial\x1a\xb0\x01\n" +
	"\x13JobTypeSkillExpTerm\x12\x1e\n" +
	"\vjob_type_id\x18\x01 \x01(\x05R\tjobTypeId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\x05R\askillId\x12\x1e\n" +
	"\vexp_term_id\x18\x03 \x01(\x05R\texpTermId\x12\x1f\n" +
	"\vinput_skill\x18\x04 \x01(\tR\n" +
	"inputSkill\x12\x1d\n" +
	"\n" +
	"is_special\x18\x05 \x01(\bR\tisSpecial\"\xc2\x01\n" +
	"\bLangInfo\x12\x1b\n" +
	"\teng_level\x18\x01 \x01(\x05R\bengLevel\x12\x1b\n" +
	"\teng_toeic\x18\x02 \x01(\x05R\bengToeic\x12\x1d\n" +
	"\n" +
	"eng_toefli\x18\x03 \x01(\x05R\tengToefli\x12\x1d\n" +
	"\n" +
	"eng_toeflp\x18\x04 \x01(\x05R\tengToeflp\x12\x1b\n" +
	"\tother_ids\x18\x05 \x03(\x05R\botherIds\x12!\n" +
	"\fother_levels\x18\x06 \x03(\x05R\votherLevels\"P\n" +
	"\x06Resume\x12\"\n" +
	"\fFileContents\x18\x01 \x01(\tR\fFileContents\x12\"\n" +
	"\fTextContents\x18\x02 \x01(\tR\fTextContents\"k\n" +
	"\x17AllCareerJobTypeExpTerm\x12)\n" +
	"\x11job_type_small_id\x18\x01 \x01(\x05R\x0ejobTypeSmallId\x12%\n" +
	"\vexp_term_id\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\texpTermId\"\x99\x11\n" +
	"\n" +
	"Competency\x12\x16\n" +
	"\x06vanity\x18\x01 \x01(\x05R\x06vanity\x12A\n" +
	"\x04axes\x18\x02 \x01(\v2-.miidas.user.marketvalue.user.Competency.AxesR\x04axes\x1a\xaf\x10\n" +
	"\x04Axes\x12)\n" +
	"\x10management_style\x18\x01 \x01(\x05R\x0fmanagementStyle\x12\x1a\n" +
	"\bvitality\x18\x02 \x01(\x05R\bvitality\x12 \n" +
	"\vsociability\x18\x03 \x01(\x05R\vsociability\x12\x1a\n" +
	"\bteamwork\x18\x04 \x01(\x05R\bteamwork\x12\x1e\n" +
	"\n" +
	"creativity\x18\x05 \x01(\x05R\n" +
	"creativity\x12'\n" +
	"\x0fproblem_solving\x18\x06 \x01(\x05R\x0eproblemSolving\x12-\n" +
	"\x12pressure_tolerance\x18\a \x01(\x05R\x11pressureTolerance\x12\"\n" +
	"\fcoordination\x18\b \x01(\x05R\fcoordination\x12\x1e\n" +
	"\n" +
	"leadership\x18\t \x01(\x05R\n" +
	"leadership\x12\"\n" +
	"\fadaptability\x18\n" +
	" \x01(\x05R\fadaptability\x12\"\n" +
	"\fperseverance\x18\v \x01(\x05R\fperseverance\x12\x14\n" +
	"\x05focus\x18\f \x01(\x05R\x05focus\x12\x1a\n" +
	"\bplanning\x18\r \x01(\x05R\bplanning\x127\n" +
	"\x17interpersonal_influence\x18\x0e \x01(\x05R\x16interpersonalInfluence\x12!\n" +
	"\fgoal_setting\x18\x0f \x01(\x05R\vgoalSetting\x12\"\n" +
	"\fdecisiveness\x18\x10 \x01(\x05R\fdecisiveness\x12-\n" +
	"\x12analytical_ability\x18\x11 \x01(\x05R\x11analyticalAbility\x12,\n" +
	"\x11conceptualization\x18\x12 \x01(\x05R\x11conceptualization\x12\x1e\n" +
	"\n" +
	"continuity\x18\x13 \x01(\x05R\n" +
	"continuity\x123\n" +
	"\x15relationship_building\x18\x14 \x01(\x05R\x14relationshipBuilding\x12\x18\n" +
	"\aempathy\x18\x15 \x01(\x05R\aempathy\x12#\n" +
	"\rself_learning\x18\x16 \x01(\x05R\fselfLearning\x12\x1c\n" +
	"\tdirective\x18\x17 \x01(\x05R\tdirective\x12\x1e\n" +
	"\n" +
	"delegation\x18\x18 \x01(\x05R\n" +
	"delegation\x12\x1c\n" +
	"\tlistening\x18\x19 \x01(\x05R\tlistening\x12\x1a\n" +
	"\bdialogue\x18\x1a \x01(\x05R\bdialogue\x12 \n" +
	"\vnegotiation\x18\x1b \x01(\x05R\vnegotiation\x12\x1a\n" +
	"\bobedient\x18\x1c \x01(\x05R\bobedient\x12\x1e\n" +
	"\n" +
	"autonomous\x18\x1d \x01(\x05R\n" +
	"autonomous\x12 \n" +
	"\vcooperative\x18\x1e \x01(\x05R\vcooperative\x12\x1c\n" +
	"\tproactive\x18\x1f \x01(\x05R\tproactive\x12\x1c\n" +
	"\tassertive\x18  \x01(\x05R\tassertive\x121\n" +
	"\x14uncertain_situations\x18! \x01(\x05R\x13uncertainSituations\x12;\n" +
	"\x1aresponse_to_sudden_changes\x18\" \x01(\x05R\x17responseToSuddenChanges\x12\x1b\n" +
	"\thard_work\x18# \x01(\x05R\bhardWork\x12(\n" +
	"\x10lack_of_planning\x18$ \x01(\x05R\x0elackOfPlanning\x12+\n" +
	"\x11strict_management\x18% \x01(\x05R\x10strictManagement\x12,\n" +
	"\x12lack_of_evaluation\x18& \x01(\x05R\x10lackOfEvaluation\x12G\n" +
	" inability_to_exercise_initiative\x18' \x01(\x05R\x1dinabilityToExerciseInitiative\x12C\n" +
	"\x1eexclusion_from_decision_making\x18( \x01(\x05R\x1bexclusionFromDecisionMaking\x12#\n" +
	"\rlow_standards\x18) \x01(\x05R\flowStandards\x12#\n" +
	"\rhigh_analysis\x18* \x01(\x05R\fhighAnalysis\x12C\n" +
	"\x1elack_of_learning_opportunities\x18+ \x01(\x05R\x1blackOfLearningOpportunities\x121\n" +
	"\x14following_precedents\x18, \x01(\x05R\x13followingPrecedents\x12!\n" +
	"\froutine_work\x18- \x01(\x05R\vroutineWork\x12/\n" +
	"\x13difficult_decisions\x18. \x01(\x05R\x12difficultDecisions\x12+\n" +
	"\x11negotiation_tasks\x18/ \x01(\x05R\x10negotiationTasks\x12-\n" +
	"\x12consensus_building\x180 \x01(\x05R\x11consensusBuilding\x120\n" +
	"\x14conflict_with_others\x181 \x01(\x05R\x12conflictWithOthers\x12#\n" +
	"\rdry_workplace\x182 \x01(\x05R\fdryWorkplace\x12/\n" +
	"\x14caught_in_the_middle\x183 \x01(\x05R\x11caughtInTheMiddle\x12-\n" +
	"\x12collaborative_work\x184 \x01(\x05R\x11collaborativeWork\"\xd2\x06\n" +
	"\x04Bias\x12\x1e\n" +
	"\n" +
	"conformity\x18\x01 \x01(\x05R\n" +
	"conformity\x12'\n" +
	"\x0fimpulse_control\x18\x02 \x01(\x05R\x0eimpulseControl\x12%\n" +
	"\x0eframing_effect\x18\x03 \x01(\x05R\rframingEffect\x12+\n" +
	"\x11focused_attention\x18\x04 \x01(\x05R\x10focusedAttention\x12+\n" +
	"\x11divided_attention\x18\x05 \x01(\x05R\x10dividedAttention\x12+\n" +
	"\x11negative_emotions\x18\x06 \x01(\x05R\x10negativeEmotions\x12\x1b\n" +
	"\tsunk_cost\x18\a \x01(\x05R\bsunkCost\x12\x1e\n" +
	"\n" +
	"impatience\x18\b \x01(\x05R\n" +
	"impatience\x12>\n" +
	"\x1bdecline_evaluation_aversion\x18\t \x01(\x05R\x19declineEvaluationAversion\x12#\n" +
	"\rloss_aversion\x18\n" +
	" \x01(\x05R\flossAversion\x12'\n" +
	"\x0feffort_aversion\x18\v \x01(\x05R\x0eeffortAversion\x12'\n" +
	"\x0fregret_aversion\x18\f \x01(\x05R\x0eregretAversion\x12!\n" +
	"\frange_others\x18\r \x01(\x05R\vrangeOthers\x12!\n" +
	"\frange_myself\x18\x0e \x01(\x05R\vrangeMyself\x12\x18\n" +
	"\aempathy\x18\x0f \x01(\x05R\aempathy\x12\x1d\n" +
	"\n" +
	"status_quo\x18\x10 \x01(\x05R\tstatusQuo\x12/\n" +
	"\x13predictive_behavior\x18\x11 \x01(\x05R\x12predictiveBehavior\x12!\n" +
	"\fbias_control\x18\x12 \x01(\x05R\vbiasControl\x12F\n" +
	"\x1faltruism_selfishness_evaluation\x18\x13 \x01(\x05R\x1daltruismSelfishnessEvaluation\x12%\n" +
	"\x0erisk_tolerance\x18\x14 \x01(\x05R\rriskTolerance\x12\x1d\n" +
	"\n" +
	"ends_means\x18\x15 \x01(\x05R\tendsMeans\"\xd0\x01\n" +
	"\x11OutsourcingSearch\x12!\n" +
	"\fwork_address\x18\x01 \x03(\x05R\vworkAddress\x12!\n" +
	"\fworking_time\x18\x02 \x03(\x05R\vworkingTime\x12'\n" +
	"\x0fcontract_period\x18\x03 \x03(\x05R\x0econtractPeriod\x12&\n" +
	"\vremote_work\x18\x04 \x01(\x05B\x05\xaa\x01\x02\b\x01R\n" +
	"remoteWork\x12$\n" +
	"\n" +
	"hourly_fee\x18\x05 \x01(\x05B\x05\xaa\x01\x02\b\x01R\thourlyFeeB1Z*miidas/m2/user/marketvalue/grpc/iface/user\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_user_profile_proto_rawDescOnce sync.Once
	file_user_profile_proto_rawDescData []byte
)

func file_user_profile_proto_rawDescGZIP() []byte {
	file_user_profile_proto_rawDescOnce.Do(func() {
		file_user_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_profile_proto_rawDesc), len(file_user_profile_proto_rawDesc)))
	})
	return file_user_profile_proto_rawDescData
}

var file_user_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_profile_proto_goTypes = []any{
	(*Profile)(nil),                        // 0: miidas.user.marketvalue.user.Profile
	(*DriverLicence)(nil),                  // 1: miidas.user.marketvalue.user.DriverLicence
	(*GraduateInfo)(nil),                   // 2: miidas.user.marketvalue.user.GraduateInfo
	(*JobInfo)(nil),                        // 3: miidas.user.marketvalue.user.JobInfo
	(*Experience)(nil),                     // 4: miidas.user.marketvalue.user.Experience
	(*LangInfo)(nil),                       // 5: miidas.user.marketvalue.user.LangInfo
	(*Resume)(nil),                         // 6: miidas.user.marketvalue.user.Resume
	(*AllCareerJobTypeExpTerm)(nil),        // 7: miidas.user.marketvalue.user.AllCareerJobTypeExpTerm
	(*Competency)(nil),                     // 8: miidas.user.marketvalue.user.Competency
	(*Bias)(nil),                           // 9: miidas.user.marketvalue.user.Bias
	(*OutsourcingSearch)(nil),              // 10: miidas.user.marketvalue.user.OutsourcingSearch
	(*Experience_JobTypeExpTerm)(nil),      // 11: miidas.user.marketvalue.user.Experience.JobTypeExpTerm
	(*Experience_JobTypeSkillExpTerm)(nil), // 12: miidas.user.marketvalue.user.Experience.JobTypeSkillExpTerm
	(*Competency_Axes)(nil),                // 13: miidas.user.marketvalue.user.Competency.Axes
	(*timestamppb.Timestamp)(nil),          // 14: google.protobuf.Timestamp
}
var file_user_profile_proto_depIdxs = []int32{
	2,  // 0: miidas.user.marketvalue.user.Profile.graduate:type_name -> miidas.user.marketvalue.user.GraduateInfo
	3,  // 1: miidas.user.marketvalue.user.Profile.job:type_name -> miidas.user.marketvalue.user.JobInfo
	4,  // 2: miidas.user.marketvalue.user.Profile.experiences:type_name -> miidas.user.marketvalue.user.Experience
	5,  // 3: miidas.user.marketvalue.user.Profile.lang:type_name -> miidas.user.marketvalue.user.LangInfo
	1,  // 4: miidas.user.marketvalue.user.Profile.driver_licence:type_name -> miidas.user.marketvalue.user.DriverLicence
	6,  // 5: miidas.user.marketvalue.user.Profile.Resume:type_name -> miidas.user.marketvalue.user.Resume
	8,  // 6: miidas.user.marketvalue.user.Profile.Competency:type_name -> miidas.user.marketvalue.user.Competency
	9,  // 7: miidas.user.marketvalue.user.Profile.Bias:type_name -> miidas.user.marketvalue.user.Bias
	14, // 8: miidas.user.marketvalue.user.Profile.registered_at:type_name -> google.protobuf.Timestamp
	10, // 9: miidas.user.marketvalue.user.Profile.outsourcing_search:type_name -> miidas.user.marketvalue.user.OutsourcingSearch
	7,  // 10: miidas.user.marketvalue.user.Profile.all_career_job_type_and_exp_terms:type_name -> miidas.user.marketvalue.user.AllCareerJobTypeExpTerm
	11, // 11: miidas.user.marketvalue.user.Experience.job_types:type_name -> miidas.user.marketvalue.user.Experience.JobTypeExpTerm
	12, // 12: miidas.user.marketvalue.user.Experience.skills:type_name -> miidas.user.marketvalue.user.Experience.JobTypeSkillExpTerm
	13, // 13: miidas.user.marketvalue.user.Competency.axes:type_name -> miidas.user.marketvalue.user.Competency.Axes
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_user_profile_proto_init() }
func file_user_profile_proto_init() {
	if File_user_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_profile_proto_rawDesc), len(file_user_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_profile_proto_goTypes,
		DependencyIndexes: file_user_profile_proto_depIdxs,
		MessageInfos:      file_user_profile_proto_msgTypes,
	}.Build()
	File_user_profile_proto = out.File
	file_user_profile_proto_goTypes = nil
	file_user_profile_proto_depIdxs = nil
}
