// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: user/will_business.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusinessWill struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Industry 業種
	Industry *Industry `protobuf:"bytes,1,opt,name=Industry" json:"Industry,omitempty"`
	// DecisionType 意思決定と裁量
	DecisionType *DecisionType `protobuf:"bytes,2,opt,name=DecisionType" json:"DecisionType,omitempty"`
	// EmployeeCharacter 組織・社員の特徴
	EmployeeCharacter *EmployeeCharacter `protobuf:"bytes,3,opt,name=EmployeeCharacter" json:"EmployeeCharacter,omitempty"`
	// HREvaluationPromotionSpeed 昇給昇格スピード
	HREvaluationPromotionSpeed *HREvaluationPromotionSpeed `protobuf:"bytes,4,opt,name=HREvaluationPromotionSpeed" json:"HREvaluationPromotionSpeed,omitempty"`
	// EmployeeAverageAge 平均年齢
	EmployeeAverageAge *EmployeeAverageAge `protobuf:"bytes,5,opt,name=EmployeeAverageAge" json:"EmployeeAverageAge,omitempty"`
	// EmployeeMidCareerRate 中途入社社員比率
	EmployeeMidCareerRate *EmployeeMidCareerRate `protobuf:"bytes,6,opt,name=EmployeeMidCareerRate" json:"EmployeeMidCareerRate,omitempty"`
	// EmployeeWomanRate 女性社員比率
	EmployeeWomanRate *EmployeeWomanRate `protobuf:"bytes,7,opt,name=EmployeeWomanRate" json:"EmployeeWomanRate,omitempty"`
	// EmployeeForeignNationalityRate 外国籍社員比率
	EmployeeForeignNationalityRate *EmployeeForeignNationalityRate `protobuf:"bytes,8,opt,name=EmployeeForeignNationalityRate" json:"EmployeeForeignNationalityRate,omitempty"`
	// ForeignNationalityRecruiting 外国籍社員積極採用
	ForeignNationalityRecruiting *ForeignNationalityRecruiting `protobuf:"bytes,9,opt,name=ForeignNationalityRecruiting" json:"ForeignNationalityRecruiting,omitempty"`
	// BusinessEmployeeQty 事業の従業員数
	EmployeeQty *BusinessEmployeeQty `protobuf:"bytes,10,opt,name=EmployeeQty" json:"EmployeeQty,omitempty"`
	// BusinessEstablishmentYear 事業の設立
	EstablishmentYear *BusinessEstablishmentYear `protobuf:"bytes,11,opt,name=EstablishmentYear" json:"EstablishmentYear,omitempty"`
	// BusinessSalesScale 事業の売上規模
	SalesScale *BusinessSalesScale `protobuf:"bytes,12,opt,name=SalesScale" json:"SalesScale,omitempty"`
	// Stage 事業ステージ
	Stage *Stage `protobuf:"bytes,13,opt,name=Stage" json:"Stage,omitempty"`
	// ProductsShare 業界シェア
	ProductsShare *ProductsShare `protobuf:"bytes,14,opt,name=ProductsShare" json:"ProductsShare,omitempty"`
	// HasOwnProducts 自社商材・サービス
	HasOwnProducts *HasOwnProducts `protobuf:"bytes,15,opt,name=HasOwnProducts" json:"HasOwnProducts,omitempty"`
	// ProductsTangibleness 商材
	ProductsTangibleness *ProductsTangibleness `protobuf:"bytes,16,opt,name=ProductsTangibleness" json:"ProductsTangibleness,omitempty"`
	// TargetCustomer 対象顧客s
	TargetCustomer *TargetCustomer `protobuf:"bytes,17,opt,name=TargetCustomer" json:"TargetCustomer,omitempty"`
	// TargetCustomerBtoB [BtoB] 主な顧客の業界
	TargetCustomerBtoB *TargetCustomerBtoB `protobuf:"bytes,18,opt,name=TargetCustomerBtoB" json:"TargetCustomerBtoB,omitempty"`
	// TargetCustomerBtoC [BtoC] 主な顧客の属性
	TargetCustomerBtoC *TargetCustomerBtoC `protobuf:"bytes,19,opt,name=TargetCustomerBtoC" json:"TargetCustomerBtoC,omitempty"`
	// TrendKeyword トレンドキーワード
	TrendKeyword *TrendKeyword `protobuf:"bytes,20,opt,name=TrendKeyword" json:"TrendKeyword,omitempty"`
	// MarketProspect マーケット
	MarketProspect *MarketProspect `protobuf:"bytes,21,opt,name=MarketProspect" json:"MarketProspect,omitempty"`
	// Strategy 戦略
	Strategy *Strategy `protobuf:"bytes,22,opt,name=Strategy" json:"Strategy,omitempty"`
	// Advantage 事業の強み
	Advantage *Advantage `protobuf:"bytes,23,opt,name=Advantage" json:"Advantage,omitempty"`
	// MedicalAdvantageField メディカル系のこだわり条件 > 得意領域
	MedicalAdvantageField *MedicalAdvantageField `protobuf:"bytes,24,opt,name=MedicalAdvantageField" json:"MedicalAdvantageField,omitempty"`
	// SIType システムインテグレーターのこだわり条件 > SI種別
	SIType *SIType `protobuf:"bytes,25,opt,name=SIType" json:"SIType,omitempty"`
	// SIAdvantageIndustry システムインテグレーターのこだわり条件 > 得意領域
	SIAdvantageIndustry *SIAdvantageIndustry `protobuf:"bytes,26,opt,name=SIAdvantageIndustry" json:"SIAdvantageIndustry,omitempty"`
	// CarPartsTier メーカー（自動車部品）のこだわり条件 > Tier
	CarPartsTier *CarPartsTier `protobuf:"bytes,27,opt,name=CarPartsTier" json:"CarPartsTier,omitempty"`
	// ContractCompanyProfitSource 請負会社のこだわり条件 > 主な収益源
	ContractCompanyProfitSource *ContractCompanyProfitSource `protobuf:"bytes,28,opt,name=ContractCompanyProfitSource" json:"ContractCompanyProfitSource,omitempty"`
	// ContractCompanyProjectTerm 請負会社のこだわり条件 > プロジェクト期間
	ContractCompanyProjectTerm *ContractCompanyProjectTerm `protobuf:"bytes,29,opt,name=ContractCompanyProjectTerm" json:"ContractCompanyProjectTerm,omitempty"`
	// ContractCompanyClientResident 請負会社のこだわり条件 > 客先常駐
	ContractCompanyClientResident *ContractCompanyClientResident `protobuf:"bytes,30,opt,name=ContractCompanyClientResident" json:"ContractCompanyClientResident,omitempty"`
	// ContractCompanyResident 請負会社のこだわり条件 > 常駐携帯
	ContractCompanyResident *ContractCompanyResident `protobuf:"bytes,31,opt,name=ContractCompanyResident" json:"ContractCompanyResident,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BusinessWill) Reset() {
	*x = BusinessWill{}
	mi := &file_user_will_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessWill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessWill) ProtoMessage() {}

func (x *BusinessWill) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessWill.ProtoReflect.Descriptor instead.
func (*BusinessWill) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessWill) GetIndustry() *Industry {
	if x != nil {
		return x.Industry
	}
	return nil
}

func (x *BusinessWill) GetDecisionType() *DecisionType {
	if x != nil {
		return x.DecisionType
	}
	return nil
}

func (x *BusinessWill) GetEmployeeCharacter() *EmployeeCharacter {
	if x != nil {
		return x.EmployeeCharacter
	}
	return nil
}

func (x *BusinessWill) GetHREvaluationPromotionSpeed() *HREvaluationPromotionSpeed {
	if x != nil {
		return x.HREvaluationPromotionSpeed
	}
	return nil
}

func (x *BusinessWill) GetEmployeeAverageAge() *EmployeeAverageAge {
	if x != nil {
		return x.EmployeeAverageAge
	}
	return nil
}

func (x *BusinessWill) GetEmployeeMidCareerRate() *EmployeeMidCareerRate {
	if x != nil {
		return x.EmployeeMidCareerRate
	}
	return nil
}

func (x *BusinessWill) GetEmployeeWomanRate() *EmployeeWomanRate {
	if x != nil {
		return x.EmployeeWomanRate
	}
	return nil
}

func (x *BusinessWill) GetEmployeeForeignNationalityRate() *EmployeeForeignNationalityRate {
	if x != nil {
		return x.EmployeeForeignNationalityRate
	}
	return nil
}

func (x *BusinessWill) GetForeignNationalityRecruiting() *ForeignNationalityRecruiting {
	if x != nil {
		return x.ForeignNationalityRecruiting
	}
	return nil
}

func (x *BusinessWill) GetEmployeeQty() *BusinessEmployeeQty {
	if x != nil {
		return x.EmployeeQty
	}
	return nil
}

func (x *BusinessWill) GetEstablishmentYear() *BusinessEstablishmentYear {
	if x != nil {
		return x.EstablishmentYear
	}
	return nil
}

func (x *BusinessWill) GetSalesScale() *BusinessSalesScale {
	if x != nil {
		return x.SalesScale
	}
	return nil
}

func (x *BusinessWill) GetStage() *Stage {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *BusinessWill) GetProductsShare() *ProductsShare {
	if x != nil {
		return x.ProductsShare
	}
	return nil
}

func (x *BusinessWill) GetHasOwnProducts() *HasOwnProducts {
	if x != nil {
		return x.HasOwnProducts
	}
	return nil
}

func (x *BusinessWill) GetProductsTangibleness() *ProductsTangibleness {
	if x != nil {
		return x.ProductsTangibleness
	}
	return nil
}

func (x *BusinessWill) GetTargetCustomer() *TargetCustomer {
	if x != nil {
		return x.TargetCustomer
	}
	return nil
}

func (x *BusinessWill) GetTargetCustomerBtoB() *TargetCustomerBtoB {
	if x != nil {
		return x.TargetCustomerBtoB
	}
	return nil
}

func (x *BusinessWill) GetTargetCustomerBtoC() *TargetCustomerBtoC {
	if x != nil {
		return x.TargetCustomerBtoC
	}
	return nil
}

func (x *BusinessWill) GetTrendKeyword() *TrendKeyword {
	if x != nil {
		return x.TrendKeyword
	}
	return nil
}

func (x *BusinessWill) GetMarketProspect() *MarketProspect {
	if x != nil {
		return x.MarketProspect
	}
	return nil
}

func (x *BusinessWill) GetStrategy() *Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *BusinessWill) GetAdvantage() *Advantage {
	if x != nil {
		return x.Advantage
	}
	return nil
}

func (x *BusinessWill) GetMedicalAdvantageField() *MedicalAdvantageField {
	if x != nil {
		return x.MedicalAdvantageField
	}
	return nil
}

func (x *BusinessWill) GetSIType() *SIType {
	if x != nil {
		return x.SIType
	}
	return nil
}

func (x *BusinessWill) GetSIAdvantageIndustry() *SIAdvantageIndustry {
	if x != nil {
		return x.SIAdvantageIndustry
	}
	return nil
}

func (x *BusinessWill) GetCarPartsTier() *CarPartsTier {
	if x != nil {
		return x.CarPartsTier
	}
	return nil
}

func (x *BusinessWill) GetContractCompanyProfitSource() *ContractCompanyProfitSource {
	if x != nil {
		return x.ContractCompanyProfitSource
	}
	return nil
}

func (x *BusinessWill) GetContractCompanyProjectTerm() *ContractCompanyProjectTerm {
	if x != nil {
		return x.ContractCompanyProjectTerm
	}
	return nil
}

func (x *BusinessWill) GetContractCompanyClientResident() *ContractCompanyClientResident {
	if x != nil {
		return x.ContractCompanyClientResident
	}
	return nil
}

func (x *BusinessWill) GetContractCompanyResident() *ContractCompanyResident {
	if x != nil {
		return x.ContractCompanyResident
	}
	return nil
}

type Industry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	MainOnly      bool                   `protobuf:"varint,2,opt,name=main_only,json=mainOnly" json:"main_only,omitempty"`
	Exclude       bool                   `protobuf:"varint,3,opt,name=exclude" json:"exclude,omitempty"`
	Value         *IndustryValue         `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Industry) Reset() {
	*x = Industry{}
	mi := &file_user_will_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Industry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Industry) ProtoMessage() {}

func (x *Industry) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Industry.ProtoReflect.Descriptor instead.
func (*Industry) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{1}
}

func (x *Industry) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Industry) GetMainOnly() bool {
	if x != nil {
		return x.MainOnly
	}
	return false
}

func (x *Industry) GetExclude() bool {
	if x != nil {
		return x.Exclude
	}
	return false
}

func (x *Industry) GetValue() *IndustryValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type IndustryValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Larges        []int32                `protobuf:"varint,1,rep,packed,name=larges" json:"larges,omitempty"`
	Middle        []int32                `protobuf:"varint,2,rep,packed,name=middle" json:"middle,omitempty"`
	Small         []int32                `protobuf:"varint,3,rep,packed,name=small" json:"small,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndustryValue) Reset() {
	*x = IndustryValue{}
	mi := &file_user_will_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndustryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndustryValue) ProtoMessage() {}

func (x *IndustryValue) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndustryValue.ProtoReflect.Descriptor instead.
func (*IndustryValue) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{2}
}

func (x *IndustryValue) GetLarges() []int32 {
	if x != nil {
		return x.Larges
	}
	return nil
}

func (x *IndustryValue) GetMiddle() []int32 {
	if x != nil {
		return x.Middle
	}
	return nil
}

func (x *IndustryValue) GetSmall() []int32 {
	if x != nil {
		return x.Small
	}
	return nil
}

type DecisionType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *DecisionTypeValue     `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionType) Reset() {
	*x = DecisionType{}
	mi := &file_user_will_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionType) ProtoMessage() {}

func (x *DecisionType) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionType.ProtoReflect.Descriptor instead.
func (*DecisionType) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{3}
}

func (x *DecisionType) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *DecisionType) GetValue() *DecisionTypeValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type DecisionTypeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1:トップダウン型, 2:ボトムアップ型
	DecisionType *int32 `protobuf:"varint,1,opt,name=decision_type,json=decisionType" json:"decision_type,omitempty"`
	// 1:論理・規則に従う, 2:感情・調和に従う
	LogicOrEmotion *int32 `protobuf:"varint,2,opt,name=logic_or_emotion,json=logicOrEmotion" json:"logic_or_emotion,omitempty"`
	// 1:中央集権型, 2:現場重視型
	Authority *int32 `protobuf:"varint,3,opt,name=authority" json:"authority,omitempty"`
	// 1:仕事の進め方にルールがある, 2:自分のやり方で進められる
	WorkProcedures *int32 `protobuf:"varint,4,opt,name=work_procedures,json=workProcedures" json:"work_procedures,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DecisionTypeValue) Reset() {
	*x = DecisionTypeValue{}
	mi := &file_user_will_business_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionTypeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionTypeValue) ProtoMessage() {}

func (x *DecisionTypeValue) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionTypeValue.ProtoReflect.Descriptor instead.
func (*DecisionTypeValue) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{4}
}

func (x *DecisionTypeValue) GetDecisionType() int32 {
	if x != nil && x.DecisionType != nil {
		return *x.DecisionType
	}
	return 0
}

func (x *DecisionTypeValue) GetLogicOrEmotion() int32 {
	if x != nil && x.LogicOrEmotion != nil {
		return *x.LogicOrEmotion
	}
	return 0
}

func (x *DecisionTypeValue) GetAuthority() int32 {
	if x != nil && x.Authority != nil {
		return *x.Authority
	}
	return 0
}

func (x *DecisionTypeValue) GetWorkProcedures() int32 {
	if x != nil && x.WorkProcedures != nil {
		return *x.WorkProcedures
	}
	return 0
}

type EmployeeCharacter struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Importance    int32                   `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *EmployeeCharacterValue `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeCharacter) Reset() {
	*x = EmployeeCharacter{}
	mi := &file_user_will_business_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeCharacter) ProtoMessage() {}

func (x *EmployeeCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeCharacter.ProtoReflect.Descriptor instead.
func (*EmployeeCharacter) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{5}
}

func (x *EmployeeCharacter) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *EmployeeCharacter) GetValue() *EmployeeCharacterValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type EmployeeCharacterValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1:若手が活躍する, 2:中堅・ベテランが活躍する
	AgeOfActivity *int32 `protobuf:"varint,1,opt,name=AgeOfActivity" json:"AgeOfActivity,omitempty"`
	// 1:挑戦的な社風, 2:堅実な社風
	ChallengeLevelOfCorporateCulture *int32 `protobuf:"varint,2,opt,name=ChallengeLevelOfCorporateCulture" json:"ChallengeLevelOfCorporateCulture,omitempty"`
	// 1:活気がある, 2:落ち着いている
	WorkplaceVibrancy *int32 `protobuf:"varint,3,opt,name=WorkplaceVibrancy" json:"WorkplaceVibrancy,omitempty"`
	// 1:上下関係が明確, 2:上下関係がフラット
	HierarchicalRelationship *int32 `protobuf:"varint,4,opt,name=HierarchicalRelationship" json:"HierarchicalRelationship,omitempty"`
	// 1:ビジネスライク, 2:アットホーム
	WorkplaceAtmosphere *int32 `protobuf:"varint,5,opt,name=WorkplaceAtmosphere" json:"WorkplaceAtmosphere,omitempty"`
	// 1:アナログ組織運営, 2:デジタル組織運営
	OrganizationManagement *int32 `protobuf:"varint,6,opt,name=OrganizationManagement" json:"OrganizationManagement,omitempty"`
	// 1:体育会系, 2:頭脳系
	MilitaryLikeOrBrain *int32 `protobuf:"varint,7,opt,name=MilitaryLikeOrBrain" json:"MilitaryLikeOrBrain,omitempty"`
	// 1:仕事重視, 2:プライベート重視
	WorkOrPersonalLife *int32 `protobuf:"varint,8,opt,name=WorkOrPersonalLife" json:"WorkOrPersonalLife,omitempty"`
	// 1:社内イベントが多い, 2:社内イベントが少ない
	CompanyEvents *int32 `protobuf:"varint,9,opt,name=CompanyEvents" json:"CompanyEvents,omitempty"`
	// 1:上司との飲み会が多い, 2:上司との飲み会が少ない
	DrinkingPartyWithBoss *int32 `protobuf:"varint,10,opt,name=DrinkingPartyWithBoss" json:"DrinkingPartyWithBoss,omitempty"`
	// 1:同僚との飲み会が多い, 2:同僚との飲み会が少ない
	DrinkingPartyWithColleague *int32 `protobuf:"varint,11,opt,name=DrinkingPartyWithColleague" json:"DrinkingPartyWithColleague,omitempty"`
	// 1:企業理念・ビジョンが浸透している, 2:企業理念・ビジョンが浸透していない
	CorporatePhilosophyPenetrance *int32 `protobuf:"varint,12,opt,name=CorporatePhilosophyPenetrance" json:"CorporatePhilosophyPenetrance,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *EmployeeCharacterValue) Reset() {
	*x = EmployeeCharacterValue{}
	mi := &file_user_will_business_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeCharacterValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeCharacterValue) ProtoMessage() {}

func (x *EmployeeCharacterValue) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeCharacterValue.ProtoReflect.Descriptor instead.
func (*EmployeeCharacterValue) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{6}
}

func (x *EmployeeCharacterValue) GetAgeOfActivity() int32 {
	if x != nil && x.AgeOfActivity != nil {
		return *x.AgeOfActivity
	}
	return 0
}

func (x *EmployeeCharacterValue) GetChallengeLevelOfCorporateCulture() int32 {
	if x != nil && x.ChallengeLevelOfCorporateCulture != nil {
		return *x.ChallengeLevelOfCorporateCulture
	}
	return 0
}

func (x *EmployeeCharacterValue) GetWorkplaceVibrancy() int32 {
	if x != nil && x.WorkplaceVibrancy != nil {
		return *x.WorkplaceVibrancy
	}
	return 0
}

func (x *EmployeeCharacterValue) GetHierarchicalRelationship() int32 {
	if x != nil && x.HierarchicalRelationship != nil {
		return *x.HierarchicalRelationship
	}
	return 0
}

func (x *EmployeeCharacterValue) GetWorkplaceAtmosphere() int32 {
	if x != nil && x.WorkplaceAtmosphere != nil {
		return *x.WorkplaceAtmosphere
	}
	return 0
}

func (x *EmployeeCharacterValue) GetOrganizationManagement() int32 {
	if x != nil && x.OrganizationManagement != nil {
		return *x.OrganizationManagement
	}
	return 0
}

func (x *EmployeeCharacterValue) GetMilitaryLikeOrBrain() int32 {
	if x != nil && x.MilitaryLikeOrBrain != nil {
		return *x.MilitaryLikeOrBrain
	}
	return 0
}

func (x *EmployeeCharacterValue) GetWorkOrPersonalLife() int32 {
	if x != nil && x.WorkOrPersonalLife != nil {
		return *x.WorkOrPersonalLife
	}
	return 0
}

func (x *EmployeeCharacterValue) GetCompanyEvents() int32 {
	if x != nil && x.CompanyEvents != nil {
		return *x.CompanyEvents
	}
	return 0
}

func (x *EmployeeCharacterValue) GetDrinkingPartyWithBoss() int32 {
	if x != nil && x.DrinkingPartyWithBoss != nil {
		return *x.DrinkingPartyWithBoss
	}
	return 0
}

func (x *EmployeeCharacterValue) GetDrinkingPartyWithColleague() int32 {
	if x != nil && x.DrinkingPartyWithColleague != nil {
		return *x.DrinkingPartyWithColleague
	}
	return 0
}

func (x *EmployeeCharacterValue) GetCorporatePhilosophyPenetrance() int32 {
	if x != nil && x.CorporatePhilosophyPenetrance != nil {
		return *x.CorporatePhilosophyPenetrance
	}
	return 0
}

type HREvaluationPromotionSpeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HREvaluationPromotionSpeed) Reset() {
	*x = HREvaluationPromotionSpeed{}
	mi := &file_user_will_business_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HREvaluationPromotionSpeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HREvaluationPromotionSpeed) ProtoMessage() {}

func (x *HREvaluationPromotionSpeed) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HREvaluationPromotionSpeed.ProtoReflect.Descriptor instead.
func (*HREvaluationPromotionSpeed) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{7}
}

func (x *HREvaluationPromotionSpeed) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *HREvaluationPromotionSpeed) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type EmployeeAverageAge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeAverageAge) Reset() {
	*x = EmployeeAverageAge{}
	mi := &file_user_will_business_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeAverageAge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeAverageAge) ProtoMessage() {}

func (x *EmployeeAverageAge) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeAverageAge.ProtoReflect.Descriptor instead.
func (*EmployeeAverageAge) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{8}
}

func (x *EmployeeAverageAge) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *EmployeeAverageAge) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type EmployeeMidCareerRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeMidCareerRate) Reset() {
	*x = EmployeeMidCareerRate{}
	mi := &file_user_will_business_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeMidCareerRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeMidCareerRate) ProtoMessage() {}

func (x *EmployeeMidCareerRate) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeMidCareerRate.ProtoReflect.Descriptor instead.
func (*EmployeeMidCareerRate) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{9}
}

func (x *EmployeeMidCareerRate) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *EmployeeMidCareerRate) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type EmployeeWomanRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeWomanRate) Reset() {
	*x = EmployeeWomanRate{}
	mi := &file_user_will_business_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeWomanRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeWomanRate) ProtoMessage() {}

func (x *EmployeeWomanRate) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeWomanRate.ProtoReflect.Descriptor instead.
func (*EmployeeWomanRate) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{10}
}

func (x *EmployeeWomanRate) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *EmployeeWomanRate) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type EmployeeForeignNationalityRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeForeignNationalityRate) Reset() {
	*x = EmployeeForeignNationalityRate{}
	mi := &file_user_will_business_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeForeignNationalityRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeForeignNationalityRate) ProtoMessage() {}

func (x *EmployeeForeignNationalityRate) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeForeignNationalityRate.ProtoReflect.Descriptor instead.
func (*EmployeeForeignNationalityRate) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{11}
}

func (x *EmployeeForeignNationalityRate) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *EmployeeForeignNationalityRate) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type ForeignNationalityRecruiting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForeignNationalityRecruiting) Reset() {
	*x = ForeignNationalityRecruiting{}
	mi := &file_user_will_business_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForeignNationalityRecruiting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignNationalityRecruiting) ProtoMessage() {}

func (x *ForeignNationalityRecruiting) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignNationalityRecruiting.ProtoReflect.Descriptor instead.
func (*ForeignNationalityRecruiting) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{12}
}

func (x *ForeignNationalityRecruiting) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *ForeignNationalityRecruiting) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type BusinessEmployeeQty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessEmployeeQty) Reset() {
	*x = BusinessEmployeeQty{}
	mi := &file_user_will_business_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessEmployeeQty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessEmployeeQty) ProtoMessage() {}

func (x *BusinessEmployeeQty) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessEmployeeQty.ProtoReflect.Descriptor instead.
func (*BusinessEmployeeQty) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{13}
}

func (x *BusinessEmployeeQty) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *BusinessEmployeeQty) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type BusinessEstablishmentYear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessEstablishmentYear) Reset() {
	*x = BusinessEstablishmentYear{}
	mi := &file_user_will_business_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessEstablishmentYear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessEstablishmentYear) ProtoMessage() {}

func (x *BusinessEstablishmentYear) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessEstablishmentYear.ProtoReflect.Descriptor instead.
func (*BusinessEstablishmentYear) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{14}
}

func (x *BusinessEstablishmentYear) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *BusinessEstablishmentYear) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type BusinessSalesScale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessSalesScale) Reset() {
	*x = BusinessSalesScale{}
	mi := &file_user_will_business_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessSalesScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessSalesScale) ProtoMessage() {}

func (x *BusinessSalesScale) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessSalesScale.ProtoReflect.Descriptor instead.
func (*BusinessSalesScale) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{15}
}

func (x *BusinessSalesScale) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *BusinessSalesScale) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_user_will_business_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{16}
}

func (x *Stage) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Stage) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProductsShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsShare) Reset() {
	*x = ProductsShare{}
	mi := &file_user_will_business_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsShare) ProtoMessage() {}

func (x *ProductsShare) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsShare.ProtoReflect.Descriptor instead.
func (*ProductsShare) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{17}
}

func (x *ProductsShare) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *ProductsShare) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type HasOwnProducts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasOwnProducts) Reset() {
	*x = HasOwnProducts{}
	mi := &file_user_will_business_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasOwnProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasOwnProducts) ProtoMessage() {}

func (x *HasOwnProducts) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasOwnProducts.ProtoReflect.Descriptor instead.
func (*HasOwnProducts) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{18}
}

func (x *HasOwnProducts) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *HasOwnProducts) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type ProductsTangibleness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductsTangibleness) Reset() {
	*x = ProductsTangibleness{}
	mi := &file_user_will_business_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductsTangibleness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductsTangibleness) ProtoMessage() {}

func (x *ProductsTangibleness) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductsTangibleness.ProtoReflect.Descriptor instead.
func (*ProductsTangibleness) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{19}
}

func (x *ProductsTangibleness) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *ProductsTangibleness) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type TargetCustomer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetCustomer) Reset() {
	*x = TargetCustomer{}
	mi := &file_user_will_business_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetCustomer) ProtoMessage() {}

func (x *TargetCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetCustomer.ProtoReflect.Descriptor instead.
func (*TargetCustomer) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{20}
}

func (x *TargetCustomer) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *TargetCustomer) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type TargetCustomerBtoB struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Importance    int32                    `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *TargetCustomerBtoBValue `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetCustomerBtoB) Reset() {
	*x = TargetCustomerBtoB{}
	mi := &file_user_will_business_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetCustomerBtoB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetCustomerBtoB) ProtoMessage() {}

func (x *TargetCustomerBtoB) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetCustomerBtoB.ProtoReflect.Descriptor instead.
func (*TargetCustomerBtoB) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{21}
}

func (x *TargetCustomerBtoB) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *TargetCustomerBtoB) GetValue() *TargetCustomerBtoBValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type TargetCustomerBtoBValue struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TargetCustomerLarges  []int32                `protobuf:"varint,1,rep,packed,name=TargetCustomerLarges" json:"TargetCustomerLarges,omitempty"`
	TargetCustomerMiddles []int32                `protobuf:"varint,2,rep,packed,name=TargetCustomerMiddles" json:"TargetCustomerMiddles,omitempty"`
	TargetCustomerSmalls  []int32                `protobuf:"varint,3,rep,packed,name=TargetCustomerSmalls" json:"TargetCustomerSmalls,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TargetCustomerBtoBValue) Reset() {
	*x = TargetCustomerBtoBValue{}
	mi := &file_user_will_business_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetCustomerBtoBValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetCustomerBtoBValue) ProtoMessage() {}

func (x *TargetCustomerBtoBValue) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetCustomerBtoBValue.ProtoReflect.Descriptor instead.
func (*TargetCustomerBtoBValue) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{22}
}

func (x *TargetCustomerBtoBValue) GetTargetCustomerLarges() []int32 {
	if x != nil {
		return x.TargetCustomerLarges
	}
	return nil
}

func (x *TargetCustomerBtoBValue) GetTargetCustomerMiddles() []int32 {
	if x != nil {
		return x.TargetCustomerMiddles
	}
	return nil
}

func (x *TargetCustomerBtoBValue) GetTargetCustomerSmalls() []int32 {
	if x != nil {
		return x.TargetCustomerSmalls
	}
	return nil
}

type TargetCustomerBtoC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetCustomerBtoC) Reset() {
	*x = TargetCustomerBtoC{}
	mi := &file_user_will_business_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetCustomerBtoC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetCustomerBtoC) ProtoMessage() {}

func (x *TargetCustomerBtoC) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetCustomerBtoC.ProtoReflect.Descriptor instead.
func (*TargetCustomerBtoC) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{23}
}

func (x *TargetCustomerBtoC) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *TargetCustomerBtoC) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type TrendKeyword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendKeyword) Reset() {
	*x = TrendKeyword{}
	mi := &file_user_will_business_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendKeyword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendKeyword) ProtoMessage() {}

func (x *TrendKeyword) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendKeyword.ProtoReflect.Descriptor instead.
func (*TrendKeyword) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{24}
}

func (x *TrendKeyword) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *TrendKeyword) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type MarketProspect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketProspect) Reset() {
	*x = MarketProspect{}
	mi := &file_user_will_business_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketProspect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketProspect) ProtoMessage() {}

func (x *MarketProspect) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketProspect.ProtoReflect.Descriptor instead.
func (*MarketProspect) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{25}
}

func (x *MarketProspect) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *MarketProspect) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type Strategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Strategy) Reset() {
	*x = Strategy{}
	mi := &file_user_will_business_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Strategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strategy) ProtoMessage() {}

func (x *Strategy) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strategy.ProtoReflect.Descriptor instead.
func (*Strategy) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{26}
}

func (x *Strategy) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Strategy) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type Advantage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Advantage) Reset() {
	*x = Advantage{}
	mi := &file_user_will_business_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advantage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advantage) ProtoMessage() {}

func (x *Advantage) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advantage.ProtoReflect.Descriptor instead.
func (*Advantage) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{27}
}

func (x *Advantage) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Advantage) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type MedicalAdvantageField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedicalAdvantageField) Reset() {
	*x = MedicalAdvantageField{}
	mi := &file_user_will_business_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedicalAdvantageField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedicalAdvantageField) ProtoMessage() {}

func (x *MedicalAdvantageField) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedicalAdvantageField.ProtoReflect.Descriptor instead.
func (*MedicalAdvantageField) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{28}
}

func (x *MedicalAdvantageField) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *MedicalAdvantageField) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SIType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SIType) Reset() {
	*x = SIType{}
	mi := &file_user_will_business_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SIType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIType) ProtoMessage() {}

func (x *SIType) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIType.ProtoReflect.Descriptor instead.
func (*SIType) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{29}
}

func (x *SIType) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *SIType) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SIAdvantageIndustry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SIAdvantageIndustry) Reset() {
	*x = SIAdvantageIndustry{}
	mi := &file_user_will_business_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SIAdvantageIndustry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIAdvantageIndustry) ProtoMessage() {}

func (x *SIAdvantageIndustry) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIAdvantageIndustry.ProtoReflect.Descriptor instead.
func (*SIAdvantageIndustry) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{30}
}

func (x *SIAdvantageIndustry) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *SIAdvantageIndustry) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type CarPartsTier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarPartsTier) Reset() {
	*x = CarPartsTier{}
	mi := &file_user_will_business_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarPartsTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarPartsTier) ProtoMessage() {}

func (x *CarPartsTier) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarPartsTier.ProtoReflect.Descriptor instead.
func (*CarPartsTier) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{31}
}

func (x *CarPartsTier) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *CarPartsTier) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type ContractCompanyProfitSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractCompanyProfitSource) Reset() {
	*x = ContractCompanyProfitSource{}
	mi := &file_user_will_business_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCompanyProfitSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCompanyProfitSource) ProtoMessage() {}

func (x *ContractCompanyProfitSource) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCompanyProfitSource.ProtoReflect.Descriptor instead.
func (*ContractCompanyProfitSource) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{32}
}

func (x *ContractCompanyProfitSource) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *ContractCompanyProfitSource) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type ContractCompanyProjectTerm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractCompanyProjectTerm) Reset() {
	*x = ContractCompanyProjectTerm{}
	mi := &file_user_will_business_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCompanyProjectTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCompanyProjectTerm) ProtoMessage() {}

func (x *ContractCompanyProjectTerm) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCompanyProjectTerm.ProtoReflect.Descriptor instead.
func (*ContractCompanyProjectTerm) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{33}
}

func (x *ContractCompanyProjectTerm) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *ContractCompanyProjectTerm) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type ContractCompanyClientResident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractCompanyClientResident) Reset() {
	*x = ContractCompanyClientResident{}
	mi := &file_user_will_business_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCompanyClientResident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCompanyClientResident) ProtoMessage() {}

func (x *ContractCompanyClientResident) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCompanyClientResident.ProtoReflect.Descriptor instead.
func (*ContractCompanyClientResident) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{34}
}

func (x *ContractCompanyClientResident) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *ContractCompanyClientResident) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type ContractCompanyResident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractCompanyResident) Reset() {
	*x = ContractCompanyResident{}
	mi := &file_user_will_business_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCompanyResident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCompanyResident) ProtoMessage() {}

func (x *ContractCompanyResident) ProtoReflect() protoreflect.Message {
	mi := &file_user_will_business_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCompanyResident.ProtoReflect.Descriptor instead.
func (*ContractCompanyResident) Descriptor() ([]byte, []int) {
	return file_user_will_business_proto_rawDescGZIP(), []int{35}
}

func (x *ContractCompanyResident) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *ContractCompanyResident) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_user_will_business_proto protoreflect.FileDescriptor

const file_user_will_business_proto_rawDesc = "" +
	"\n" +
	"\x18user/will_business.proto\x12\x1cmiidas.user.marketvalue.user\"\x9d\x17\n" +
	"\fBusinessWill\x12B\n" +
	"\bIndustry\x18\x01 \x01(\v2&.miidas.user.marketvalue.user.IndustryR\bIndustry\x12N\n" +
	"\fDecisionType\x18\x02 \x01(\v2*.miidas.user.marketvalue.user.DecisionTypeR\fDecisionType\x12]\n" +
	"\x11EmployeeCharacter\x18\x03 \x01(\v2/.miidas.user.marketvalue.user.EmployeeCharacterR\x11EmployeeCharacter\x12x\n" +
	"\x1aHREvaluationPromotionSpeed\x18\x04 \x01(\v28.miidas.user.marketvalue.user.HREvaluationPromotionSpeedR\x1aHREvaluationPromotionSpeed\x12`\n" +
	"\x12EmployeeAverageAge\x18\x05 \x01(\v20.miidas.user.marketvalue.user.EmployeeAverageAgeR\x12EmployeeAverageAge\x12i\n" +
	"\x15EmployeeMidCareerRate\x18\x06 \x01(\v23.miidas.user.marketvalue.user.EmployeeMidCareerRateR\x15EmployeeMidCareerRate\x12]\n" +
	"\x11EmployeeWomanRate\x18\a \x01(\v2/.miidas.user.marketvalue.user.EmployeeWomanRateR\x11EmployeeWomanRate\x12\x84\x01\n" +
	"\x1eEmployeeForeignNationalityRate\x18\b \x01(\v2<.miidas.user.marketvalue.user.EmployeeForeignNationalityRateR\x1eEmployeeForeignNationalityRate\x12~\n" +
	"\x1cForeignNationalityRecruiting\x18\t \x01(\v2:.miidas.user.marketvalue.user.ForeignNationalityRecruitingR\x1cForeignNationalityRecruiting\x12S\n" +
	"\vEmployeeQty\x18\n" +
	" \x01(\v21.miidas.user.marketvalue.user.BusinessEmployeeQtyR\vEmployeeQty\x12e\n" +
	"\x11EstablishmentYear\x18\v \x01(\v27.miidas.user.marketvalue.user.BusinessEstablishmentYearR\x11EstablishmentYear\x12P\n" +
	"\n" +
	"SalesScale\x18\f \x01(\v20.miidas.user.marketvalue.user.BusinessSalesScaleR\n" +
	"SalesScale\x129\n" +
	"\x05Stage\x18\r \x01(\v2#.miidas.user.marketvalue.user.StageR\x05Stage\x12Q\n" +
	"\rProductsShare\x18\x0e \x01(\v2+.miidas.user.marketvalue.user.ProductsShareR\rProductsShare\x12T\n" +
	"\x0eHasOwnProducts\x18\x0f \x01(\v2,.miidas.user.marketvalue.user.HasOwnProductsR\x0eHasOwnProducts\x12f\n" +
	"\x14ProductsTangibleness\x18\x10 \x01(\v22.miidas.user.marketvalue.user.ProductsTangiblenessR\x14ProductsTangibleness\x12T\n" +
	"\x0eTargetCustomer\x18\x11 \x01(\v2,.miidas.user.marketvalue.user.TargetCustomerR\x0eTargetCustomer\x12`\n" +
	"\x12TargetCustomerBtoB\x18\x12 \x01(\v20.miidas.user.marketvalue.user.TargetCustomerBtoBR\x12TargetCustomerBtoB\x12`\n" +
	"\x12TargetCustomerBtoC\x18\x13 \x01(\v20.miidas.user.marketvalue.user.TargetCustomerBtoCR\x12TargetCustomerBtoC\x12N\n" +
	"\fTrendKeyword\x18\x14 \x01(\v2*.miidas.user.marketvalue.user.TrendKeywordR\fTrendKeyword\x12T\n" +
	"\x0eMarketProspect\x18\x15 \x01(\v2,.miidas.user.marketvalue.user.MarketProspectR\x0eMarketProspect\x12B\n" +
	"\bStrategy\x18\x16 \x01(\v2&.miidas.user.marketvalue.user.StrategyR\bStrategy\x12E\n" +
	"\tAdvantage\x18\x17 \x01(\v2'.miidas.user.marketvalue.user.AdvantageR\tAdvantage\x12i\n" +
	"\x15MedicalAdvantageField\x18\x18 \x01(\v23.miidas.user.marketvalue.user.MedicalAdvantageFieldR\x15MedicalAdvantageField\x12<\n" +
	"\x06SIType\x18\x19 \x01(\v2$.miidas.user.marketvalue.user.SITypeR\x06SIType\x12c\n" +
	"\x13SIAdvantageIndustry\x18\x1a \x01(\v21.miidas.user.marketvalue.user.SIAdvantageIndustryR\x13SIAdvantageIndustry\x12N\n" +
	"\fCarPartsTier\x18\x1b \x01(\v2*.miidas.user.marketvalue.user.CarPartsTierR\fCarPartsTier\x12{\n" +
	"\x1bContractCompanyProfitSource\x18\x1c \x01(\v29.miidas.user.marketvalue.user.ContractCompanyProfitSourceR\x1bContractCompanyProfitSource\x12x\n" +
	"\x1aContractCompanyProjectTerm\x18\x1d \x01(\v28.miidas.user.marketvalue.user.ContractCompanyProjectTermR\x1aContractCompanyProjectTerm\x12\x81\x01\n" +
	"\x1dContractCompanyClientResident\x18\x1e \x01(\v2;.miidas.user.marketvalue.user.ContractCompanyClientResidentR\x1dContractCompanyClientResident\x12o\n" +
	"\x17ContractCompanyResident\x18\x1f \x01(\v25.miidas.user.marketvalue.user.ContractCompanyResidentR\x17ContractCompanyResident\"\xa4\x01\n" +
	"\bIndustry\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\tmain_only\x18\x02 \x01(\bR\bmainOnly\x12\x18\n" +
	"\aexclude\x18\x03 \x01(\bR\aexclude\x12A\n" +
	"\x05value\x18\x04 \x01(\v2+.miidas.user.marketvalue.user.IndustryValueR\x05value\"U\n" +
	"\rIndustryValue\x12\x16\n" +
	"\x06larges\x18\x01 \x03(\x05R\x06larges\x12\x16\n" +
	"\x06middle\x18\x02 \x03(\x05R\x06middle\x12\x14\n" +
	"\x05small\x18\x03 \x03(\x05R\x05small\"u\n" +
	"\fDecisionType\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12E\n" +
	"\x05value\x18\x02 \x01(\v2/.miidas.user.marketvalue.user.DecisionTypeValueR\x05value\"\xc5\x01\n" +
	"\x11DecisionTypeValue\x12*\n" +
	"\rdecision_type\x18\x01 \x01(\x05B\x05\xaa\x01\x02\b\x01R\fdecisionType\x12/\n" +
	"\x10logic_or_emotion\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x0elogicOrEmotion\x12#\n" +
	"\tauthority\x18\x03 \x01(\x05B\x05\xaa\x01\x02\b\x01R\tauthority\x12.\n" +
	"\x0fwork_procedures\x18\x04 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x0eworkProcedures\"\x7f\n" +
	"\x11EmployeeCharacter\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12J\n" +
	"\x05value\x18\x02 \x01(\v24.miidas.user.marketvalue.user.EmployeeCharacterValueR\x05value\"\xf6\x05\n" +
	"\x16EmployeeCharacterValue\x12+\n" +
	"\rAgeOfActivity\x18\x01 \x01(\x05B\x05\xaa\x01\x02\b\x01R\rAgeOfActivity\x12Q\n" +
	" ChallengeLevelOfCorporateCulture\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R ChallengeLevelOfCorporateCulture\x123\n" +
	"\x11WorkplaceVibrancy\x18\x03 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x11WorkplaceVibrancy\x12A\n" +
	"\x18HierarchicalRelationship\x18\x04 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x18HierarchicalRelationship\x127\n" +
	"\x13WorkplaceAtmosphere\x18\x05 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x13WorkplaceAtmosphere\x12=\n" +
	"\x16OrganizationManagement\x18\x06 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x16OrganizationManagement\x127\n" +
	"\x13MilitaryLikeOrBrain\x18\a \x01(\x05B\x05\xaa\x01\x02\b\x01R\x13MilitaryLikeOrBrain\x125\n" +
	"\x12WorkOrPersonalLife\x18\b \x01(\x05B\x05\xaa\x01\x02\b\x01R\x12WorkOrPersonalLife\x12+\n" +
	"\rCompanyEvents\x18\t \x01(\x05B\x05\xaa\x01\x02\b\x01R\rCompanyEvents\x12;\n" +
	"\x15DrinkingPartyWithBoss\x18\n" +
	" \x01(\x05B\x05\xaa\x01\x02\b\x01R\x15DrinkingPartyWithBoss\x12E\n" +
	"\x1aDrinkingPartyWithColleague\x18\v \x01(\x05B\x05\xaa\x01\x02\b\x01R\x1aDrinkingPartyWithColleague\x12K\n" +
	"\x1dCorporatePhilosophyPenetrance\x18\f \x01(\x05B\x05\xaa\x01\x02\b\x01R\x1dCorporatePhilosophyPenetrance\"R\n" +
	"\x1aHREvaluationPromotionSpeed\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"J\n" +
	"\x12EmployeeAverageAge\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"M\n" +
	"\x15EmployeeMidCareerRate\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"I\n" +
	"\x11EmployeeWomanRate\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"V\n" +
	"\x1eEmployeeForeignNationalityRate\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"[\n" +
	"\x1cForeignNationalityRecruiting\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05value\"K\n" +
	"\x13BusinessEmployeeQty\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"Q\n" +
	"\x19BusinessEstablishmentYear\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"J\n" +
	"\x12BusinessSalesScale\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"=\n" +
	"\x05Stage\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"E\n" +
	"\rProductsShare\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"M\n" +
	"\x0eHasOwnProducts\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05value\"S\n" +
	"\x14ProductsTangibleness\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05value\"M\n" +
	"\x0eTargetCustomer\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05value\"\x81\x01\n" +
	"\x12TargetCustomerBtoB\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12K\n" +
	"\x05value\x18\x02 \x01(\v25.miidas.user.marketvalue.user.TargetCustomerBtoBValueR\x05value\"\xb7\x01\n" +
	"\x17TargetCustomerBtoBValue\x122\n" +
	"\x14TargetCustomerLarges\x18\x01 \x03(\x05R\x14TargetCustomerLarges\x124\n" +
	"\x15TargetCustomerMiddles\x18\x02 \x03(\x05R\x15TargetCustomerMiddles\x122\n" +
	"\x14TargetCustomerSmalls\x18\x03 \x03(\x05R\x14TargetCustomerSmalls\"J\n" +
	"\x12TargetCustomerBtoC\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"D\n" +
	"\fTrendKeyword\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"F\n" +
	"\x0eMarketProspect\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"@\n" +
	"\bStrategy\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"A\n" +
	"\tAdvantage\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"M\n" +
	"\x15MedicalAdvantageField\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\">\n" +
	"\x06SIType\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"K\n" +
	"\x13SIAdvantageIndustry\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"D\n" +
	"\fCarPartsTier\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"S\n" +
	"\x1bContractCompanyProfitSource\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"R\n" +
	"\x1aContractCompanyProjectTerm\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"U\n" +
	"\x1dContractCompanyClientResident\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"O\n" +
	"\x17ContractCompanyResident\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05valueB1Z*miidas/m2/user/marketvalue/grpc/iface/user\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_user_will_business_proto_rawDescOnce sync.Once
	file_user_will_business_proto_rawDescData []byte
)

func file_user_will_business_proto_rawDescGZIP() []byte {
	file_user_will_business_proto_rawDescOnce.Do(func() {
		file_user_will_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_will_business_proto_rawDesc), len(file_user_will_business_proto_rawDesc)))
	})
	return file_user_will_business_proto_rawDescData
}

var file_user_will_business_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_user_will_business_proto_goTypes = []any{
	(*BusinessWill)(nil),                   // 0: miidas.user.marketvalue.user.BusinessWill
	(*Industry)(nil),                       // 1: miidas.user.marketvalue.user.Industry
	(*IndustryValue)(nil),                  // 2: miidas.user.marketvalue.user.IndustryValue
	(*DecisionType)(nil),                   // 3: miidas.user.marketvalue.user.DecisionType
	(*DecisionTypeValue)(nil),              // 4: miidas.user.marketvalue.user.DecisionTypeValue
	(*EmployeeCharacter)(nil),              // 5: miidas.user.marketvalue.user.EmployeeCharacter
	(*EmployeeCharacterValue)(nil),         // 6: miidas.user.marketvalue.user.EmployeeCharacterValue
	(*HREvaluationPromotionSpeed)(nil),     // 7: miidas.user.marketvalue.user.HREvaluationPromotionSpeed
	(*EmployeeAverageAge)(nil),             // 8: miidas.user.marketvalue.user.EmployeeAverageAge
	(*EmployeeMidCareerRate)(nil),          // 9: miidas.user.marketvalue.user.EmployeeMidCareerRate
	(*EmployeeWomanRate)(nil),              // 10: miidas.user.marketvalue.user.EmployeeWomanRate
	(*EmployeeForeignNationalityRate)(nil), // 11: miidas.user.marketvalue.user.EmployeeForeignNationalityRate
	(*ForeignNationalityRecruiting)(nil),   // 12: miidas.user.marketvalue.user.ForeignNationalityRecruiting
	(*BusinessEmployeeQty)(nil),            // 13: miidas.user.marketvalue.user.BusinessEmployeeQty
	(*BusinessEstablishmentYear)(nil),      // 14: miidas.user.marketvalue.user.BusinessEstablishmentYear
	(*BusinessSalesScale)(nil),             // 15: miidas.user.marketvalue.user.BusinessSalesScale
	(*Stage)(nil),                          // 16: miidas.user.marketvalue.user.Stage
	(*ProductsShare)(nil),                  // 17: miidas.user.marketvalue.user.ProductsShare
	(*HasOwnProducts)(nil),                 // 18: miidas.user.marketvalue.user.HasOwnProducts
	(*ProductsTangibleness)(nil),           // 19: miidas.user.marketvalue.user.ProductsTangibleness
	(*TargetCustomer)(nil),                 // 20: miidas.user.marketvalue.user.TargetCustomer
	(*TargetCustomerBtoB)(nil),             // 21: miidas.user.marketvalue.user.TargetCustomerBtoB
	(*TargetCustomerBtoBValue)(nil),        // 22: miidas.user.marketvalue.user.TargetCustomerBtoBValue
	(*TargetCustomerBtoC)(nil),             // 23: miidas.user.marketvalue.user.TargetCustomerBtoC
	(*TrendKeyword)(nil),                   // 24: miidas.user.marketvalue.user.TrendKeyword
	(*MarketProspect)(nil),                 // 25: miidas.user.marketvalue.user.MarketProspect
	(*Strategy)(nil),                       // 26: miidas.user.marketvalue.user.Strategy
	(*Advantage)(nil),                      // 27: miidas.user.marketvalue.user.Advantage
	(*MedicalAdvantageField)(nil),          // 28: miidas.user.marketvalue.user.MedicalAdvantageField
	(*SIType)(nil),                         // 29: miidas.user.marketvalue.user.SIType
	(*SIAdvantageIndustry)(nil),            // 30: miidas.user.marketvalue.user.SIAdvantageIndustry
	(*CarPartsTier)(nil),                   // 31: miidas.user.marketvalue.user.CarPartsTier
	(*ContractCompanyProfitSource)(nil),    // 32: miidas.user.marketvalue.user.ContractCompanyProfitSource
	(*ContractCompanyProjectTerm)(nil),     // 33: miidas.user.marketvalue.user.ContractCompanyProjectTerm
	(*ContractCompanyClientResident)(nil),  // 34: miidas.user.marketvalue.user.ContractCompanyClientResident
	(*ContractCompanyResident)(nil),        // 35: miidas.user.marketvalue.user.ContractCompanyResident
}
var file_user_will_business_proto_depIdxs = []int32{
	1,  // 0: miidas.user.marketvalue.user.BusinessWill.Industry:type_name -> miidas.user.marketvalue.user.Industry
	3,  // 1: miidas.user.marketvalue.user.BusinessWill.DecisionType:type_name -> miidas.user.marketvalue.user.DecisionType
	5,  // 2: miidas.user.marketvalue.user.BusinessWill.EmployeeCharacter:type_name -> miidas.user.marketvalue.user.EmployeeCharacter
	7,  // 3: miidas.user.marketvalue.user.BusinessWill.HREvaluationPromotionSpeed:type_name -> miidas.user.marketvalue.user.HREvaluationPromotionSpeed
	8,  // 4: miidas.user.marketvalue.user.BusinessWill.EmployeeAverageAge:type_name -> miidas.user.marketvalue.user.EmployeeAverageAge
	9,  // 5: miidas.user.marketvalue.user.BusinessWill.EmployeeMidCareerRate:type_name -> miidas.user.marketvalue.user.EmployeeMidCareerRate
	10, // 6: miidas.user.marketvalue.user.BusinessWill.EmployeeWomanRate:type_name -> miidas.user.marketvalue.user.EmployeeWomanRate
	11, // 7: miidas.user.marketvalue.user.BusinessWill.EmployeeForeignNationalityRate:type_name -> miidas.user.marketvalue.user.EmployeeForeignNationalityRate
	12, // 8: miidas.user.marketvalue.user.BusinessWill.ForeignNationalityRecruiting:type_name -> miidas.user.marketvalue.user.ForeignNationalityRecruiting
	13, // 9: miidas.user.marketvalue.user.BusinessWill.EmployeeQty:type_name -> miidas.user.marketvalue.user.BusinessEmployeeQty
	14, // 10: miidas.user.marketvalue.user.BusinessWill.EstablishmentYear:type_name -> miidas.user.marketvalue.user.BusinessEstablishmentYear
	15, // 11: miidas.user.marketvalue.user.BusinessWill.SalesScale:type_name -> miidas.user.marketvalue.user.BusinessSalesScale
	16, // 12: miidas.user.marketvalue.user.BusinessWill.Stage:type_name -> miidas.user.marketvalue.user.Stage
	17, // 13: miidas.user.marketvalue.user.BusinessWill.ProductsShare:type_name -> miidas.user.marketvalue.user.ProductsShare
	18, // 14: miidas.user.marketvalue.user.BusinessWill.HasOwnProducts:type_name -> miidas.user.marketvalue.user.HasOwnProducts
	19, // 15: miidas.user.marketvalue.user.BusinessWill.ProductsTangibleness:type_name -> miidas.user.marketvalue.user.ProductsTangibleness
	20, // 16: miidas.user.marketvalue.user.BusinessWill.TargetCustomer:type_name -> miidas.user.marketvalue.user.TargetCustomer
	21, // 17: miidas.user.marketvalue.user.BusinessWill.TargetCustomerBtoB:type_name -> miidas.user.marketvalue.user.TargetCustomerBtoB
	23, // 18: miidas.user.marketvalue.user.BusinessWill.TargetCustomerBtoC:type_name -> miidas.user.marketvalue.user.TargetCustomerBtoC
	24, // 19: miidas.user.marketvalue.user.BusinessWill.TrendKeyword:type_name -> miidas.user.marketvalue.user.TrendKeyword
	25, // 20: miidas.user.marketvalue.user.BusinessWill.MarketProspect:type_name -> miidas.user.marketvalue.user.MarketProspect
	26, // 21: miidas.user.marketvalue.user.BusinessWill.Strategy:type_name -> miidas.user.marketvalue.user.Strategy
	27, // 22: miidas.user.marketvalue.user.BusinessWill.Advantage:type_name -> miidas.user.marketvalue.user.Advantage
	28, // 23: miidas.user.marketvalue.user.BusinessWill.MedicalAdvantageField:type_name -> miidas.user.marketvalue.user.MedicalAdvantageField
	29, // 24: miidas.user.marketvalue.user.BusinessWill.SIType:type_name -> miidas.user.marketvalue.user.SIType
	30, // 25: miidas.user.marketvalue.user.BusinessWill.SIAdvantageIndustry:type_name -> miidas.user.marketvalue.user.SIAdvantageIndustry
	31, // 26: miidas.user.marketvalue.user.BusinessWill.CarPartsTier:type_name -> miidas.user.marketvalue.user.CarPartsTier
	32, // 27: miidas.user.marketvalue.user.BusinessWill.ContractCompanyProfitSource:type_name -> miidas.user.marketvalue.user.ContractCompanyProfitSource
	33, // 28: miidas.user.marketvalue.user.BusinessWill.ContractCompanyProjectTerm:type_name -> miidas.user.marketvalue.user.ContractCompanyProjectTerm
	34, // 29: miidas.user.marketvalue.user.BusinessWill.ContractCompanyClientResident:type_name -> miidas.user.marketvalue.user.ContractCompanyClientResident
	35, // 30: miidas.user.marketvalue.user.BusinessWill.ContractCompanyResident:type_name -> miidas.user.marketvalue.user.ContractCompanyResident
	2,  // 31: miidas.user.marketvalue.user.Industry.value:type_name -> miidas.user.marketvalue.user.IndustryValue
	4,  // 32: miidas.user.marketvalue.user.DecisionType.value:type_name -> miidas.user.marketvalue.user.DecisionTypeValue
	6,  // 33: miidas.user.marketvalue.user.EmployeeCharacter.value:type_name -> miidas.user.marketvalue.user.EmployeeCharacterValue
	22, // 34: miidas.user.marketvalue.user.TargetCustomerBtoB.value:type_name -> miidas.user.marketvalue.user.TargetCustomerBtoBValue
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_user_will_business_proto_init() }
func file_user_will_business_proto_init() {
	if File_user_will_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_will_business_proto_rawDesc), len(file_user_will_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_will_business_proto_goTypes,
		DependencyIndexes: file_user_will_business_proto_depIdxs,
		MessageInfos:      file_user_will_business_proto_msgTypes,
	}.Build()
	File_user_will_business_proto = out.File
	file_user_will_business_proto_goTypes = nil
	file_user_will_business_proto_depIdxs = nil
}
