// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: common/vo.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueText) Reset() {
	*x = ValueText{}
	mi := &file_common_vo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueText) ProtoMessage() {}

func (x *ValueText) ProtoReflect() protoreflect.Message {
	mi := &file_common_vo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueText.ProtoReflect.Descriptor instead.
func (*ValueText) Descriptor() ([]byte, []int) {
	return file_common_vo_proto_rawDescGZIP(), []int{0}
}

func (x *ValueText) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ValueText) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ValueText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ValuesText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*IntIdNamePair       `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuesText) Reset() {
	*x = ValuesText{}
	mi := &file_common_vo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuesText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesText) ProtoMessage() {}

func (x *ValuesText) ProtoReflect() protoreflect.Message {
	mi := &file_common_vo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesText.ProtoReflect.Descriptor instead.
func (*ValuesText) Descriptor() ([]byte, []int) {
	return file_common_vo_proto_rawDescGZIP(), []int{1}
}

func (x *ValuesText) GetIds() []*IntIdNamePair {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ValuesText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type IntIdNamePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntIdNamePair) Reset() {
	*x = IntIdNamePair{}
	mi := &file_common_vo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntIdNamePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntIdNamePair) ProtoMessage() {}

func (x *IntIdNamePair) ProtoReflect() protoreflect.Message {
	mi := &file_common_vo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntIdNamePair.ProtoReflect.Descriptor instead.
func (*IntIdNamePair) Descriptor() ([]byte, []int) {
	return file_common_vo_proto_rawDescGZIP(), []int{2}
}

func (x *IntIdNamePair) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IntIdNamePair) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type IntIdLabelPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntIdLabelPair) Reset() {
	*x = IntIdLabelPair{}
	mi := &file_common_vo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntIdLabelPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntIdLabelPair) ProtoMessage() {}

func (x *IntIdLabelPair) ProtoReflect() protoreflect.Message {
	mi := &file_common_vo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntIdLabelPair.ProtoReflect.Descriptor instead.
func (*IntIdLabelPair) Descriptor() ([]byte, []int) {
	return file_common_vo_proto_rawDescGZIP(), []int{3}
}

func (x *IntIdLabelPair) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IntIdLabelPair) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Flag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	On            bool                   `protobuf:"varint,1,opt,name=on" json:"on,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flag) Reset() {
	*x = Flag{}
	mi := &file_common_vo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flag) ProtoMessage() {}

func (x *Flag) ProtoReflect() protoreflect.Message {
	mi := &file_common_vo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flag.ProtoReflect.Descriptor instead.
func (*Flag) Descriptor() ([]byte, []int) {
	return file_common_vo_proto_rawDescGZIP(), []int{4}
}

func (x *Flag) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

func (x *Flag) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type FlagText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flg           *Flag                  `protobuf:"bytes,1,opt,name=flg" json:"flg,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlagText) Reset() {
	*x = FlagText{}
	mi := &file_common_vo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlagText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlagText) ProtoMessage() {}

func (x *FlagText) ProtoReflect() protoreflect.Message {
	mi := &file_common_vo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlagText.ProtoReflect.Descriptor instead.
func (*FlagText) Descriptor() ([]byte, []int) {
	return file_common_vo_proto_rawDescGZIP(), []int{5}
}

func (x *FlagText) GetFlg() *Flag {
	if x != nil {
		return x.Flg
	}
	return nil
}

func (x *FlagText) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlagText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_common_vo_proto protoreflect.FileDescriptor

const file_common_vo_proto_rawDesc = "" +
	"\n" +
	"\x0fcommon/vo.proto\x12\x1emiidas.user.marketvalue.common\"E\n" +
	"\tValueText\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"a\n" +
	"\n" +
	"ValuesText\x12?\n" +
	"\x03ids\x18\x01 \x03(\v2-.miidas.user.marketvalue.common.IntIdNamePairR\x03ids\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"3\n" +
	"\rIntIdNamePair\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"6\n" +
	"\x0eIntIdLabelPair\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\",\n" +
	"\x04Flag\x12\x0e\n" +
	"\x02on\x18\x01 \x01(\bR\x02on\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"j\n" +
	"\bFlagText\x126\n" +
	"\x03flg\x18\x01 \x01(\v2$.miidas.user.marketvalue.common.FlagR\x03flg\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04textB3Z,miidas/m2/user/marketvalue/grpc/iface/common\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_common_vo_proto_rawDescOnce sync.Once
	file_common_vo_proto_rawDescData []byte
)

func file_common_vo_proto_rawDescGZIP() []byte {
	file_common_vo_proto_rawDescOnce.Do(func() {
		file_common_vo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_vo_proto_rawDesc), len(file_common_vo_proto_rawDesc)))
	})
	return file_common_vo_proto_rawDescData
}

var file_common_vo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_vo_proto_goTypes = []any{
	(*ValueText)(nil),      // 0: miidas.user.marketvalue.common.ValueText
	(*ValuesText)(nil),     // 1: miidas.user.marketvalue.common.ValuesText
	(*IntIdNamePair)(nil),  // 2: miidas.user.marketvalue.common.IntIdNamePair
	(*IntIdLabelPair)(nil), // 3: miidas.user.marketvalue.common.IntIdLabelPair
	(*Flag)(nil),           // 4: miidas.user.marketvalue.common.Flag
	(*FlagText)(nil),       // 5: miidas.user.marketvalue.common.FlagText
}
var file_common_vo_proto_depIdxs = []int32{
	2, // 0: miidas.user.marketvalue.common.ValuesText.ids:type_name -> miidas.user.marketvalue.common.IntIdNamePair
	4, // 1: miidas.user.marketvalue.common.FlagText.flg:type_name -> miidas.user.marketvalue.common.Flag
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_vo_proto_init() }
func file_common_vo_proto_init() {
	if File_common_vo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_vo_proto_rawDesc), len(file_common_vo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_vo_proto_goTypes,
		DependencyIndexes: file_common_vo_proto_depIdxs,
		MessageInfos:      file_common_vo_proto_msgTypes,
	}.Build()
	File_common_vo_proto = out.File
	file_common_vo_proto_goTypes = nil
	file_common_vo_proto_depIdxs = nil
}
