// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: company/company.proto

package company

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "miidas/m2/user/marketvalue/grpc/iface/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Company struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Detail               *Detail                `protobuf:"bytes,2,opt,name=detail" json:"detail,omitempty"`
	IsSearchable         bool                   `protobuf:"varint,3,opt,name=is_searchable,json=isSearchable" json:"is_searchable,omitempty"`
	StopOffer            bool                   `protobuf:"varint,4,opt,name=stop_offer,json=stopOffer" json:"stop_offer,omitempty"`
	RegistrationStatusId int32                  `protobuf:"varint,5,opt,name=registration_status_id,json=registrationStatusId" json:"registration_status_id,omitempty"`
	LastModifiedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_modified_at,json=lastModifiedAt" json:"last_modified_at,omitempty"`
	ImportedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=imported_at,json=importedAt" json:"imported_at,omitempty"`
	StopOfferDatetime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=stop_offer_datetime,json=stopOfferDatetime" json:"stop_offer_datetime,omitempty"`
	IsMatchingEnabled    bool                   `protobuf:"varint,9,opt,name=is_matching_enabled,json=isMatchingEnabled" json:"is_matching_enabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_company_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_company_company_proto_rawDescGZIP(), []int{0}
}

func (x *Company) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Company) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Company) GetIsSearchable() bool {
	if x != nil {
		return x.IsSearchable
	}
	return false
}

func (x *Company) GetStopOffer() bool {
	if x != nil {
		return x.StopOffer
	}
	return false
}

func (x *Company) GetRegistrationStatusId() int32 {
	if x != nil {
		return x.RegistrationStatusId
	}
	return 0
}

func (x *Company) GetLastModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedAt
	}
	return nil
}

func (x *Company) GetImportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ImportedAt
	}
	return nil
}

func (x *Company) GetStopOfferDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.StopOfferDatetime
	}
	return nil
}

func (x *Company) GetIsMatchingEnabled() bool {
	if x != nil {
		return x.IsMatchingEnabled
	}
	return false
}

type Detail struct {
	state                        protoimpl.MessageState           `protogen:"open.v1"`
	Name                         string                           `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	NameId                       int32                            `protobuf:"varint,2,opt,name=name_id,json=nameId" json:"name_id,omitempty"`
	Withdrew                     bool                             `protobuf:"varint,3,opt,name=withdrew" json:"withdrew,omitempty"`
	ProfitCompany                *common.ValueText                `protobuf:"bytes,4,opt,name=profit_company,json=profitCompany" json:"profit_company,omitempty"`
	Address                      *Detail_Address                  `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
	EmployeeQty                  *common.ValueText                `protobuf:"bytes,6,opt,name=employee_qty,json=employeeQty" json:"employee_qty,omitempty"`
	EstablishmentYear            *common.ValueText                `protobuf:"bytes,7,opt,name=establishment_year,json=establishmentYear" json:"establishment_year,omitempty"`
	CapitalType                  *common.ValuesText               `protobuf:"bytes,8,opt,name=capital_type,json=capitalType" json:"capital_type,omitempty"`
	SalesScale                   *common.ValueText                `protobuf:"bytes,9,opt,name=sales_scale,json=salesScale" json:"sales_scale,omitempty"`
	PresidentName                string                           `protobuf:"bytes,10,opt,name=president_name,json=presidentName" json:"president_name,omitempty"`
	Website                      string                           `protobuf:"bytes,11,opt,name=website" json:"website,omitempty"`
	Introduction                 string                           `protobuf:"bytes,12,opt,name=introduction" json:"introduction,omitempty"`
	AppealPoint                  *common.ValuesText               `protobuf:"bytes,13,opt,name=appeal_point,json=appealPoint" json:"appeal_point,omitempty"`
	SalesOverseasRate            *common.ValueText                `protobuf:"bytes,14,opt,name=sales_overseas_rate,json=salesOverseasRate" json:"sales_overseas_rate,omitempty"`
	EmployeeWorkAbroadRate       *common.ValueText                `protobuf:"bytes,15,opt,name=employee_work_abroad_rate,json=employeeWorkAbroadRate" json:"employee_work_abroad_rate,omitempty"`
	WelfareBenefit               []*common.ValueText              `protobuf:"bytes,16,rep,name=welfare_benefit,json=welfareBenefit" json:"welfare_benefit,omitempty"`
	YearHolidays                 *common.ValueText                `protobuf:"bytes,17,opt,name=year_holidays,json=yearHolidays" json:"year_holidays,omitempty"`
	SideBusiness                 *common.ValueText                `protobuf:"bytes,18,opt,name=side_business,json=sideBusiness" json:"side_business,omitempty"`
	SideBusinessCondition        string                           `protobuf:"bytes,19,opt,name=side_business_condition,json=sideBusinessCondition" json:"side_business_condition,omitempty"`
	Vacations                    []*common.ValueText              `protobuf:"bytes,20,rep,name=vacations" json:"vacations,omitempty"`
	PaidHolidayUseRate           *common.ValueText                `protobuf:"bytes,21,opt,name=paid_holiday_use_rate,json=paidHolidayUseRate" json:"paid_holiday_use_rate,omitempty"`
	JobRotationExists            *common.FlagText                 `protobuf:"bytes,22,opt,name=job_rotation_exists,json=jobRotationExists" json:"job_rotation_exists,omitempty"`
	ChangeDepartmentRequest      *common.FlagText                 `protobuf:"bytes,23,opt,name=change_department_request,json=changeDepartmentRequest" json:"change_department_request,omitempty"`
	SpecialistCareerPath         *common.ValueText                `protobuf:"bytes,24,opt,name=specialist_career_path,json=specialistCareerPath" json:"specialist_career_path,omitempty"`
	HrEvaluationSpecialSystem    *common.ValuesText               `protobuf:"bytes,25,opt,name=hr_evaluation_special_system,json=hrEvaluationSpecialSystem" json:"hr_evaluation_special_system,omitempty"`
	HrEvaluationWomanManagerRate *common.ValueText                `protobuf:"bytes,26,opt,name=hr_evaluation_woman_manager_rate,json=hrEvaluationWomanManagerRate" json:"hr_evaluation_woman_manager_rate,omitempty"`
	HrEvaluation20SManagerRate   *common.ValueText                `protobuf:"bytes,27,opt,name=hr_evaluation20s_manager_rate,json=hrEvaluation20sManagerRate" json:"hr_evaluation20s_manager_rate,omitempty"`
	TrainingSystem               *Detail_TrainingSystem           `protobuf:"bytes,28,opt,name=training_system,json=trainingSystem" json:"training_system,omitempty"`
	WelfareAchievement           []*common.ValueText              `protobuf:"bytes,29,rep,name=welfare_achievement,json=welfareAchievement" json:"welfare_achievement,omitempty"`
	WelfarePopular               []*common.ValueText              `protobuf:"bytes,30,rep,name=welfare_popular,json=welfarePopular" json:"welfare_popular,omitempty"`
	WelfareOther                 []*common.ValueText              `protobuf:"bytes,31,rep,name=welfare_other,json=welfareOther" json:"welfare_other,omitempty"`
	Other                        *common.ValuesText               `protobuf:"bytes,32,opt,name=other" json:"other,omitempty"`
	Pr                           string                           `protobuf:"bytes,33,opt,name=pr" json:"pr,omitempty"`
	Document                     []*Detail_Document               `protobuf:"bytes,34,rep,name=document" json:"document,omitempty"`
	HpmCertifiedFrom             *timestamppb.Timestamp           `protobuf:"bytes,35,opt,name=hpm_certified_from,json=hpmCertifiedFrom" json:"hpm_certified_from,omitempty"`
	HpmCertifiedTo               *timestamppb.Timestamp           `protobuf:"bytes,36,opt,name=hpm_certified_to,json=hpmCertifiedTo" json:"hpm_certified_to,omitempty"`
	IsAgreedHatarakuhitoFirst    bool                             `protobuf:"varint,37,opt,name=is_agreed_hatarakuhito_first,json=isAgreedHatarakuhitoFirst" json:"is_agreed_hatarakuhito_first,omitempty"`
	RecentHpmCertifications      []*Detail_RecentHPMCertification `protobuf:"bytes,38,rep,name=recent_hpm_certifications,json=recentHpmCertifications" json:"recent_hpm_certifications,omitempty"`
	WelfareInsurance             []*common.ValueText              `protobuf:"bytes,39,rep,name=welfare_insurance,json=welfareInsurance" json:"welfare_insurance,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Detail) Reset() {
	*x = Detail{}
	mi := &file_company_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_company_company_proto_rawDescGZIP(), []int{1}
}

func (x *Detail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Detail) GetNameId() int32 {
	if x != nil {
		return x.NameId
	}
	return 0
}

func (x *Detail) GetWithdrew() bool {
	if x != nil {
		return x.Withdrew
	}
	return false
}

func (x *Detail) GetProfitCompany() *common.ValueText {
	if x != nil {
		return x.ProfitCompany
	}
	return nil
}

func (x *Detail) GetAddress() *Detail_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Detail) GetEmployeeQty() *common.ValueText {
	if x != nil {
		return x.EmployeeQty
	}
	return nil
}

func (x *Detail) GetEstablishmentYear() *common.ValueText {
	if x != nil {
		return x.EstablishmentYear
	}
	return nil
}

func (x *Detail) GetCapitalType() *common.ValuesText {
	if x != nil {
		return x.CapitalType
	}
	return nil
}

func (x *Detail) GetSalesScale() *common.ValueText {
	if x != nil {
		return x.SalesScale
	}
	return nil
}

func (x *Detail) GetPresidentName() string {
	if x != nil {
		return x.PresidentName
	}
	return ""
}

func (x *Detail) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Detail) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *Detail) GetAppealPoint() *common.ValuesText {
	if x != nil {
		return x.AppealPoint
	}
	return nil
}

func (x *Detail) GetSalesOverseasRate() *common.ValueText {
	if x != nil {
		return x.SalesOverseasRate
	}
	return nil
}

func (x *Detail) GetEmployeeWorkAbroadRate() *common.ValueText {
	if x != nil {
		return x.EmployeeWorkAbroadRate
	}
	return nil
}

func (x *Detail) GetWelfareBenefit() []*common.ValueText {
	if x != nil {
		return x.WelfareBenefit
	}
	return nil
}

func (x *Detail) GetYearHolidays() *common.ValueText {
	if x != nil {
		return x.YearHolidays
	}
	return nil
}

func (x *Detail) GetSideBusiness() *common.ValueText {
	if x != nil {
		return x.SideBusiness
	}
	return nil
}

func (x *Detail) GetSideBusinessCondition() string {
	if x != nil {
		return x.SideBusinessCondition
	}
	return ""
}

func (x *Detail) GetVacations() []*common.ValueText {
	if x != nil {
		return x.Vacations
	}
	return nil
}

func (x *Detail) GetPaidHolidayUseRate() *common.ValueText {
	if x != nil {
		return x.PaidHolidayUseRate
	}
	return nil
}

func (x *Detail) GetJobRotationExists() *common.FlagText {
	if x != nil {
		return x.JobRotationExists
	}
	return nil
}

func (x *Detail) GetChangeDepartmentRequest() *common.FlagText {
	if x != nil {
		return x.ChangeDepartmentRequest
	}
	return nil
}

func (x *Detail) GetSpecialistCareerPath() *common.ValueText {
	if x != nil {
		return x.SpecialistCareerPath
	}
	return nil
}

func (x *Detail) GetHrEvaluationSpecialSystem() *common.ValuesText {
	if x != nil {
		return x.HrEvaluationSpecialSystem
	}
	return nil
}

func (x *Detail) GetHrEvaluationWomanManagerRate() *common.ValueText {
	if x != nil {
		return x.HrEvaluationWomanManagerRate
	}
	return nil
}

func (x *Detail) GetHrEvaluation20SManagerRate() *common.ValueText {
	if x != nil {
		return x.HrEvaluation20SManagerRate
	}
	return nil
}

func (x *Detail) GetTrainingSystem() *Detail_TrainingSystem {
	if x != nil {
		return x.TrainingSystem
	}
	return nil
}

func (x *Detail) GetWelfareAchievement() []*common.ValueText {
	if x != nil {
		return x.WelfareAchievement
	}
	return nil
}

func (x *Detail) GetWelfarePopular() []*common.ValueText {
	if x != nil {
		return x.WelfarePopular
	}
	return nil
}

func (x *Detail) GetWelfareOther() []*common.ValueText {
	if x != nil {
		return x.WelfareOther
	}
	return nil
}

func (x *Detail) GetOther() *common.ValuesText {
	if x != nil {
		return x.Other
	}
	return nil
}

func (x *Detail) GetPr() string {
	if x != nil {
		return x.Pr
	}
	return ""
}

func (x *Detail) GetDocument() []*Detail_Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *Detail) GetHpmCertifiedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.HpmCertifiedFrom
	}
	return nil
}

func (x *Detail) GetHpmCertifiedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.HpmCertifiedTo
	}
	return nil
}

func (x *Detail) GetIsAgreedHatarakuhitoFirst() bool {
	if x != nil {
		return x.IsAgreedHatarakuhitoFirst
	}
	return false
}

func (x *Detail) GetRecentHpmCertifications() []*Detail_RecentHPMCertification {
	if x != nil {
		return x.RecentHpmCertifications
	}
	return nil
}

func (x *Detail) GetWelfareInsurance() []*common.ValueText {
	if x != nil {
		return x.WelfareInsurance
	}
	return nil
}

type Detail_Address struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrefectureId    int32                  `protobuf:"varint,1,opt,name=prefecture_id,json=prefectureId" json:"prefecture_id,omitempty"`
	PrefectureLabel string                 `protobuf:"bytes,2,opt,name=prefecture_label,json=prefectureLabel" json:"prefecture_label,omitempty"`
	Address         string                 `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Detail_Address) Reset() {
	*x = Detail_Address{}
	mi := &file_company_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_Address) ProtoMessage() {}

func (x *Detail_Address) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_Address.ProtoReflect.Descriptor instead.
func (*Detail_Address) Descriptor() ([]byte, []int) {
	return file_company_company_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Detail_Address) GetPrefectureId() int32 {
	if x != nil {
		return x.PrefectureId
	}
	return 0
}

func (x *Detail_Address) GetPrefectureLabel() string {
	if x != nil {
		return x.PrefectureLabel
	}
	return ""
}

func (x *Detail_Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Detail_Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_Document) Reset() {
	*x = Detail_Document{}
	mi := &file_company_company_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_Document) ProtoMessage() {}

func (x *Detail_Document) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_Document.ProtoReflect.Descriptor instead.
func (*Detail_Document) Descriptor() ([]byte, []int) {
	return file_company_company_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Detail_Document) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Detail_Document) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Detail_Document) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Detail_TrainingSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_TrainingSystem) Reset() {
	*x = Detail_TrainingSystem{}
	mi := &file_company_company_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_TrainingSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_TrainingSystem) ProtoMessage() {}

func (x *Detail_TrainingSystem) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_TrainingSystem.ProtoReflect.Descriptor instead.
func (*Detail_TrainingSystem) Descriptor() ([]byte, []int) {
	return file_company_company_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Detail_TrainingSystem) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *Detail_TrainingSystem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Detail_RecentHPMCertification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year" json:"year,omitempty"`
	From          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_RecentHPMCertification) Reset() {
	*x = Detail_RecentHPMCertification{}
	mi := &file_company_company_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_RecentHPMCertification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_RecentHPMCertification) ProtoMessage() {}

func (x *Detail_RecentHPMCertification) ProtoReflect() protoreflect.Message {
	mi := &file_company_company_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_RecentHPMCertification.ProtoReflect.Descriptor instead.
func (*Detail_RecentHPMCertification) Descriptor() ([]byte, []int) {
	return file_company_company_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Detail_RecentHPMCertification) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Detail_RecentHPMCertification) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Detail_RecentHPMCertification) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

var File_company_company_proto protoreflect.FileDescriptor

const file_company_company_proto_rawDesc = "" +
	"\n" +
	"\x15company/company.proto\x12\x1fmiidas.user.marketvalue.company\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fcommon/vo.proto\"\xd3\x03\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12?\n" +
	"\x06detail\x18\x02 \x01(\v2'.miidas.user.marketvalue.company.DetailR\x06detail\x12#\n" +
	"\ris_searchable\x18\x03 \x01(\bR\fisSearchable\x12\x1d\n" +
	"\n" +
	"stop_offer\x18\x04 \x01(\bR\tstopOffer\x124\n" +
	"\x16registration_status_id\x18\x05 \x01(\x05R\x14registrationStatusId\x12D\n" +
	"\x10last_modified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastModifiedAt\x12;\n" +
	"\vimported_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"importedAt\x12J\n" +
	"\x13stop_offer_datetime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11stopOfferDatetime\x12.\n" +
	"\x13is_matching_enabled\x18\t \x01(\bR\x11isMatchingEnabled\"\x92\x1a\n" +
	"\x06Detail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\aname_id\x18\x02 \x01(\x05R\x06nameId\x12\x1a\n" +
	"\bwithdrew\x18\x03 \x01(\bR\bwithdrew\x12P\n" +
	"\x0eprofit_company\x18\x04 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\rprofitCompany\x12I\n" +
	"\aaddress\x18\x05 \x01(\v2/.miidas.user.marketvalue.company.Detail.AddressR\aaddress\x12L\n" +
	"\femployee_qty\x18\x06 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\vemployeeQty\x12X\n" +
	"\x12establishment_year\x18\a \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x11establishmentYear\x12M\n" +
	"\fcapital_type\x18\b \x01(\v2*.miidas.user.marketvalue.common.ValuesTextR\vcapitalType\x12J\n" +
	"\vsales_scale\x18\t \x01(\v2).miidas.user.marketvalue.common.ValueTextR\n" +
	"salesScale\x12%\n" +
	"\x0epresident_name\x18\n" +
	" \x01(\tR\rpresidentName\x12\x18\n" +
	"\awebsite\x18\v \x01(\tR\awebsite\x12\"\n" +
	"\fintroduction\x18\f \x01(\tR\fintroduction\x12M\n" +
	"\fappeal_point\x18\r \x01(\v2*.miidas.user.marketvalue.common.ValuesTextR\vappealPoint\x12Y\n" +
	"\x13sales_overseas_rate\x18\x0e \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x11salesOverseasRate\x12d\n" +
	"\x19employee_work_abroad_rate\x18\x0f \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x16employeeWorkAbroadRate\x12R\n" +
	"\x0fwelfare_benefit\x18\x10 \x03(\v2).miidas.user.marketvalue.common.ValueTextR\x0ewelfareBenefit\x12N\n" +
	"\ryear_holidays\x18\x11 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\fyearHolidays\x12N\n" +
	"\rside_business\x18\x12 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\fsideBusiness\x126\n" +
	"\x17side_business_condition\x18\x13 \x01(\tR\x15sideBusinessCondition\x12G\n" +
	"\tvacations\x18\x14 \x03(\v2).miidas.user.marketvalue.common.ValueTextR\tvacations\x12\\\n" +
	"\x15paid_holiday_use_rate\x18\x15 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x12paidHolidayUseRate\x12X\n" +
	"\x13job_rotation_exists\x18\x16 \x01(\v2(.miidas.user.marketvalue.common.FlagTextR\x11jobRotationExists\x12d\n" +
	"\x19change_department_request\x18\x17 \x01(\v2(.miidas.user.marketvalue.common.FlagTextR\x17changeDepartmentRequest\x12_\n" +
	"\x16specialist_career_path\x18\x18 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x14specialistCareerPath\x12k\n" +
	"\x1chr_evaluation_special_system\x18\x19 \x01(\v2*.miidas.user.marketvalue.common.ValuesTextR\x19hrEvaluationSpecialSystem\x12q\n" +
	" hr_evaluation_woman_manager_rate\x18\x1a \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x1chrEvaluationWomanManagerRate\x12l\n" +
	"\x1dhr_evaluation20s_manager_rate\x18\x1b \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x1ahrEvaluation20sManagerRate\x12_\n" +
	"\x0ftraining_system\x18\x1c \x01(\v26.miidas.user.marketvalue.company.Detail.TrainingSystemR\x0etrainingSystem\x12Z\n" +
	"\x13welfare_achievement\x18\x1d \x03(\v2).miidas.user.marketvalue.common.ValueTextR\x12welfareAchievement\x12R\n" +
	"\x0fwelfare_popular\x18\x1e \x03(\v2).miidas.user.marketvalue.common.ValueTextR\x0ewelfarePopular\x12N\n" +
	"\rwelfare_other\x18\x1f \x03(\v2).miidas.user.marketvalue.common.ValueTextR\fwelfareOther\x12@\n" +
	"\x05other\x18  \x01(\v2*.miidas.user.marketvalue.common.ValuesTextR\x05other\x12\x0e\n" +
	"\x02pr\x18! \x01(\tR\x02pr\x12L\n" +
	"\bdocument\x18\" \x03(\v20.miidas.user.marketvalue.company.Detail.DocumentR\bdocument\x12H\n" +
	"\x12hpm_certified_from\x18# \x01(\v2\x1a.google.protobuf.TimestampR\x10hpmCertifiedFrom\x12D\n" +
	"\x10hpm_certified_to\x18$ \x01(\v2\x1a.google.protobuf.TimestampR\x0ehpmCertifiedTo\x12?\n" +
	"\x1cis_agreed_hatarakuhito_first\x18% \x01(\bR\x19isAgreedHatarakuhitoFirst\x12z\n" +
	"\x19recent_hpm_certifications\x18& \x03(\v2>.miidas.user.marketvalue.company.Detail.RecentHPMCertificationR\x17recentHpmCertifications\x12V\n" +
	"\x11welfare_insurance\x18' \x03(\v2).miidas.user.marketvalue.common.ValueTextR\x10welfareInsurance\x1as\n" +
	"\aAddress\x12#\n" +
	"\rprefecture_id\x18\x01 \x01(\x05R\fprefectureId\x12)\n" +
	"\x10prefecture_label\x18\x02 \x01(\tR\x0fprefectureLabel\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x1aD\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x1a<\n" +
	"\x0eTrainingSystem\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x1a\x88\x01\n" +
	"\x16RecentHPMCertification\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12.\n" +
	"\x04from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02toB4Z-miidas/m2/user/marketvalue/grpc/iface/company\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_company_company_proto_rawDescOnce sync.Once
	file_company_company_proto_rawDescData []byte
)

func file_company_company_proto_rawDescGZIP() []byte {
	file_company_company_proto_rawDescOnce.Do(func() {
		file_company_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_company_company_proto_rawDesc), len(file_company_company_proto_rawDesc)))
	})
	return file_company_company_proto_rawDescData
}

var file_company_company_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_company_company_proto_goTypes = []any{
	(*Company)(nil),                       // 0: miidas.user.marketvalue.company.Company
	(*Detail)(nil),                        // 1: miidas.user.marketvalue.company.Detail
	(*Detail_Address)(nil),                // 2: miidas.user.marketvalue.company.Detail.Address
	(*Detail_Document)(nil),               // 3: miidas.user.marketvalue.company.Detail.Document
	(*Detail_TrainingSystem)(nil),         // 4: miidas.user.marketvalue.company.Detail.TrainingSystem
	(*Detail_RecentHPMCertification)(nil), // 5: miidas.user.marketvalue.company.Detail.RecentHPMCertification
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
	(*common.ValueText)(nil),              // 7: miidas.user.marketvalue.common.ValueText
	(*common.ValuesText)(nil),             // 8: miidas.user.marketvalue.common.ValuesText
	(*common.FlagText)(nil),               // 9: miidas.user.marketvalue.common.FlagText
}
var file_company_company_proto_depIdxs = []int32{
	1,  // 0: miidas.user.marketvalue.company.Company.detail:type_name -> miidas.user.marketvalue.company.Detail
	6,  // 1: miidas.user.marketvalue.company.Company.last_modified_at:type_name -> google.protobuf.Timestamp
	6,  // 2: miidas.user.marketvalue.company.Company.imported_at:type_name -> google.protobuf.Timestamp
	6,  // 3: miidas.user.marketvalue.company.Company.stop_offer_datetime:type_name -> google.protobuf.Timestamp
	7,  // 4: miidas.user.marketvalue.company.Detail.profit_company:type_name -> miidas.user.marketvalue.common.ValueText
	2,  // 5: miidas.user.marketvalue.company.Detail.address:type_name -> miidas.user.marketvalue.company.Detail.Address
	7,  // 6: miidas.user.marketvalue.company.Detail.employee_qty:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 7: miidas.user.marketvalue.company.Detail.establishment_year:type_name -> miidas.user.marketvalue.common.ValueText
	8,  // 8: miidas.user.marketvalue.company.Detail.capital_type:type_name -> miidas.user.marketvalue.common.ValuesText
	7,  // 9: miidas.user.marketvalue.company.Detail.sales_scale:type_name -> miidas.user.marketvalue.common.ValueText
	8,  // 10: miidas.user.marketvalue.company.Detail.appeal_point:type_name -> miidas.user.marketvalue.common.ValuesText
	7,  // 11: miidas.user.marketvalue.company.Detail.sales_overseas_rate:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 12: miidas.user.marketvalue.company.Detail.employee_work_abroad_rate:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 13: miidas.user.marketvalue.company.Detail.welfare_benefit:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 14: miidas.user.marketvalue.company.Detail.year_holidays:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 15: miidas.user.marketvalue.company.Detail.side_business:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 16: miidas.user.marketvalue.company.Detail.vacations:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 17: miidas.user.marketvalue.company.Detail.paid_holiday_use_rate:type_name -> miidas.user.marketvalue.common.ValueText
	9,  // 18: miidas.user.marketvalue.company.Detail.job_rotation_exists:type_name -> miidas.user.marketvalue.common.FlagText
	9,  // 19: miidas.user.marketvalue.company.Detail.change_department_request:type_name -> miidas.user.marketvalue.common.FlagText
	7,  // 20: miidas.user.marketvalue.company.Detail.specialist_career_path:type_name -> miidas.user.marketvalue.common.ValueText
	8,  // 21: miidas.user.marketvalue.company.Detail.hr_evaluation_special_system:type_name -> miidas.user.marketvalue.common.ValuesText
	7,  // 22: miidas.user.marketvalue.company.Detail.hr_evaluation_woman_manager_rate:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 23: miidas.user.marketvalue.company.Detail.hr_evaluation20s_manager_rate:type_name -> miidas.user.marketvalue.common.ValueText
	4,  // 24: miidas.user.marketvalue.company.Detail.training_system:type_name -> miidas.user.marketvalue.company.Detail.TrainingSystem
	7,  // 25: miidas.user.marketvalue.company.Detail.welfare_achievement:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 26: miidas.user.marketvalue.company.Detail.welfare_popular:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 27: miidas.user.marketvalue.company.Detail.welfare_other:type_name -> miidas.user.marketvalue.common.ValueText
	8,  // 28: miidas.user.marketvalue.company.Detail.other:type_name -> miidas.user.marketvalue.common.ValuesText
	3,  // 29: miidas.user.marketvalue.company.Detail.document:type_name -> miidas.user.marketvalue.company.Detail.Document
	6,  // 30: miidas.user.marketvalue.company.Detail.hpm_certified_from:type_name -> google.protobuf.Timestamp
	6,  // 31: miidas.user.marketvalue.company.Detail.hpm_certified_to:type_name -> google.protobuf.Timestamp
	5,  // 32: miidas.user.marketvalue.company.Detail.recent_hpm_certifications:type_name -> miidas.user.marketvalue.company.Detail.RecentHPMCertification
	7,  // 33: miidas.user.marketvalue.company.Detail.welfare_insurance:type_name -> miidas.user.marketvalue.common.ValueText
	6,  // 34: miidas.user.marketvalue.company.Detail.RecentHPMCertification.from:type_name -> google.protobuf.Timestamp
	6,  // 35: miidas.user.marketvalue.company.Detail.RecentHPMCertification.to:type_name -> google.protobuf.Timestamp
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_company_company_proto_init() }
func file_company_company_proto_init() {
	if File_company_company_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_company_company_proto_rawDesc), len(file_company_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_company_company_proto_goTypes,
		DependencyIndexes: file_company_company_proto_depIdxs,
		MessageInfos:      file_company_company_proto_msgTypes,
	}.Build()
	File_company_company_proto = out.File
	file_company_company_proto_goTypes = nil
	file_company_company_proto_depIdxs = nil
}
