server {
    # default "Catch All" server
    listen 80 default_server;
    server_name _;

    location / {
        return 404;
    }

    # for ELB-HealthChecker
    location = /health {
        access_log off;
        return 200;
    }
}
