// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: mv2_user_will_company.proto

package iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 企業希望条件
type Company struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vacations 休暇
	Vacations *Vacations `protobuf:"bytes,1,opt,name=vacations" json:"vacations,omitempty"`
	// YearHolidays 年間休日
	YearHolidays *YearHolidays `protobuf:"bytes,2,opt,name=yearHolidays" json:"yearHolidays,omitempty"`
	// PaidHolidayUseRate 有給休暇取得率
	PaidHolidayUseRate *PaidHolidayUseRate `protobuf:"bytes,3,opt,name=paidHolidayUseRate" json:"paidHolidayUseRate,omitempty"`
	// JobRotationExists ジョブローテーション
	JobRotationExists *JobRotationExists `protobuf:"bytes,4,opt,name=jobRotationExists" json:"jobRotationExists,omitempty"`
	// ChangeDepartmentRequest 異動希望申請制度
	ChangeDepartmentRequest *ChangeDepartmentRequest `protobuf:"bytes,5,opt,name=changeDepartmentRequest" json:"changeDepartmentRequest,omitempty"`
	// HREvaluationSpecialSystem 特殊な評価制度
	HREvaluationSpecialSystem *HREvaluationSpecialSystem `protobuf:"bytes,6,opt,name=HREvaluationSpecialSystem" json:"HREvaluationSpecialSystem,omitempty"`
	// SpecialistCareerPath スペシャリストキャリアパス
	SpecialistCareerPath *SpecialistCareerPath `protobuf:"bytes,7,opt,name=SpecialistCareerPath" json:"SpecialistCareerPath,omitempty"`
	// HREvaluationWomanManagerRate 女性管理職比率
	HREvaluationWomanManagerRate *HREvaluationWomanManagerRate `protobuf:"bytes,8,opt,name=HREvaluationWomanManagerRate" json:"HREvaluationWomanManagerRate,omitempty"`
	// HREvaluation20SManagerRate 20代管理職
	HREvaluation20SManagerRate *HREvaluation20SManagerRate `protobuf:"bytes,9,opt,name=HREvaluation20SManagerRate" json:"HREvaluation20SManagerRate,omitempty"`
	// ProfitCompany 法人種別
	ProfitCompany *ProfitCompany `protobuf:"bytes,10,opt,name=ProfitCompany" json:"ProfitCompany,omitempty"`
	// AddressPrefecture 本社所在地
	AddressPrefecture *AddressPrefecture `protobuf:"bytes,11,opt,name=AddressPrefecture" json:"AddressPrefecture,omitempty"`
	// EmployeeQty 従業員数
	EmployeeQty *EmployeeQty `protobuf:"bytes,12,opt,name=EmployeeQty" json:"EmployeeQty,omitempty"`
	// EstablishmentYear 設立
	EstablishmentYear *EstablishmentYear `protobuf:"bytes,13,opt,name=EstablishmentYear" json:"EstablishmentYear,omitempty"`
	// CapitalType 資本区分
	CapitalType *CapitalType `protobuf:"bytes,14,opt,name=CapitalType" json:"CapitalType,omitempty"`
	// SalesScale 売上規模
	SalesScale *SalesScale `protobuf:"bytes,15,opt,name=SalesScale" json:"SalesScale,omitempty"`
	// AppealPoint アピールポイント
	AppealPoint *AppealPoint `protobuf:"bytes,16,opt,name=AppealPoint" json:"AppealPoint,omitempty"`
	// EmployeeWorkAbroadRate 海外駐在社員比率
	EmployeeWorkAbroadRate *EmployeeWorkAbroadRate `protobuf:"bytes,17,opt,name=EmployeeWorkAbroadRate" json:"EmployeeWorkAbroadRate,omitempty"`
	// SalesOverseasRate 海外売上比率
	SalesOverseasRate *SalesOverseasRate `protobuf:"bytes,18,opt,name=SalesOverseasRate" json:"SalesOverseasRate,omitempty"`
	// WelfareBenefit 福利厚生（待遇）
	WelfareBenefit *WelfareBenefit `protobuf:"bytes,19,opt,name=WelfareBenefit" json:"WelfareBenefit,omitempty"`
	// WelfareAchievement 実績のある福利厚生
	WelfareAchievement *WelfareAchievement `protobuf:"bytes,20,opt,name=WelfareAchievement" json:"WelfareAchievement,omitempty"`
	// WelfarePopular 人気の福利厚生
	WelfarePopular *WelfarePopular `protobuf:"bytes,21,opt,name=WelfarePopular" json:"WelfarePopular,omitempty"`
	// WelfareOther その他福利厚生
	WelfareOther *WelfareOther `protobuf:"bytes,22,opt,name=WelfareOther" json:"WelfareOther,omitempty"`
	// TrainingSystemExists 研修制度
	TrainingSystemExists *TrainingSystemExists `protobuf:"bytes,23,opt,name=TrainingSystemExists" json:"TrainingSystemExists,omitempty"`
	// Other その他企業特徴
	Other *Other `protobuf:"bytes,24,opt,name=Other" json:"Other,omitempty"`
	// SideBusiness 副業
	SideBusiness  *SideBusiness `protobuf:"bytes,25,opt,name=SideBusiness" json:"SideBusiness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_mv2_user_will_company_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{0}
}

func (x *Company) GetVacations() *Vacations {
	if x != nil {
		return x.Vacations
	}
	return nil
}

func (x *Company) GetYearHolidays() *YearHolidays {
	if x != nil {
		return x.YearHolidays
	}
	return nil
}

func (x *Company) GetPaidHolidayUseRate() *PaidHolidayUseRate {
	if x != nil {
		return x.PaidHolidayUseRate
	}
	return nil
}

func (x *Company) GetJobRotationExists() *JobRotationExists {
	if x != nil {
		return x.JobRotationExists
	}
	return nil
}

func (x *Company) GetChangeDepartmentRequest() *ChangeDepartmentRequest {
	if x != nil {
		return x.ChangeDepartmentRequest
	}
	return nil
}

func (x *Company) GetHREvaluationSpecialSystem() *HREvaluationSpecialSystem {
	if x != nil {
		return x.HREvaluationSpecialSystem
	}
	return nil
}

func (x *Company) GetSpecialistCareerPath() *SpecialistCareerPath {
	if x != nil {
		return x.SpecialistCareerPath
	}
	return nil
}

func (x *Company) GetHREvaluationWomanManagerRate() *HREvaluationWomanManagerRate {
	if x != nil {
		return x.HREvaluationWomanManagerRate
	}
	return nil
}

func (x *Company) GetHREvaluation20SManagerRate() *HREvaluation20SManagerRate {
	if x != nil {
		return x.HREvaluation20SManagerRate
	}
	return nil
}

func (x *Company) GetProfitCompany() *ProfitCompany {
	if x != nil {
		return x.ProfitCompany
	}
	return nil
}

func (x *Company) GetAddressPrefecture() *AddressPrefecture {
	if x != nil {
		return x.AddressPrefecture
	}
	return nil
}

func (x *Company) GetEmployeeQty() *EmployeeQty {
	if x != nil {
		return x.EmployeeQty
	}
	return nil
}

func (x *Company) GetEstablishmentYear() *EstablishmentYear {
	if x != nil {
		return x.EstablishmentYear
	}
	return nil
}

func (x *Company) GetCapitalType() *CapitalType {
	if x != nil {
		return x.CapitalType
	}
	return nil
}

func (x *Company) GetSalesScale() *SalesScale {
	if x != nil {
		return x.SalesScale
	}
	return nil
}

func (x *Company) GetAppealPoint() *AppealPoint {
	if x != nil {
		return x.AppealPoint
	}
	return nil
}

func (x *Company) GetEmployeeWorkAbroadRate() *EmployeeWorkAbroadRate {
	if x != nil {
		return x.EmployeeWorkAbroadRate
	}
	return nil
}

func (x *Company) GetSalesOverseasRate() *SalesOverseasRate {
	if x != nil {
		return x.SalesOverseasRate
	}
	return nil
}

func (x *Company) GetWelfareBenefit() *WelfareBenefit {
	if x != nil {
		return x.WelfareBenefit
	}
	return nil
}

func (x *Company) GetWelfareAchievement() *WelfareAchievement {
	if x != nil {
		return x.WelfareAchievement
	}
	return nil
}

func (x *Company) GetWelfarePopular() *WelfarePopular {
	if x != nil {
		return x.WelfarePopular
	}
	return nil
}

func (x *Company) GetWelfareOther() *WelfareOther {
	if x != nil {
		return x.WelfareOther
	}
	return nil
}

func (x *Company) GetTrainingSystemExists() *TrainingSystemExists {
	if x != nil {
		return x.TrainingSystemExists
	}
	return nil
}

func (x *Company) GetOther() *Other {
	if x != nil {
		return x.Other
	}
	return nil
}

func (x *Company) GetSideBusiness() *SideBusiness {
	if x != nil {
		return x.SideBusiness
	}
	return nil
}

type Vacations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacations) Reset() {
	*x = Vacations{}
	mi := &file_mv2_user_will_company_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacations) ProtoMessage() {}

func (x *Vacations) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacations.ProtoReflect.Descriptor instead.
func (*Vacations) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{1}
}

func (x *Vacations) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Vacations) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type YearHolidays struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YearHolidays) Reset() {
	*x = YearHolidays{}
	mi := &file_mv2_user_will_company_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YearHolidays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YearHolidays) ProtoMessage() {}

func (x *YearHolidays) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YearHolidays.ProtoReflect.Descriptor instead.
func (*YearHolidays) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{2}
}

func (x *YearHolidays) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *YearHolidays) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type PaidHolidayUseRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaidHolidayUseRate) Reset() {
	*x = PaidHolidayUseRate{}
	mi := &file_mv2_user_will_company_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaidHolidayUseRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaidHolidayUseRate) ProtoMessage() {}

func (x *PaidHolidayUseRate) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaidHolidayUseRate.ProtoReflect.Descriptor instead.
func (*PaidHolidayUseRate) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{3}
}

func (x *PaidHolidayUseRate) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *PaidHolidayUseRate) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type JobRotationExists struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRotationExists) Reset() {
	*x = JobRotationExists{}
	mi := &file_mv2_user_will_company_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRotationExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRotationExists) ProtoMessage() {}

func (x *JobRotationExists) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRotationExists.ProtoReflect.Descriptor instead.
func (*JobRotationExists) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{4}
}

func (x *JobRotationExists) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *JobRotationExists) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type ChangeDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeDepartmentRequest) Reset() {
	*x = ChangeDepartmentRequest{}
	mi := &file_mv2_user_will_company_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDepartmentRequest) ProtoMessage() {}

func (x *ChangeDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDepartmentRequest.ProtoReflect.Descriptor instead.
func (*ChangeDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeDepartmentRequest) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *ChangeDepartmentRequest) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type HREvaluationSpecialSystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HREvaluationSpecialSystem) Reset() {
	*x = HREvaluationSpecialSystem{}
	mi := &file_mv2_user_will_company_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HREvaluationSpecialSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HREvaluationSpecialSystem) ProtoMessage() {}

func (x *HREvaluationSpecialSystem) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HREvaluationSpecialSystem.ProtoReflect.Descriptor instead.
func (*HREvaluationSpecialSystem) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{6}
}

func (x *HREvaluationSpecialSystem) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *HREvaluationSpecialSystem) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SpecialistCareerPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecialistCareerPath) Reset() {
	*x = SpecialistCareerPath{}
	mi := &file_mv2_user_will_company_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecialistCareerPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecialistCareerPath) ProtoMessage() {}

func (x *SpecialistCareerPath) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecialistCareerPath.ProtoReflect.Descriptor instead.
func (*SpecialistCareerPath) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{7}
}

func (x *SpecialistCareerPath) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *SpecialistCareerPath) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type HREvaluationWomanManagerRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HREvaluationWomanManagerRate) Reset() {
	*x = HREvaluationWomanManagerRate{}
	mi := &file_mv2_user_will_company_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HREvaluationWomanManagerRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HREvaluationWomanManagerRate) ProtoMessage() {}

func (x *HREvaluationWomanManagerRate) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HREvaluationWomanManagerRate.ProtoReflect.Descriptor instead.
func (*HREvaluationWomanManagerRate) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{8}
}

func (x *HREvaluationWomanManagerRate) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *HREvaluationWomanManagerRate) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type HREvaluation20SManagerRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HREvaluation20SManagerRate) Reset() {
	*x = HREvaluation20SManagerRate{}
	mi := &file_mv2_user_will_company_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HREvaluation20SManagerRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HREvaluation20SManagerRate) ProtoMessage() {}

func (x *HREvaluation20SManagerRate) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HREvaluation20SManagerRate.ProtoReflect.Descriptor instead.
func (*HREvaluation20SManagerRate) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{9}
}

func (x *HREvaluation20SManagerRate) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *HREvaluation20SManagerRate) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type ProfitCompany struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfitCompany) Reset() {
	*x = ProfitCompany{}
	mi := &file_mv2_user_will_company_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfitCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfitCompany) ProtoMessage() {}

func (x *ProfitCompany) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfitCompany.ProtoReflect.Descriptor instead.
func (*ProfitCompany) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{10}
}

func (x *ProfitCompany) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *ProfitCompany) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type AddressPrefecture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressPrefecture) Reset() {
	*x = AddressPrefecture{}
	mi := &file_mv2_user_will_company_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressPrefecture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressPrefecture) ProtoMessage() {}

func (x *AddressPrefecture) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressPrefecture.ProtoReflect.Descriptor instead.
func (*AddressPrefecture) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{11}
}

func (x *AddressPrefecture) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *AddressPrefecture) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type EmployeeQty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeQty) Reset() {
	*x = EmployeeQty{}
	mi := &file_mv2_user_will_company_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeQty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeQty) ProtoMessage() {}

func (x *EmployeeQty) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeQty.ProtoReflect.Descriptor instead.
func (*EmployeeQty) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{12}
}

func (x *EmployeeQty) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *EmployeeQty) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type EstablishmentYear struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstablishmentYear) Reset() {
	*x = EstablishmentYear{}
	mi := &file_mv2_user_will_company_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstablishmentYear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishmentYear) ProtoMessage() {}

func (x *EstablishmentYear) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishmentYear.ProtoReflect.Descriptor instead.
func (*EstablishmentYear) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{13}
}

func (x *EstablishmentYear) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *EstablishmentYear) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type CapitalType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapitalType) Reset() {
	*x = CapitalType{}
	mi := &file_mv2_user_will_company_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapitalType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapitalType) ProtoMessage() {}

func (x *CapitalType) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapitalType.ProtoReflect.Descriptor instead.
func (*CapitalType) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{14}
}

func (x *CapitalType) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *CapitalType) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SalesScale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalesScale) Reset() {
	*x = SalesScale{}
	mi := &file_mv2_user_will_company_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesScale) ProtoMessage() {}

func (x *SalesScale) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesScale.ProtoReflect.Descriptor instead.
func (*SalesScale) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{15}
}

func (x *SalesScale) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *SalesScale) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type AppealPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppealPoint) Reset() {
	*x = AppealPoint{}
	mi := &file_mv2_user_will_company_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppealPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppealPoint) ProtoMessage() {}

func (x *AppealPoint) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppealPoint.ProtoReflect.Descriptor instead.
func (*AppealPoint) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{16}
}

func (x *AppealPoint) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *AppealPoint) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type EmployeeWorkAbroadRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeWorkAbroadRate) Reset() {
	*x = EmployeeWorkAbroadRate{}
	mi := &file_mv2_user_will_company_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeWorkAbroadRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeWorkAbroadRate) ProtoMessage() {}

func (x *EmployeeWorkAbroadRate) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeWorkAbroadRate.ProtoReflect.Descriptor instead.
func (*EmployeeWorkAbroadRate) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{17}
}

func (x *EmployeeWorkAbroadRate) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *EmployeeWorkAbroadRate) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SalesOverseasRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalesOverseasRate) Reset() {
	*x = SalesOverseasRate{}
	mi := &file_mv2_user_will_company_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalesOverseasRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalesOverseasRate) ProtoMessage() {}

func (x *SalesOverseasRate) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalesOverseasRate.ProtoReflect.Descriptor instead.
func (*SalesOverseasRate) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{18}
}

func (x *SalesOverseasRate) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *SalesOverseasRate) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type WelfareBenefit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelfareBenefit) Reset() {
	*x = WelfareBenefit{}
	mi := &file_mv2_user_will_company_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelfareBenefit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelfareBenefit) ProtoMessage() {}

func (x *WelfareBenefit) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelfareBenefit.ProtoReflect.Descriptor instead.
func (*WelfareBenefit) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{19}
}

func (x *WelfareBenefit) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *WelfareBenefit) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type WelfareAchievement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelfareAchievement) Reset() {
	*x = WelfareAchievement{}
	mi := &file_mv2_user_will_company_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelfareAchievement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelfareAchievement) ProtoMessage() {}

func (x *WelfareAchievement) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelfareAchievement.ProtoReflect.Descriptor instead.
func (*WelfareAchievement) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{20}
}

func (x *WelfareAchievement) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *WelfareAchievement) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type WelfarePopular struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelfarePopular) Reset() {
	*x = WelfarePopular{}
	mi := &file_mv2_user_will_company_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelfarePopular) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelfarePopular) ProtoMessage() {}

func (x *WelfarePopular) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelfarePopular.ProtoReflect.Descriptor instead.
func (*WelfarePopular) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{21}
}

func (x *WelfarePopular) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *WelfarePopular) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type WelfareOther struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelfareOther) Reset() {
	*x = WelfareOther{}
	mi := &file_mv2_user_will_company_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelfareOther) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelfareOther) ProtoMessage() {}

func (x *WelfareOther) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelfareOther.ProtoReflect.Descriptor instead.
func (*WelfareOther) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{22}
}

func (x *WelfareOther) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *WelfareOther) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type TrainingSystemExists struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainingSystemExists) Reset() {
	*x = TrainingSystemExists{}
	mi := &file_mv2_user_will_company_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingSystemExists) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingSystemExists) ProtoMessage() {}

func (x *TrainingSystemExists) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingSystemExists.ProtoReflect.Descriptor instead.
func (*TrainingSystemExists) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{23}
}

func (x *TrainingSystemExists) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *TrainingSystemExists) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type Other struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Other) Reset() {
	*x = Other{}
	mi := &file_mv2_user_will_company_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Other) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Other) ProtoMessage() {}

func (x *Other) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Other.ProtoReflect.Descriptor instead.
func (*Other) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{24}
}

func (x *Other) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *Other) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type SideBusiness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Importance    int32                  `protobuf:"varint,1,opt,name=importance" json:"importance,omitempty"`
	Value         []int32                `protobuf:"varint,2,rep,packed,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SideBusiness) Reset() {
	*x = SideBusiness{}
	mi := &file_mv2_user_will_company_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SideBusiness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SideBusiness) ProtoMessage() {}

func (x *SideBusiness) ProtoReflect() protoreflect.Message {
	mi := &file_mv2_user_will_company_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SideBusiness.ProtoReflect.Descriptor instead.
func (*SideBusiness) Descriptor() ([]byte, []int) {
	return file_mv2_user_will_company_proto_rawDescGZIP(), []int{25}
}

func (x *SideBusiness) GetImportance() int32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *SideBusiness) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_mv2_user_will_company_proto protoreflect.FileDescriptor

const file_mv2_user_will_company_proto_rawDesc = "" +
	"\n" +
	"\x1bmv2_user_will_company.proto\x12\x17miidas.user.marketvalue\"\x8e\x11\n" +
	"\aCompany\x12@\n" +
	"\tvacations\x18\x01 \x01(\v2\".miidas.user.marketvalue.VacationsR\tvacations\x12I\n" +
	"\fyearHolidays\x18\x02 \x01(\v2%.miidas.user.marketvalue.YearHolidaysR\fyearHolidays\x12[\n" +
	"\x12paidHolidayUseRate\x18\x03 \x01(\v2+.miidas.user.marketvalue.PaidHolidayUseRateR\x12paidHolidayUseRate\x12X\n" +
	"\x11jobRotationExists\x18\x04 \x01(\v2*.miidas.user.marketvalue.JobRotationExistsR\x11jobRotationExists\x12j\n" +
	"\x17changeDepartmentRequest\x18\x05 \x01(\v20.miidas.user.marketvalue.ChangeDepartmentRequestR\x17changeDepartmentRequest\x12p\n" +
	"\x19HREvaluationSpecialSystem\x18\x06 \x01(\v22.miidas.user.marketvalue.HREvaluationSpecialSystemR\x19HREvaluationSpecialSystem\x12a\n" +
	"\x14SpecialistCareerPath\x18\a \x01(\v2-.miidas.user.marketvalue.SpecialistCareerPathR\x14SpecialistCareerPath\x12y\n" +
	"\x1cHREvaluationWomanManagerRate\x18\b \x01(\v25.miidas.user.marketvalue.HREvaluationWomanManagerRateR\x1cHREvaluationWomanManagerRate\x12s\n" +
	"\x1aHREvaluation20SManagerRate\x18\t \x01(\v23.miidas.user.marketvalue.HREvaluation20SManagerRateR\x1aHREvaluation20SManagerRate\x12L\n" +
	"\rProfitCompany\x18\n" +
	" \x01(\v2&.miidas.user.marketvalue.ProfitCompanyR\rProfitCompany\x12X\n" +
	"\x11AddressPrefecture\x18\v \x01(\v2*.miidas.user.marketvalue.AddressPrefectureR\x11AddressPrefecture\x12F\n" +
	"\vEmployeeQty\x18\f \x01(\v2$.miidas.user.marketvalue.EmployeeQtyR\vEmployeeQty\x12X\n" +
	"\x11EstablishmentYear\x18\r \x01(\v2*.miidas.user.marketvalue.EstablishmentYearR\x11EstablishmentYear\x12F\n" +
	"\vCapitalType\x18\x0e \x01(\v2$.miidas.user.marketvalue.CapitalTypeR\vCapitalType\x12C\n" +
	"\n" +
	"SalesScale\x18\x0f \x01(\v2#.miidas.user.marketvalue.SalesScaleR\n" +
	"SalesScale\x12F\n" +
	"\vAppealPoint\x18\x10 \x01(\v2$.miidas.user.marketvalue.AppealPointR\vAppealPoint\x12g\n" +
	"\x16EmployeeWorkAbroadRate\x18\x11 \x01(\v2/.miidas.user.marketvalue.EmployeeWorkAbroadRateR\x16EmployeeWorkAbroadRate\x12X\n" +
	"\x11SalesOverseasRate\x18\x12 \x01(\v2*.miidas.user.marketvalue.SalesOverseasRateR\x11SalesOverseasRate\x12O\n" +
	"\x0eWelfareBenefit\x18\x13 \x01(\v2'.miidas.user.marketvalue.WelfareBenefitR\x0eWelfareBenefit\x12[\n" +
	"\x12WelfareAchievement\x18\x14 \x01(\v2+.miidas.user.marketvalue.WelfareAchievementR\x12WelfareAchievement\x12O\n" +
	"\x0eWelfarePopular\x18\x15 \x01(\v2'.miidas.user.marketvalue.WelfarePopularR\x0eWelfarePopular\x12I\n" +
	"\fWelfareOther\x18\x16 \x01(\v2%.miidas.user.marketvalue.WelfareOtherR\fWelfareOther\x12a\n" +
	"\x14TrainingSystemExists\x18\x17 \x01(\v2-.miidas.user.marketvalue.TrainingSystemExistsR\x14TrainingSystemExists\x124\n" +
	"\x05Other\x18\x18 \x01(\v2\x1e.miidas.user.marketvalue.OtherR\x05Other\x12I\n" +
	"\fSideBusiness\x18\x19 \x01(\v2%.miidas.user.marketvalue.SideBusinessR\fSideBusiness\"A\n" +
	"\tVacations\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"K\n" +
	"\fYearHolidays\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05value\"J\n" +
	"\x12PaidHolidayUseRate\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"P\n" +
	"\x11JobRotationExists\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05value\"V\n" +
	"\x17ChangeDepartmentRequest\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05value\"Q\n" +
	"\x19HREvaluationSpecialSystem\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"L\n" +
	"\x14SpecialistCareerPath\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"T\n" +
	"\x1cHREvaluationWomanManagerRate\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"R\n" +
	"\x1aHREvaluation20SManagerRate\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"L\n" +
	"\rProfitCompany\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05value\"I\n" +
	"\x11AddressPrefecture\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"C\n" +
	"\vEmployeeQty\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"I\n" +
	"\x11EstablishmentYear\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"C\n" +
	"\vCapitalType\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"B\n" +
	"\n" +
	"SalesScale\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"C\n" +
	"\vAppealPoint\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"N\n" +
	"\x16EmployeeWorkAbroadRate\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"I\n" +
	"\x11SalesOverseasRate\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"F\n" +
	"\x0eWelfareBenefit\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"J\n" +
	"\x12WelfareAchievement\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"F\n" +
	"\x0eWelfarePopular\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"D\n" +
	"\fWelfareOther\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"S\n" +
	"\x14TrainingSystemExists\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x01R\x05value\"=\n" +
	"\x05Other\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05value\"D\n" +
	"\fSideBusiness\x12\x1e\n" +
	"\n" +
	"importance\x18\x01 \x01(\x05R\n" +
	"importance\x12\x14\n" +
	"\x05value\x18\x02 \x03(\x05R\x05valueB,Z%miidas/m2/user/marketvalue/grpc/iface\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_mv2_user_will_company_proto_rawDescOnce sync.Once
	file_mv2_user_will_company_proto_rawDescData []byte
)

func file_mv2_user_will_company_proto_rawDescGZIP() []byte {
	file_mv2_user_will_company_proto_rawDescOnce.Do(func() {
		file_mv2_user_will_company_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mv2_user_will_company_proto_rawDesc), len(file_mv2_user_will_company_proto_rawDesc)))
	})
	return file_mv2_user_will_company_proto_rawDescData
}

var file_mv2_user_will_company_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_mv2_user_will_company_proto_goTypes = []any{
	(*Company)(nil),                      // 0: miidas.user.marketvalue.Company
	(*Vacations)(nil),                    // 1: miidas.user.marketvalue.Vacations
	(*YearHolidays)(nil),                 // 2: miidas.user.marketvalue.YearHolidays
	(*PaidHolidayUseRate)(nil),           // 3: miidas.user.marketvalue.PaidHolidayUseRate
	(*JobRotationExists)(nil),            // 4: miidas.user.marketvalue.JobRotationExists
	(*ChangeDepartmentRequest)(nil),      // 5: miidas.user.marketvalue.ChangeDepartmentRequest
	(*HREvaluationSpecialSystem)(nil),    // 6: miidas.user.marketvalue.HREvaluationSpecialSystem
	(*SpecialistCareerPath)(nil),         // 7: miidas.user.marketvalue.SpecialistCareerPath
	(*HREvaluationWomanManagerRate)(nil), // 8: miidas.user.marketvalue.HREvaluationWomanManagerRate
	(*HREvaluation20SManagerRate)(nil),   // 9: miidas.user.marketvalue.HREvaluation20SManagerRate
	(*ProfitCompany)(nil),                // 10: miidas.user.marketvalue.ProfitCompany
	(*AddressPrefecture)(nil),            // 11: miidas.user.marketvalue.AddressPrefecture
	(*EmployeeQty)(nil),                  // 12: miidas.user.marketvalue.EmployeeQty
	(*EstablishmentYear)(nil),            // 13: miidas.user.marketvalue.EstablishmentYear
	(*CapitalType)(nil),                  // 14: miidas.user.marketvalue.CapitalType
	(*SalesScale)(nil),                   // 15: miidas.user.marketvalue.SalesScale
	(*AppealPoint)(nil),                  // 16: miidas.user.marketvalue.AppealPoint
	(*EmployeeWorkAbroadRate)(nil),       // 17: miidas.user.marketvalue.EmployeeWorkAbroadRate
	(*SalesOverseasRate)(nil),            // 18: miidas.user.marketvalue.SalesOverseasRate
	(*WelfareBenefit)(nil),               // 19: miidas.user.marketvalue.WelfareBenefit
	(*WelfareAchievement)(nil),           // 20: miidas.user.marketvalue.WelfareAchievement
	(*WelfarePopular)(nil),               // 21: miidas.user.marketvalue.WelfarePopular
	(*WelfareOther)(nil),                 // 22: miidas.user.marketvalue.WelfareOther
	(*TrainingSystemExists)(nil),         // 23: miidas.user.marketvalue.TrainingSystemExists
	(*Other)(nil),                        // 24: miidas.user.marketvalue.Other
	(*SideBusiness)(nil),                 // 25: miidas.user.marketvalue.SideBusiness
}
var file_mv2_user_will_company_proto_depIdxs = []int32{
	1,  // 0: miidas.user.marketvalue.Company.vacations:type_name -> miidas.user.marketvalue.Vacations
	2,  // 1: miidas.user.marketvalue.Company.yearHolidays:type_name -> miidas.user.marketvalue.YearHolidays
	3,  // 2: miidas.user.marketvalue.Company.paidHolidayUseRate:type_name -> miidas.user.marketvalue.PaidHolidayUseRate
	4,  // 3: miidas.user.marketvalue.Company.jobRotationExists:type_name -> miidas.user.marketvalue.JobRotationExists
	5,  // 4: miidas.user.marketvalue.Company.changeDepartmentRequest:type_name -> miidas.user.marketvalue.ChangeDepartmentRequest
	6,  // 5: miidas.user.marketvalue.Company.HREvaluationSpecialSystem:type_name -> miidas.user.marketvalue.HREvaluationSpecialSystem
	7,  // 6: miidas.user.marketvalue.Company.SpecialistCareerPath:type_name -> miidas.user.marketvalue.SpecialistCareerPath
	8,  // 7: miidas.user.marketvalue.Company.HREvaluationWomanManagerRate:type_name -> miidas.user.marketvalue.HREvaluationWomanManagerRate
	9,  // 8: miidas.user.marketvalue.Company.HREvaluation20SManagerRate:type_name -> miidas.user.marketvalue.HREvaluation20SManagerRate
	10, // 9: miidas.user.marketvalue.Company.ProfitCompany:type_name -> miidas.user.marketvalue.ProfitCompany
	11, // 10: miidas.user.marketvalue.Company.AddressPrefecture:type_name -> miidas.user.marketvalue.AddressPrefecture
	12, // 11: miidas.user.marketvalue.Company.EmployeeQty:type_name -> miidas.user.marketvalue.EmployeeQty
	13, // 12: miidas.user.marketvalue.Company.EstablishmentYear:type_name -> miidas.user.marketvalue.EstablishmentYear
	14, // 13: miidas.user.marketvalue.Company.CapitalType:type_name -> miidas.user.marketvalue.CapitalType
	15, // 14: miidas.user.marketvalue.Company.SalesScale:type_name -> miidas.user.marketvalue.SalesScale
	16, // 15: miidas.user.marketvalue.Company.AppealPoint:type_name -> miidas.user.marketvalue.AppealPoint
	17, // 16: miidas.user.marketvalue.Company.EmployeeWorkAbroadRate:type_name -> miidas.user.marketvalue.EmployeeWorkAbroadRate
	18, // 17: miidas.user.marketvalue.Company.SalesOverseasRate:type_name -> miidas.user.marketvalue.SalesOverseasRate
	19, // 18: miidas.user.marketvalue.Company.WelfareBenefit:type_name -> miidas.user.marketvalue.WelfareBenefit
	20, // 19: miidas.user.marketvalue.Company.WelfareAchievement:type_name -> miidas.user.marketvalue.WelfareAchievement
	21, // 20: miidas.user.marketvalue.Company.WelfarePopular:type_name -> miidas.user.marketvalue.WelfarePopular
	22, // 21: miidas.user.marketvalue.Company.WelfareOther:type_name -> miidas.user.marketvalue.WelfareOther
	23, // 22: miidas.user.marketvalue.Company.TrainingSystemExists:type_name -> miidas.user.marketvalue.TrainingSystemExists
	24, // 23: miidas.user.marketvalue.Company.Other:type_name -> miidas.user.marketvalue.Other
	25, // 24: miidas.user.marketvalue.Company.SideBusiness:type_name -> miidas.user.marketvalue.SideBusiness
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_mv2_user_will_company_proto_init() }
func file_mv2_user_will_company_proto_init() {
	if File_mv2_user_will_company_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mv2_user_will_company_proto_rawDesc), len(file_mv2_user_will_company_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mv2_user_will_company_proto_goTypes,
		DependencyIndexes: file_mv2_user_will_company_proto_depIdxs,
		MessageInfos:      file_mv2_user_will_company_proto_msgTypes,
	}.Build()
	File_mv2_user_will_company_proto = out.File
	file_mv2_user_will_company_proto_goTypes = nil
	file_mv2_user_will_company_proto_depIdxs = nil
}
