// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.35.0
// source: mv2.proto

package iface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	business "miidas/m2/user/marketvalue/grpc/iface/business"
	company "miidas/m2/user/marketvalue/grpc/iface/company"
	position "miidas/m2/user/marketvalue/grpc/iface/position"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketValue_GetMenkakuOutsourcingPositionIDsByUserInfo_FullMethodName = "/miidas.user.marketvalue.MarketValue/GetMenkakuOutsourcingPositionIDsByUserInfo"
	MarketValue_GetInterimValue_FullMethodName                            = "/miidas.user.marketvalue.MarketValue/GetInterimValue"
	MarketValue_GetMarketValueResult_FullMethodName                       = "/miidas.user.marketvalue.MarketValue/GetMarketValueResult"
	MarketValue_GetOutsourcingPositionList_FullMethodName                 = "/miidas.user.marketvalue.MarketValue/GetOutsourcingPositionList"
	MarketValue_GetMultiJobChangePositionDetailStream_FullMethodName      = "/miidas.user.marketvalue.MarketValue/GetMultiJobChangePositionDetailStream"
	MarketValue_GetMultiOutsourcingPositionDetailStream_FullMethodName    = "/miidas.user.marketvalue.MarketValue/GetMultiOutsourcingPositionDetailStream"
	MarketValue_GetJobChangePositionDetail_FullMethodName                 = "/miidas.user.marketvalue.MarketValue/GetJobChangePositionDetail"
	MarketValue_GetOutsourcingPositionDetail_FullMethodName               = "/miidas.user.marketvalue.MarketValue/GetOutsourcingPositionDetail"
	MarketValue_GetActionedPositionList_FullMethodName                    = "/miidas.user.marketvalue.MarketValue/GetActionedPositionList"
	MarketValue_GetWillPositionList_FullMethodName                        = "/miidas.user.marketvalue.MarketValue/GetWillPositionList"
	MarketValue_GetExpandWillPositionList_FullMethodName                  = "/miidas.user.marketvalue.MarketValue/GetExpandWillPositionList"
	MarketValue_GetThemePositionList_FullMethodName                       = "/miidas.user.marketvalue.MarketValue/GetThemePositionList"
	MarketValue_GetStarCollaborativePositionList_FullMethodName           = "/miidas.user.marketvalue.MarketValue/GetStarCollaborativePositionList"
	MarketValue_GetCompanies_FullMethodName                               = "/miidas.user.marketvalue.MarketValue/GetCompanies"
	MarketValue_GetBusinesses_FullMethodName                              = "/miidas.user.marketvalue.MarketValue/GetBusinesses"
	MarketValue_GetPositions_FullMethodName                               = "/miidas.user.marketvalue.MarketValue/GetPositions"
	MarketValue_GetWillMatchPosition_FullMethodName                       = "/miidas.user.marketvalue.MarketValue/GetWillMatchPosition"
)

// MarketValueClient is the client API for MarketValue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketValueClient interface {
	GetMenkakuOutsourcingPositionIDsByUserInfo(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*PositionIDs, error)
	GetInterimValue(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*InterimValue, error)
	GetMarketValueResult(ctx context.Context, in *MarketValueRequest, opts ...grpc.CallOption) (*MarketValueResult, error)
	// ポジション一覧取得系
	GetOutsourcingPositionList(ctx context.Context, in *PositionListRequest, opts ...grpc.CallOption) (*PositionListResponse, error)
	// ポジション詳細複数取得系(stream)
	GetMultiJobChangePositionDetailStream(ctx context.Context, in *PositionMultiDetailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MultiPositionDetailResponseStream], error)
	GetMultiOutsourcingPositionDetailStream(ctx context.Context, in *PositionMultiDetailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MultiOutsourcingPositionDetailResponseStream], error)
	// ポジション詳細取得
	GetJobChangePositionDetail(ctx context.Context, in *PositionDetailRequest, opts ...grpc.CallOption) (*JobChangePositionDetailResponse, error)
	GetOutsourcingPositionDetail(ctx context.Context, in *PositionDetailRequest, opts ...grpc.CallOption) (*OutsourcingPositionDetailResponse, error)
	// アクション済みポジションリスト
	// 希望条件一致度と勤務地の希望条件が完全一致かは判断しない
	GetActionedPositionList(ctx context.Context, in *ActionedPositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error)
	// 希望条件一致ポジションリスト
	GetWillPositionList(ctx context.Context, in *WillPositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error)
	// 拡大希望条件一致ポジションリスト
	GetExpandWillPositionList(ctx context.Context, in *ExpandWillPositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error)
	// テーマポジションリスト
	// テーマの「予め系テーマポジション」データの取得では希望条件一致度と勤務地の希望条件が完全一致かは判断しない
	GetThemePositionList(ctx context.Context, in *ThemePositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error)
	// 気になるに協調するポジションリスト
	// 希望条件一致度と勤務地の希望条件が完全一致かは判断しない
	GetStarCollaborativePositionList(ctx context.Context, in *StarCollaborativePositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error)
	// 企業詳細取得
	GetCompanies(ctx context.Context, in *CompanyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[company.Company], error)
	// 事業詳細取得
	GetBusinesses(ctx context.Context, in *BusinessRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[business.Business], error)
	// ポジション詳細取得
	GetPositions(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[position.Position], error)
	// ポジションマッチング情報取得
	GetWillMatchPosition(ctx context.Context, in *WillMatchPositionRequest, opts ...grpc.CallOption) (*WillMatchPositionResponse, error)
}

type marketValueClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketValueClient(cc grpc.ClientConnInterface) MarketValueClient {
	return &marketValueClient{cc}
}

func (c *marketValueClient) GetMenkakuOutsourcingPositionIDsByUserInfo(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*PositionIDs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionIDs)
	err := c.cc.Invoke(ctx, MarketValue_GetMenkakuOutsourcingPositionIDsByUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketValueClient) GetInterimValue(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*InterimValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterimValue)
	err := c.cc.Invoke(ctx, MarketValue_GetInterimValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketValueClient) GetMarketValueResult(ctx context.Context, in *MarketValueRequest, opts ...grpc.CallOption) (*MarketValueResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketValueResult)
	err := c.cc.Invoke(ctx, MarketValue_GetMarketValueResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketValueClient) GetOutsourcingPositionList(ctx context.Context, in *PositionListRequest, opts ...grpc.CallOption) (*PositionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionListResponse)
	err := c.cc.Invoke(ctx, MarketValue_GetOutsourcingPositionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketValueClient) GetMultiJobChangePositionDetailStream(ctx context.Context, in *PositionMultiDetailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MultiPositionDetailResponseStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[0], MarketValue_GetMultiJobChangePositionDetailStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PositionMultiDetailRequest, MultiPositionDetailResponseStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetMultiJobChangePositionDetailStreamClient = grpc.ServerStreamingClient[MultiPositionDetailResponseStream]

func (c *marketValueClient) GetMultiOutsourcingPositionDetailStream(ctx context.Context, in *PositionMultiDetailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MultiOutsourcingPositionDetailResponseStream], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[1], MarketValue_GetMultiOutsourcingPositionDetailStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PositionMultiDetailRequest, MultiOutsourcingPositionDetailResponseStream]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetMultiOutsourcingPositionDetailStreamClient = grpc.ServerStreamingClient[MultiOutsourcingPositionDetailResponseStream]

func (c *marketValueClient) GetJobChangePositionDetail(ctx context.Context, in *PositionDetailRequest, opts ...grpc.CallOption) (*JobChangePositionDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobChangePositionDetailResponse)
	err := c.cc.Invoke(ctx, MarketValue_GetJobChangePositionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketValueClient) GetOutsourcingPositionDetail(ctx context.Context, in *PositionDetailRequest, opts ...grpc.CallOption) (*OutsourcingPositionDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutsourcingPositionDetailResponse)
	err := c.cc.Invoke(ctx, MarketValue_GetOutsourcingPositionDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketValueClient) GetActionedPositionList(ctx context.Context, in *ActionedPositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[2], MarketValue_GetActionedPositionList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ActionedPositionListRequest, PositionListEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetActionedPositionListClient = grpc.ServerStreamingClient[PositionListEntry]

func (c *marketValueClient) GetWillPositionList(ctx context.Context, in *WillPositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[3], MarketValue_GetWillPositionList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WillPositionListRequest, PositionListEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetWillPositionListClient = grpc.ServerStreamingClient[PositionListEntry]

func (c *marketValueClient) GetExpandWillPositionList(ctx context.Context, in *ExpandWillPositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[4], MarketValue_GetExpandWillPositionList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExpandWillPositionListRequest, PositionListEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetExpandWillPositionListClient = grpc.ServerStreamingClient[PositionListEntry]

func (c *marketValueClient) GetThemePositionList(ctx context.Context, in *ThemePositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[5], MarketValue_GetThemePositionList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ThemePositionListRequest, PositionListEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetThemePositionListClient = grpc.ServerStreamingClient[PositionListEntry]

func (c *marketValueClient) GetStarCollaborativePositionList(ctx context.Context, in *StarCollaborativePositionListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionListEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[6], MarketValue_GetStarCollaborativePositionList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StarCollaborativePositionListRequest, PositionListEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetStarCollaborativePositionListClient = grpc.ServerStreamingClient[PositionListEntry]

func (c *marketValueClient) GetCompanies(ctx context.Context, in *CompanyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[company.Company], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[7], MarketValue_GetCompanies_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CompanyRequest, company.Company]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetCompaniesClient = grpc.ServerStreamingClient[company.Company]

func (c *marketValueClient) GetBusinesses(ctx context.Context, in *BusinessRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[business.Business], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[8], MarketValue_GetBusinesses_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BusinessRequest, business.Business]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetBusinessesClient = grpc.ServerStreamingClient[business.Business]

func (c *marketValueClient) GetPositions(ctx context.Context, in *PositionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[position.Position], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketValue_ServiceDesc.Streams[9], MarketValue_GetPositions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PositionRequest, position.Position]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetPositionsClient = grpc.ServerStreamingClient[position.Position]

func (c *marketValueClient) GetWillMatchPosition(ctx context.Context, in *WillMatchPositionRequest, opts ...grpc.CallOption) (*WillMatchPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WillMatchPositionResponse)
	err := c.cc.Invoke(ctx, MarketValue_GetWillMatchPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketValueServer is the server API for MarketValue service.
// All implementations must embed UnimplementedMarketValueServer
// for forward compatibility.
type MarketValueServer interface {
	GetMenkakuOutsourcingPositionIDsByUserInfo(context.Context, *UserInfo) (*PositionIDs, error)
	GetInterimValue(context.Context, *UserInfo) (*InterimValue, error)
	GetMarketValueResult(context.Context, *MarketValueRequest) (*MarketValueResult, error)
	// ポジション一覧取得系
	GetOutsourcingPositionList(context.Context, *PositionListRequest) (*PositionListResponse, error)
	// ポジション詳細複数取得系(stream)
	GetMultiJobChangePositionDetailStream(*PositionMultiDetailRequest, grpc.ServerStreamingServer[MultiPositionDetailResponseStream]) error
	GetMultiOutsourcingPositionDetailStream(*PositionMultiDetailRequest, grpc.ServerStreamingServer[MultiOutsourcingPositionDetailResponseStream]) error
	// ポジション詳細取得
	GetJobChangePositionDetail(context.Context, *PositionDetailRequest) (*JobChangePositionDetailResponse, error)
	GetOutsourcingPositionDetail(context.Context, *PositionDetailRequest) (*OutsourcingPositionDetailResponse, error)
	// アクション済みポジションリスト
	// 希望条件一致度と勤務地の希望条件が完全一致かは判断しない
	GetActionedPositionList(*ActionedPositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error
	// 希望条件一致ポジションリスト
	GetWillPositionList(*WillPositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error
	// 拡大希望条件一致ポジションリスト
	GetExpandWillPositionList(*ExpandWillPositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error
	// テーマポジションリスト
	// テーマの「予め系テーマポジション」データの取得では希望条件一致度と勤務地の希望条件が完全一致かは判断しない
	GetThemePositionList(*ThemePositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error
	// 気になるに協調するポジションリスト
	// 希望条件一致度と勤務地の希望条件が完全一致かは判断しない
	GetStarCollaborativePositionList(*StarCollaborativePositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error
	// 企業詳細取得
	GetCompanies(*CompanyRequest, grpc.ServerStreamingServer[company.Company]) error
	// 事業詳細取得
	GetBusinesses(*BusinessRequest, grpc.ServerStreamingServer[business.Business]) error
	// ポジション詳細取得
	GetPositions(*PositionRequest, grpc.ServerStreamingServer[position.Position]) error
	// ポジションマッチング情報取得
	GetWillMatchPosition(context.Context, *WillMatchPositionRequest) (*WillMatchPositionResponse, error)
	mustEmbedUnimplementedMarketValueServer()
}

// UnimplementedMarketValueServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketValueServer struct{}

func (UnimplementedMarketValueServer) GetMenkakuOutsourcingPositionIDsByUserInfo(context.Context, *UserInfo) (*PositionIDs, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMenkakuOutsourcingPositionIDsByUserInfo not implemented")
}
func (UnimplementedMarketValueServer) GetInterimValue(context.Context, *UserInfo) (*InterimValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInterimValue not implemented")
}
func (UnimplementedMarketValueServer) GetMarketValueResult(context.Context, *MarketValueRequest) (*MarketValueResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketValueResult not implemented")
}
func (UnimplementedMarketValueServer) GetOutsourcingPositionList(context.Context, *PositionListRequest) (*PositionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOutsourcingPositionList not implemented")
}
func (UnimplementedMarketValueServer) GetMultiJobChangePositionDetailStream(*PositionMultiDetailRequest, grpc.ServerStreamingServer[MultiPositionDetailResponseStream]) error {
	return status.Error(codes.Unimplemented, "method GetMultiJobChangePositionDetailStream not implemented")
}
func (UnimplementedMarketValueServer) GetMultiOutsourcingPositionDetailStream(*PositionMultiDetailRequest, grpc.ServerStreamingServer[MultiOutsourcingPositionDetailResponseStream]) error {
	return status.Error(codes.Unimplemented, "method GetMultiOutsourcingPositionDetailStream not implemented")
}
func (UnimplementedMarketValueServer) GetJobChangePositionDetail(context.Context, *PositionDetailRequest) (*JobChangePositionDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobChangePositionDetail not implemented")
}
func (UnimplementedMarketValueServer) GetOutsourcingPositionDetail(context.Context, *PositionDetailRequest) (*OutsourcingPositionDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOutsourcingPositionDetail not implemented")
}
func (UnimplementedMarketValueServer) GetActionedPositionList(*ActionedPositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error {
	return status.Error(codes.Unimplemented, "method GetActionedPositionList not implemented")
}
func (UnimplementedMarketValueServer) GetWillPositionList(*WillPositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error {
	return status.Error(codes.Unimplemented, "method GetWillPositionList not implemented")
}
func (UnimplementedMarketValueServer) GetExpandWillPositionList(*ExpandWillPositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error {
	return status.Error(codes.Unimplemented, "method GetExpandWillPositionList not implemented")
}
func (UnimplementedMarketValueServer) GetThemePositionList(*ThemePositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error {
	return status.Error(codes.Unimplemented, "method GetThemePositionList not implemented")
}
func (UnimplementedMarketValueServer) GetStarCollaborativePositionList(*StarCollaborativePositionListRequest, grpc.ServerStreamingServer[PositionListEntry]) error {
	return status.Error(codes.Unimplemented, "method GetStarCollaborativePositionList not implemented")
}
func (UnimplementedMarketValueServer) GetCompanies(*CompanyRequest, grpc.ServerStreamingServer[company.Company]) error {
	return status.Error(codes.Unimplemented, "method GetCompanies not implemented")
}
func (UnimplementedMarketValueServer) GetBusinesses(*BusinessRequest, grpc.ServerStreamingServer[business.Business]) error {
	return status.Error(codes.Unimplemented, "method GetBusinesses not implemented")
}
func (UnimplementedMarketValueServer) GetPositions(*PositionRequest, grpc.ServerStreamingServer[position.Position]) error {
	return status.Error(codes.Unimplemented, "method GetPositions not implemented")
}
func (UnimplementedMarketValueServer) GetWillMatchPosition(context.Context, *WillMatchPositionRequest) (*WillMatchPositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWillMatchPosition not implemented")
}
func (UnimplementedMarketValueServer) mustEmbedUnimplementedMarketValueServer() {}
func (UnimplementedMarketValueServer) testEmbeddedByValue()                     {}

// UnsafeMarketValueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketValueServer will
// result in compilation errors.
type UnsafeMarketValueServer interface {
	mustEmbedUnimplementedMarketValueServer()
}

func RegisterMarketValueServer(s grpc.ServiceRegistrar, srv MarketValueServer) {
	// If the following call panics, it indicates UnimplementedMarketValueServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketValue_ServiceDesc, srv)
}

func _MarketValue_GetMenkakuOutsourcingPositionIDsByUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketValueServer).GetMenkakuOutsourcingPositionIDsByUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketValue_GetMenkakuOutsourcingPositionIDsByUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketValueServer).GetMenkakuOutsourcingPositionIDsByUserInfo(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketValue_GetInterimValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketValueServer).GetInterimValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketValue_GetInterimValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketValueServer).GetInterimValue(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketValue_GetMarketValueResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketValueServer).GetMarketValueResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketValue_GetMarketValueResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketValueServer).GetMarketValueResult(ctx, req.(*MarketValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketValue_GetOutsourcingPositionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketValueServer).GetOutsourcingPositionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketValue_GetOutsourcingPositionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketValueServer).GetOutsourcingPositionList(ctx, req.(*PositionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketValue_GetMultiJobChangePositionDetailStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PositionMultiDetailRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetMultiJobChangePositionDetailStream(m, &grpc.GenericServerStream[PositionMultiDetailRequest, MultiPositionDetailResponseStream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetMultiJobChangePositionDetailStreamServer = grpc.ServerStreamingServer[MultiPositionDetailResponseStream]

func _MarketValue_GetMultiOutsourcingPositionDetailStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PositionMultiDetailRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetMultiOutsourcingPositionDetailStream(m, &grpc.GenericServerStream[PositionMultiDetailRequest, MultiOutsourcingPositionDetailResponseStream]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetMultiOutsourcingPositionDetailStreamServer = grpc.ServerStreamingServer[MultiOutsourcingPositionDetailResponseStream]

func _MarketValue_GetJobChangePositionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketValueServer).GetJobChangePositionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketValue_GetJobChangePositionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketValueServer).GetJobChangePositionDetail(ctx, req.(*PositionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketValue_GetOutsourcingPositionDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketValueServer).GetOutsourcingPositionDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketValue_GetOutsourcingPositionDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketValueServer).GetOutsourcingPositionDetail(ctx, req.(*PositionDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketValue_GetActionedPositionList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ActionedPositionListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetActionedPositionList(m, &grpc.GenericServerStream[ActionedPositionListRequest, PositionListEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetActionedPositionListServer = grpc.ServerStreamingServer[PositionListEntry]

func _MarketValue_GetWillPositionList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WillPositionListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetWillPositionList(m, &grpc.GenericServerStream[WillPositionListRequest, PositionListEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetWillPositionListServer = grpc.ServerStreamingServer[PositionListEntry]

func _MarketValue_GetExpandWillPositionList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExpandWillPositionListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetExpandWillPositionList(m, &grpc.GenericServerStream[ExpandWillPositionListRequest, PositionListEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetExpandWillPositionListServer = grpc.ServerStreamingServer[PositionListEntry]

func _MarketValue_GetThemePositionList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ThemePositionListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetThemePositionList(m, &grpc.GenericServerStream[ThemePositionListRequest, PositionListEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetThemePositionListServer = grpc.ServerStreamingServer[PositionListEntry]

func _MarketValue_GetStarCollaborativePositionList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StarCollaborativePositionListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetStarCollaborativePositionList(m, &grpc.GenericServerStream[StarCollaborativePositionListRequest, PositionListEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetStarCollaborativePositionListServer = grpc.ServerStreamingServer[PositionListEntry]

func _MarketValue_GetCompanies_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CompanyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetCompanies(m, &grpc.GenericServerStream[CompanyRequest, company.Company]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetCompaniesServer = grpc.ServerStreamingServer[company.Company]

func _MarketValue_GetBusinesses_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BusinessRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetBusinesses(m, &grpc.GenericServerStream[BusinessRequest, business.Business]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetBusinessesServer = grpc.ServerStreamingServer[business.Business]

func _MarketValue_GetPositions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketValueServer).GetPositions(m, &grpc.GenericServerStream[PositionRequest, position.Position]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketValue_GetPositionsServer = grpc.ServerStreamingServer[position.Position]

func _MarketValue_GetWillMatchPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WillMatchPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketValueServer).GetWillMatchPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketValue_GetWillMatchPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketValueServer).GetWillMatchPosition(ctx, req.(*WillMatchPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketValue_ServiceDesc is the grpc.ServiceDesc for MarketValue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketValue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "miidas.user.marketvalue.MarketValue",
	HandlerType: (*MarketValueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenkakuOutsourcingPositionIDsByUserInfo",
			Handler:    _MarketValue_GetMenkakuOutsourcingPositionIDsByUserInfo_Handler,
		},
		{
			MethodName: "GetInterimValue",
			Handler:    _MarketValue_GetInterimValue_Handler,
		},
		{
			MethodName: "GetMarketValueResult",
			Handler:    _MarketValue_GetMarketValueResult_Handler,
		},
		{
			MethodName: "GetOutsourcingPositionList",
			Handler:    _MarketValue_GetOutsourcingPositionList_Handler,
		},
		{
			MethodName: "GetJobChangePositionDetail",
			Handler:    _MarketValue_GetJobChangePositionDetail_Handler,
		},
		{
			MethodName: "GetOutsourcingPositionDetail",
			Handler:    _MarketValue_GetOutsourcingPositionDetail_Handler,
		},
		{
			MethodName: "GetWillMatchPosition",
			Handler:    _MarketValue_GetWillMatchPosition_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMultiJobChangePositionDetailStream",
			Handler:       _MarketValue_GetMultiJobChangePositionDetailStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetMultiOutsourcingPositionDetailStream",
			Handler:       _MarketValue_GetMultiOutsourcingPositionDetailStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetActionedPositionList",
			Handler:       _MarketValue_GetActionedPositionList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetWillPositionList",
			Handler:       _MarketValue_GetWillPositionList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetExpandWillPositionList",
			Handler:       _MarketValue_GetExpandWillPositionList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetThemePositionList",
			Handler:       _MarketValue_GetThemePositionList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStarCollaborativePositionList",
			Handler:       _MarketValue_GetStarCollaborativePositionList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCompanies",
			Handler:       _MarketValue_GetCompanies_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBusinesses",
			Handler:       _MarketValue_GetBusinesses_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPositions",
			Handler:       _MarketValue_GetPositions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mv2.proto",
}
