// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: business/business.proto

package business

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "miidas/m2/user/marketvalue/grpc/iface/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Business struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CompanyId      int32                  `protobuf:"varint,2,opt,name=company_id,json=companyId" json:"company_id,omitempty"`
	Detail         *Detail                `protobuf:"bytes,3,opt,name=detail" json:"detail,omitempty"`
	LastModifiedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_modified_at,json=lastModifiedAt" json:"last_modified_at,omitempty"`
	ImportedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=imported_at,json=importedAt" json:"imported_at,omitempty"`
	TrashedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=trashed_at,json=trashedAt" json:"trashed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Business) Reset() {
	*x = Business{}
	mi := &file_business_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Business) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Business) ProtoMessage() {}

func (x *Business) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Business.ProtoReflect.Descriptor instead.
func (*Business) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{0}
}

func (x *Business) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Business) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *Business) GetDetail() *Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Business) GetLastModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedAt
	}
	return nil
}

func (x *Business) GetImportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ImportedAt
	}
	return nil
}

func (x *Business) GetTrashedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TrashedAt
	}
	return nil
}

type Detail struct {
	state                          protoimpl.MessageState    `protogen:"open.v1"`
	Name                           string                    `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	EmployeeQty                    *common.ValueText         `protobuf:"bytes,2,opt,name=employee_qty,json=employeeQty" json:"employee_qty,omitempty"`
	EstablishmentYear              *common.ValueText         `protobuf:"bytes,3,opt,name=establishment_year,json=establishmentYear" json:"establishment_year,omitempty"`
	SalesScale                     *common.ValueText         `protobuf:"bytes,4,opt,name=sales_scale,json=salesScale" json:"sales_scale,omitempty"`
	Industries                     *Detail_Industries        `protobuf:"bytes,5,opt,name=industries" json:"industries,omitempty"`
	Stage                          *common.ValueText         `protobuf:"bytes,6,opt,name=stage" json:"stage,omitempty"`
	Product                        *Detail_Product           `protobuf:"bytes,7,opt,name=product" json:"product,omitempty"`
	TargetCustomer                 *Detail_TargetCustomer    `protobuf:"bytes,8,opt,name=target_customer,json=targetCustomer" json:"target_customer,omitempty"`
	TrendKeyword                   *common.ValuesText        `protobuf:"bytes,9,opt,name=trend_keyword,json=trendKeyword" json:"trend_keyword,omitempty"`
	MarketProspect                 *common.ValueText         `protobuf:"bytes,10,opt,name=market_prospect,json=marketProspect" json:"market_prospect,omitempty"`
	Strategy                       *common.ValueText         `protobuf:"bytes,11,opt,name=strategy" json:"strategy,omitempty"`
	Advantage                      *common.ValueText         `protobuf:"bytes,12,opt,name=advantage" json:"advantage,omitempty"`
	DecisionType                   *Detail_DecisionType      `protobuf:"bytes,13,opt,name=decision_type,json=decisionType" json:"decision_type,omitempty"`
	EmployeeAverageAge             *common.ValueText         `protobuf:"bytes,14,opt,name=employee_average_age,json=employeeAverageAge" json:"employee_average_age,omitempty"`
	EmployeeWomanRate              *common.ValueText         `protobuf:"bytes,15,opt,name=employee_woman_rate,json=employeeWomanRate" json:"employee_woman_rate,omitempty"`
	EmployeeMidCareerRate          *common.ValueText         `protobuf:"bytes,16,opt,name=employee_mid_career_rate,json=employeeMidCareerRate" json:"employee_mid_career_rate,omitempty"`
	EmployeeForeignNationalityRate *common.ValueText         `protobuf:"bytes,17,opt,name=employee_foreign_nationality_rate,json=employeeForeignNationalityRate" json:"employee_foreign_nationality_rate,omitempty"`
	EmployeeCharacter              *Detail_EmployeeCharacter `protobuf:"bytes,18,opt,name=employee_character,json=employeeCharacter" json:"employee_character,omitempty"`
	HrEvaluationPromotionSpeed     *common.ValueText         `protobuf:"bytes,19,opt,name=hr_evaluation_promotion_speed,json=hrEvaluationPromotionSpeed" json:"hr_evaluation_promotion_speed,omitempty"`
	ForeignNationalityRecruiting   *bool                     `protobuf:"varint,20,opt,name=foreign_nationality_recruiting,json=foreignNationalityRecruiting" json:"foreign_nationality_recruiting,omitempty"`
	MedicalAdvantageField          *common.ValuesText        `protobuf:"bytes,21,opt,name=medical_advantage_field,json=medicalAdvantageField" json:"medical_advantage_field,omitempty"`
	CarPartsTier                   *common.ValueText         `protobuf:"bytes,22,opt,name=car_parts_tier,json=carPartsTier" json:"car_parts_tier,omitempty"`
	SiType                         *common.ValueText         `protobuf:"bytes,23,opt,name=si_type,json=siType" json:"si_type,omitempty"`
	SiAdvantageIndustry            *common.ValuesText        `protobuf:"bytes,24,opt,name=si_advantage_industry,json=siAdvantageIndustry" json:"si_advantage_industry,omitempty"`
	ContractCompanyProfitSource    *common.ValueText         `protobuf:"bytes,25,opt,name=contract_company_profit_source,json=contractCompanyProfitSource" json:"contract_company_profit_source,omitempty"`
	ContractCompanyProjectTerm     *common.ValueText         `protobuf:"bytes,26,opt,name=contract_company_project_term,json=contractCompanyProjectTerm" json:"contract_company_project_term,omitempty"`
	ContractCompanyClientResident  *common.ValueText         `protobuf:"bytes,27,opt,name=contract_company_client_resident,json=contractCompanyClientResident" json:"contract_company_client_resident,omitempty"`
	ContractCompanyResident        *common.ValueText         `protobuf:"bytes,28,opt,name=contract_company_resident,json=contractCompanyResident" json:"contract_company_resident,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Detail) Reset() {
	*x = Detail{}
	mi := &file_business_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1}
}

func (x *Detail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Detail) GetEmployeeQty() *common.ValueText {
	if x != nil {
		return x.EmployeeQty
	}
	return nil
}

func (x *Detail) GetEstablishmentYear() *common.ValueText {
	if x != nil {
		return x.EstablishmentYear
	}
	return nil
}

func (x *Detail) GetSalesScale() *common.ValueText {
	if x != nil {
		return x.SalesScale
	}
	return nil
}

func (x *Detail) GetIndustries() *Detail_Industries {
	if x != nil {
		return x.Industries
	}
	return nil
}

func (x *Detail) GetStage() *common.ValueText {
	if x != nil {
		return x.Stage
	}
	return nil
}

func (x *Detail) GetProduct() *Detail_Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *Detail) GetTargetCustomer() *Detail_TargetCustomer {
	if x != nil {
		return x.TargetCustomer
	}
	return nil
}

func (x *Detail) GetTrendKeyword() *common.ValuesText {
	if x != nil {
		return x.TrendKeyword
	}
	return nil
}

func (x *Detail) GetMarketProspect() *common.ValueText {
	if x != nil {
		return x.MarketProspect
	}
	return nil
}

func (x *Detail) GetStrategy() *common.ValueText {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *Detail) GetAdvantage() *common.ValueText {
	if x != nil {
		return x.Advantage
	}
	return nil
}

func (x *Detail) GetDecisionType() *Detail_DecisionType {
	if x != nil {
		return x.DecisionType
	}
	return nil
}

func (x *Detail) GetEmployeeAverageAge() *common.ValueText {
	if x != nil {
		return x.EmployeeAverageAge
	}
	return nil
}

func (x *Detail) GetEmployeeWomanRate() *common.ValueText {
	if x != nil {
		return x.EmployeeWomanRate
	}
	return nil
}

func (x *Detail) GetEmployeeMidCareerRate() *common.ValueText {
	if x != nil {
		return x.EmployeeMidCareerRate
	}
	return nil
}

func (x *Detail) GetEmployeeForeignNationalityRate() *common.ValueText {
	if x != nil {
		return x.EmployeeForeignNationalityRate
	}
	return nil
}

func (x *Detail) GetEmployeeCharacter() *Detail_EmployeeCharacter {
	if x != nil {
		return x.EmployeeCharacter
	}
	return nil
}

func (x *Detail) GetHrEvaluationPromotionSpeed() *common.ValueText {
	if x != nil {
		return x.HrEvaluationPromotionSpeed
	}
	return nil
}

func (x *Detail) GetForeignNationalityRecruiting() bool {
	if x != nil && x.ForeignNationalityRecruiting != nil {
		return *x.ForeignNationalityRecruiting
	}
	return false
}

func (x *Detail) GetMedicalAdvantageField() *common.ValuesText {
	if x != nil {
		return x.MedicalAdvantageField
	}
	return nil
}

func (x *Detail) GetCarPartsTier() *common.ValueText {
	if x != nil {
		return x.CarPartsTier
	}
	return nil
}

func (x *Detail) GetSiType() *common.ValueText {
	if x != nil {
		return x.SiType
	}
	return nil
}

func (x *Detail) GetSiAdvantageIndustry() *common.ValuesText {
	if x != nil {
		return x.SiAdvantageIndustry
	}
	return nil
}

func (x *Detail) GetContractCompanyProfitSource() *common.ValueText {
	if x != nil {
		return x.ContractCompanyProfitSource
	}
	return nil
}

func (x *Detail) GetContractCompanyProjectTerm() *common.ValueText {
	if x != nil {
		return x.ContractCompanyProjectTerm
	}
	return nil
}

func (x *Detail) GetContractCompanyClientResident() *common.ValueText {
	if x != nil {
		return x.ContractCompanyClientResident
	}
	return nil
}

func (x *Detail) GetContractCompanyResident() *common.ValueText {
	if x != nil {
		return x.ContractCompanyResident
	}
	return nil
}

type Detail_DecisionType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type1         int32                  `protobuf:"varint,1,opt,name=type1" json:"type1,omitempty"`
	Type2         int32                  `protobuf:"varint,2,opt,name=type2" json:"type2,omitempty"`
	Type3         int32                  `protobuf:"varint,3,opt,name=type3" json:"type3,omitempty"`
	Type4         int32                  `protobuf:"varint,4,opt,name=type4" json:"type4,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_DecisionType) Reset() {
	*x = Detail_DecisionType{}
	mi := &file_business_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_DecisionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_DecisionType) ProtoMessage() {}

func (x *Detail_DecisionType) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_DecisionType.ProtoReflect.Descriptor instead.
func (*Detail_DecisionType) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Detail_DecisionType) GetType1() int32 {
	if x != nil {
		return x.Type1
	}
	return 0
}

func (x *Detail_DecisionType) GetType2() int32 {
	if x != nil {
		return x.Type2
	}
	return 0
}

func (x *Detail_DecisionType) GetType3() int32 {
	if x != nil {
		return x.Type3
	}
	return 0
}

func (x *Detail_DecisionType) GetType4() int32 {
	if x != nil {
		return x.Type4
	}
	return 0
}

func (x *Detail_DecisionType) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Detail_EmployeeCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character1    int32                  `protobuf:"varint,1,opt,name=character1" json:"character1,omitempty"`
	Character2    int32                  `protobuf:"varint,2,opt,name=character2" json:"character2,omitempty"`
	Character3    int32                  `protobuf:"varint,3,opt,name=character3" json:"character3,omitempty"`
	Character4    int32                  `protobuf:"varint,4,opt,name=character4" json:"character4,omitempty"`
	Character5    int32                  `protobuf:"varint,5,opt,name=character5" json:"character5,omitempty"`
	Character6    int32                  `protobuf:"varint,6,opt,name=character6" json:"character6,omitempty"`
	Character7    int32                  `protobuf:"varint,7,opt,name=character7" json:"character7,omitempty"`
	Character8    int32                  `protobuf:"varint,8,opt,name=character8" json:"character8,omitempty"`
	Character9    int32                  `protobuf:"varint,9,opt,name=character9" json:"character9,omitempty"`
	Character10   int32                  `protobuf:"varint,10,opt,name=character10" json:"character10,omitempty"`
	Character11   int32                  `protobuf:"varint,11,opt,name=character11" json:"character11,omitempty"`
	Character12   int32                  `protobuf:"varint,12,opt,name=character12" json:"character12,omitempty"`
	Text          string                 `protobuf:"bytes,13,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_EmployeeCharacter) Reset() {
	*x = Detail_EmployeeCharacter{}
	mi := &file_business_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_EmployeeCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_EmployeeCharacter) ProtoMessage() {}

func (x *Detail_EmployeeCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_EmployeeCharacter.ProtoReflect.Descriptor instead.
func (*Detail_EmployeeCharacter) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Detail_EmployeeCharacter) GetCharacter1() int32 {
	if x != nil {
		return x.Character1
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter2() int32 {
	if x != nil {
		return x.Character2
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter3() int32 {
	if x != nil {
		return x.Character3
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter4() int32 {
	if x != nil {
		return x.Character4
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter5() int32 {
	if x != nil {
		return x.Character5
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter6() int32 {
	if x != nil {
		return x.Character6
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter7() int32 {
	if x != nil {
		return x.Character7
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter8() int32 {
	if x != nil {
		return x.Character8
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter9() int32 {
	if x != nil {
		return x.Character9
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter10() int32 {
	if x != nil {
		return x.Character10
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter11() int32 {
	if x != nil {
		return x.Character11
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetCharacter12() int32 {
	if x != nil {
		return x.Character12
	}
	return 0
}

func (x *Detail_EmployeeCharacter) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Detail_Industries struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Industries    []*Detail_Industries_Industry `protobuf:"bytes,1,rep,name=industries" json:"industries,omitempty"`
	Text          string                        `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_Industries) Reset() {
	*x = Detail_Industries{}
	mi := &file_business_business_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_Industries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_Industries) ProtoMessage() {}

func (x *Detail_Industries) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_Industries.ProtoReflect.Descriptor instead.
func (*Detail_Industries) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Detail_Industries) GetIndustries() []*Detail_Industries_Industry {
	if x != nil {
		return x.Industries
	}
	return nil
}

func (x *Detail_Industries) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Detail_Product struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	Share          *common.ValueText            `protobuf:"bytes,1,opt,name=share" json:"share,omitempty"`
	HasOwnProducts *common.FlagText             `protobuf:"bytes,2,opt,name=has_own_products,json=hasOwnProducts" json:"has_own_products,omitempty"`
	Tangibleness   *Detail_Product_Tangibleness `protobuf:"bytes,3,opt,name=tangibleness" json:"tangibleness,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Detail_Product) Reset() {
	*x = Detail_Product{}
	mi := &file_business_business_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_Product) ProtoMessage() {}

func (x *Detail_Product) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_Product.ProtoReflect.Descriptor instead.
func (*Detail_Product) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1, 3}
}

func (x *Detail_Product) GetShare() *common.ValueText {
	if x != nil {
		return x.Share
	}
	return nil
}

func (x *Detail_Product) GetHasOwnProducts() *common.FlagText {
	if x != nil {
		return x.HasOwnProducts
	}
	return nil
}

func (x *Detail_Product) GetTangibleness() *Detail_Product_Tangibleness {
	if x != nil {
		return x.Tangibleness
	}
	return nil
}

type Detail_TargetCustomer struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	BtoBExists    *bool                       `protobuf:"varint,1,opt,name=bto_b_exists,json=btoBExists" json:"bto_b_exists,omitempty"`
	BtoCExists    *bool                       `protobuf:"varint,2,opt,name=bto_c_exists,json=btoCExists" json:"bto_c_exists,omitempty"`
	Text          string                      `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	BtoB          *Detail_TargetCustomer_BtoB `protobuf:"bytes,4,opt,name=bto_b,json=btoB" json:"bto_b,omitempty"`
	BtoC          *Detail_TargetCustomer_BtoC `protobuf:"bytes,5,opt,name=bto_c,json=btoC" json:"bto_c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_TargetCustomer) Reset() {
	*x = Detail_TargetCustomer{}
	mi := &file_business_business_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_TargetCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_TargetCustomer) ProtoMessage() {}

func (x *Detail_TargetCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_TargetCustomer.ProtoReflect.Descriptor instead.
func (*Detail_TargetCustomer) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1, 4}
}

func (x *Detail_TargetCustomer) GetBtoBExists() bool {
	if x != nil && x.BtoBExists != nil {
		return *x.BtoBExists
	}
	return false
}

func (x *Detail_TargetCustomer) GetBtoCExists() bool {
	if x != nil && x.BtoCExists != nil {
		return *x.BtoCExists
	}
	return false
}

func (x *Detail_TargetCustomer) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Detail_TargetCustomer) GetBtoB() *Detail_TargetCustomer_BtoB {
	if x != nil {
		return x.BtoB
	}
	return nil
}

func (x *Detail_TargetCustomer) GetBtoC() *Detail_TargetCustomer_BtoC {
	if x != nil {
		return x.BtoC
	}
	return nil
}

type Detail_Industries_Industry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmallId       int32                  `protobuf:"varint,1,opt,name=small_id,json=smallId" json:"small_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	MainFlg       bool                   `protobuf:"varint,3,opt,name=mainFlg" json:"mainFlg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_Industries_Industry) Reset() {
	*x = Detail_Industries_Industry{}
	mi := &file_business_business_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_Industries_Industry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_Industries_Industry) ProtoMessage() {}

func (x *Detail_Industries_Industry) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_Industries_Industry.ProtoReflect.Descriptor instead.
func (*Detail_Industries_Industry) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1, 2, 0}
}

func (x *Detail_Industries_Industry) GetSmallId() int32 {
	if x != nil {
		return x.SmallId
	}
	return 0
}

func (x *Detail_Industries_Industry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Detail_Industries_Industry) GetMainFlg() bool {
	if x != nil {
		return x.MainFlg
	}
	return false
}

type Detail_Product_Tangibleness struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tangible      *common.Flag           `protobuf:"bytes,1,opt,name=tangible" json:"tangible,omitempty"`
	Intangible    *common.Flag           `protobuf:"bytes,2,opt,name=intangible" json:"intangible,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_Product_Tangibleness) Reset() {
	*x = Detail_Product_Tangibleness{}
	mi := &file_business_business_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_Product_Tangibleness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_Product_Tangibleness) ProtoMessage() {}

func (x *Detail_Product_Tangibleness) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_Product_Tangibleness.ProtoReflect.Descriptor instead.
func (*Detail_Product_Tangibleness) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1, 3, 0}
}

func (x *Detail_Product_Tangibleness) GetTangible() *common.Flag {
	if x != nil {
		return x.Tangible
	}
	return nil
}

func (x *Detail_Product_Tangibleness) GetIntangible() *common.Flag {
	if x != nil {
		return x.Intangible
	}
	return nil
}

func (x *Detail_Product_Tangibleness) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Detail_TargetCustomer_BtoB struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	IndustrySmallIds []*common.IntIdLabelPair `protobuf:"bytes,1,rep,name=industry_small_ids,json=industrySmallIds" json:"industry_small_ids,omitempty"`
	Text             string                   `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Detail_TargetCustomer_BtoB) Reset() {
	*x = Detail_TargetCustomer_BtoB{}
	mi := &file_business_business_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_TargetCustomer_BtoB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_TargetCustomer_BtoB) ProtoMessage() {}

func (x *Detail_TargetCustomer_BtoB) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_TargetCustomer_BtoB.ProtoReflect.Descriptor instead.
func (*Detail_TargetCustomer_BtoB) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1, 4, 0}
}

func (x *Detail_TargetCustomer_BtoB) GetIndustrySmallIds() []*common.IntIdLabelPair {
	if x != nil {
		return x.IndustrySmallIds
	}
	return nil
}

func (x *Detail_TargetCustomer_BtoB) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Detail_TargetCustomer_BtoC struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	TargetIds     []*common.IntIdLabelPair `protobuf:"bytes,1,rep,name=target_ids,json=targetIds" json:"target_ids,omitempty"`
	Text          string                   `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail_TargetCustomer_BtoC) Reset() {
	*x = Detail_TargetCustomer_BtoC{}
	mi := &file_business_business_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail_TargetCustomer_BtoC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail_TargetCustomer_BtoC) ProtoMessage() {}

func (x *Detail_TargetCustomer_BtoC) ProtoReflect() protoreflect.Message {
	mi := &file_business_business_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail_TargetCustomer_BtoC.ProtoReflect.Descriptor instead.
func (*Detail_TargetCustomer_BtoC) Descriptor() ([]byte, []int) {
	return file_business_business_proto_rawDescGZIP(), []int{1, 4, 1}
}

func (x *Detail_TargetCustomer_BtoC) GetTargetIds() []*common.IntIdLabelPair {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

func (x *Detail_TargetCustomer_BtoC) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_business_business_proto protoreflect.FileDescriptor

const file_business_business_proto_rawDesc = "" +
	"\n" +
	"\x17business/business.proto\x12 miidas.user.marketvalue.business\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fcommon/vo.proto\"\xb9\x02\n" +
	"\bBusiness\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\x05R\tcompanyId\x12@\n" +
	"\x06detail\x18\x03 \x01(\v2(.miidas.user.marketvalue.business.DetailR\x06detail\x12D\n" +
	"\x10last_modified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastModifiedAt\x12;\n" +
	"\vimported_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"importedAt\x129\n" +
	"\n" +
	"trashed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttrashedAt\"\xe8 \n" +
	"\x06Detail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12L\n" +
	"\femployee_qty\x18\x02 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\vemployeeQty\x12X\n" +
	"\x12establishment_year\x18\x03 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x11establishmentYear\x12J\n" +
	"\vsales_scale\x18\x04 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\n" +
	"salesScale\x12S\n" +
	"\n" +
	"industries\x18\x05 \x01(\v23.miidas.user.marketvalue.business.Detail.IndustriesR\n" +
	"industries\x12?\n" +
	"\x05stage\x18\x06 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x05stage\x12J\n" +
	"\aproduct\x18\a \x01(\v20.miidas.user.marketvalue.business.Detail.ProductR\aproduct\x12`\n" +
	"\x0ftarget_customer\x18\b \x01(\v27.miidas.user.marketvalue.business.Detail.TargetCustomerR\x0etargetCustomer\x12O\n" +
	"\rtrend_keyword\x18\t \x01(\v2*.miidas.user.marketvalue.common.ValuesTextR\ftrendKeyword\x12R\n" +
	"\x0fmarket_prospect\x18\n" +
	" \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x0emarketProspect\x12E\n" +
	"\bstrategy\x18\v \x01(\v2).miidas.user.marketvalue.common.ValueTextR\bstrategy\x12G\n" +
	"\tadvantage\x18\f \x01(\v2).miidas.user.marketvalue.common.ValueTextR\tadvantage\x12Z\n" +
	"\rdecision_type\x18\r \x01(\v25.miidas.user.marketvalue.business.Detail.DecisionTypeR\fdecisionType\x12[\n" +
	"\x14employee_average_age\x18\x0e \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x12employeeAverageAge\x12Y\n" +
	"\x13employee_woman_rate\x18\x0f \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x11employeeWomanRate\x12b\n" +
	"\x18employee_mid_career_rate\x18\x10 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x15employeeMidCareerRate\x12t\n" +
	"!employee_foreign_nationality_rate\x18\x11 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x1eemployeeForeignNationalityRate\x12i\n" +
	"\x12employee_character\x18\x12 \x01(\v2:.miidas.user.marketvalue.business.Detail.EmployeeCharacterR\x11employeeCharacter\x12l\n" +
	"\x1dhr_evaluation_promotion_speed\x18\x13 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x1ahrEvaluationPromotionSpeed\x12K\n" +
	"\x1eforeign_nationality_recruiting\x18\x14 \x01(\bB\x05\xaa\x01\x02\b\x01R\x1cforeignNationalityRecruiting\x12b\n" +
	"\x17medical_advantage_field\x18\x15 \x01(\v2*.miidas.user.marketvalue.common.ValuesTextR\x15medicalAdvantageField\x12O\n" +
	"\x0ecar_parts_tier\x18\x16 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\fcarPartsTier\x12B\n" +
	"\asi_type\x18\x17 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x06siType\x12^\n" +
	"\x15si_advantage_industry\x18\x18 \x01(\v2*.miidas.user.marketvalue.common.ValuesTextR\x13siAdvantageIndustry\x12n\n" +
	"\x1econtract_company_profit_source\x18\x19 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x1bcontractCompanyProfitSource\x12l\n" +
	"\x1dcontract_company_project_term\x18\x1a \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x1acontractCompanyProjectTerm\x12r\n" +
	" contract_company_client_resident\x18\x1b \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x1dcontractCompanyClientResident\x12e\n" +
	"\x19contract_company_resident\x18\x1c \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x17contractCompanyResident\x1az\n" +
	"\fDecisionType\x12\x14\n" +
	"\x05type1\x18\x01 \x01(\x05R\x05type1\x12\x14\n" +
	"\x05type2\x18\x02 \x01(\x05R\x05type2\x12\x14\n" +
	"\x05type3\x18\x03 \x01(\x05R\x05type3\x12\x14\n" +
	"\x05type4\x18\x04 \x01(\x05R\x05type4\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x1a\xad\x03\n" +
	"\x11EmployeeCharacter\x12\x1e\n" +
	"\n" +
	"character1\x18\x01 \x01(\x05R\n" +
	"character1\x12\x1e\n" +
	"\n" +
	"character2\x18\x02 \x01(\x05R\n" +
	"character2\x12\x1e\n" +
	"\n" +
	"character3\x18\x03 \x01(\x05R\n" +
	"character3\x12\x1e\n" +
	"\n" +
	"character4\x18\x04 \x01(\x05R\n" +
	"character4\x12\x1e\n" +
	"\n" +
	"character5\x18\x05 \x01(\x05R\n" +
	"character5\x12\x1e\n" +
	"\n" +
	"character6\x18\x06 \x01(\x05R\n" +
	"character6\x12\x1e\n" +
	"\n" +
	"character7\x18\a \x01(\x05R\n" +
	"character7\x12\x1e\n" +
	"\n" +
	"character8\x18\b \x01(\x05R\n" +
	"character8\x12\x1e\n" +
	"\n" +
	"character9\x18\t \x01(\x05R\n" +
	"character9\x12 \n" +
	"\vcharacter10\x18\n" +
	" \x01(\x05R\vcharacter10\x12 \n" +
	"\vcharacter11\x18\v \x01(\x05R\vcharacter11\x12 \n" +
	"\vcharacter12\x18\f \x01(\x05R\vcharacter12\x12\x12\n" +
	"\x04text\x18\r \x01(\tR\x04text\x1a\xd5\x01\n" +
	"\n" +
	"Industries\x12\\\n" +
	"\n" +
	"industries\x18\x01 \x03(\v2<.miidas.user.marketvalue.business.Detail.Industries.IndustryR\n" +
	"industries\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x1aU\n" +
	"\bIndustry\x12\x19\n" +
	"\bsmall_id\x18\x01 \x01(\x05R\asmallId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\amainFlg\x18\x03 \x01(\bR\amainFlg\x1a\xae\x03\n" +
	"\aProduct\x12?\n" +
	"\x05share\x18\x01 \x01(\v2).miidas.user.marketvalue.common.ValueTextR\x05share\x12R\n" +
	"\x10has_own_products\x18\x02 \x01(\v2(.miidas.user.marketvalue.common.FlagTextR\x0ehasOwnProducts\x12a\n" +
	"\ftangibleness\x18\x03 \x01(\v2=.miidas.user.marketvalue.business.Detail.Product.TangiblenessR\ftangibleness\x1a\xaa\x01\n" +
	"\fTangibleness\x12@\n" +
	"\btangible\x18\x01 \x01(\v2$.miidas.user.marketvalue.common.FlagR\btangible\x12D\n" +
	"\n" +
	"intangible\x18\x02 \x01(\v2$.miidas.user.marketvalue.common.FlagR\n" +
	"intangible\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x1a\x81\x04\n" +
	"\x0eTargetCustomer\x12'\n" +
	"\fbto_b_exists\x18\x01 \x01(\bB\x05\xaa\x01\x02\b\x01R\n" +
	"btoBExists\x12'\n" +
	"\fbto_c_exists\x18\x02 \x01(\bB\x05\xaa\x01\x02\b\x01R\n" +
	"btoCExists\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12Q\n" +
	"\x05bto_b\x18\x04 \x01(\v2<.miidas.user.marketvalue.business.Detail.TargetCustomer.BtoBR\x04btoB\x12Q\n" +
	"\x05bto_c\x18\x05 \x01(\v2<.miidas.user.marketvalue.business.Detail.TargetCustomer.BtoCR\x04btoC\x1ax\n" +
	"\x04BtoB\x12\\\n" +
	"\x12industry_small_ids\x18\x01 \x03(\v2..miidas.user.marketvalue.common.IntIdLabelPairR\x10industrySmallIds\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x1ai\n" +
	"\x04BtoC\x12M\n" +
	"\n" +
	"target_ids\x18\x01 \x03(\v2..miidas.user.marketvalue.common.IntIdLabelPairR\ttargetIds\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04textB5Z.miidas/m2/user/marketvalue/grpc/iface/business\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_business_business_proto_rawDescOnce sync.Once
	file_business_business_proto_rawDescData []byte
)

func file_business_business_proto_rawDescGZIP() []byte {
	file_business_business_proto_rawDescOnce.Do(func() {
		file_business_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_business_proto_rawDesc), len(file_business_business_proto_rawDesc)))
	})
	return file_business_business_proto_rawDescData
}

var file_business_business_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_business_business_proto_goTypes = []any{
	(*Business)(nil),                    // 0: miidas.user.marketvalue.business.Business
	(*Detail)(nil),                      // 1: miidas.user.marketvalue.business.Detail
	(*Detail_DecisionType)(nil),         // 2: miidas.user.marketvalue.business.Detail.DecisionType
	(*Detail_EmployeeCharacter)(nil),    // 3: miidas.user.marketvalue.business.Detail.EmployeeCharacter
	(*Detail_Industries)(nil),           // 4: miidas.user.marketvalue.business.Detail.Industries
	(*Detail_Product)(nil),              // 5: miidas.user.marketvalue.business.Detail.Product
	(*Detail_TargetCustomer)(nil),       // 6: miidas.user.marketvalue.business.Detail.TargetCustomer
	(*Detail_Industries_Industry)(nil),  // 7: miidas.user.marketvalue.business.Detail.Industries.Industry
	(*Detail_Product_Tangibleness)(nil), // 8: miidas.user.marketvalue.business.Detail.Product.Tangibleness
	(*Detail_TargetCustomer_BtoB)(nil),  // 9: miidas.user.marketvalue.business.Detail.TargetCustomer.BtoB
	(*Detail_TargetCustomer_BtoC)(nil),  // 10: miidas.user.marketvalue.business.Detail.TargetCustomer.BtoC
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
	(*common.ValueText)(nil),            // 12: miidas.user.marketvalue.common.ValueText
	(*common.ValuesText)(nil),           // 13: miidas.user.marketvalue.common.ValuesText
	(*common.FlagText)(nil),             // 14: miidas.user.marketvalue.common.FlagText
	(*common.Flag)(nil),                 // 15: miidas.user.marketvalue.common.Flag
	(*common.IntIdLabelPair)(nil),       // 16: miidas.user.marketvalue.common.IntIdLabelPair
}
var file_business_business_proto_depIdxs = []int32{
	1,  // 0: miidas.user.marketvalue.business.Business.detail:type_name -> miidas.user.marketvalue.business.Detail
	11, // 1: miidas.user.marketvalue.business.Business.last_modified_at:type_name -> google.protobuf.Timestamp
	11, // 2: miidas.user.marketvalue.business.Business.imported_at:type_name -> google.protobuf.Timestamp
	11, // 3: miidas.user.marketvalue.business.Business.trashed_at:type_name -> google.protobuf.Timestamp
	12, // 4: miidas.user.marketvalue.business.Detail.employee_qty:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 5: miidas.user.marketvalue.business.Detail.establishment_year:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 6: miidas.user.marketvalue.business.Detail.sales_scale:type_name -> miidas.user.marketvalue.common.ValueText
	4,  // 7: miidas.user.marketvalue.business.Detail.industries:type_name -> miidas.user.marketvalue.business.Detail.Industries
	12, // 8: miidas.user.marketvalue.business.Detail.stage:type_name -> miidas.user.marketvalue.common.ValueText
	5,  // 9: miidas.user.marketvalue.business.Detail.product:type_name -> miidas.user.marketvalue.business.Detail.Product
	6,  // 10: miidas.user.marketvalue.business.Detail.target_customer:type_name -> miidas.user.marketvalue.business.Detail.TargetCustomer
	13, // 11: miidas.user.marketvalue.business.Detail.trend_keyword:type_name -> miidas.user.marketvalue.common.ValuesText
	12, // 12: miidas.user.marketvalue.business.Detail.market_prospect:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 13: miidas.user.marketvalue.business.Detail.strategy:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 14: miidas.user.marketvalue.business.Detail.advantage:type_name -> miidas.user.marketvalue.common.ValueText
	2,  // 15: miidas.user.marketvalue.business.Detail.decision_type:type_name -> miidas.user.marketvalue.business.Detail.DecisionType
	12, // 16: miidas.user.marketvalue.business.Detail.employee_average_age:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 17: miidas.user.marketvalue.business.Detail.employee_woman_rate:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 18: miidas.user.marketvalue.business.Detail.employee_mid_career_rate:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 19: miidas.user.marketvalue.business.Detail.employee_foreign_nationality_rate:type_name -> miidas.user.marketvalue.common.ValueText
	3,  // 20: miidas.user.marketvalue.business.Detail.employee_character:type_name -> miidas.user.marketvalue.business.Detail.EmployeeCharacter
	12, // 21: miidas.user.marketvalue.business.Detail.hr_evaluation_promotion_speed:type_name -> miidas.user.marketvalue.common.ValueText
	13, // 22: miidas.user.marketvalue.business.Detail.medical_advantage_field:type_name -> miidas.user.marketvalue.common.ValuesText
	12, // 23: miidas.user.marketvalue.business.Detail.car_parts_tier:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 24: miidas.user.marketvalue.business.Detail.si_type:type_name -> miidas.user.marketvalue.common.ValueText
	13, // 25: miidas.user.marketvalue.business.Detail.si_advantage_industry:type_name -> miidas.user.marketvalue.common.ValuesText
	12, // 26: miidas.user.marketvalue.business.Detail.contract_company_profit_source:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 27: miidas.user.marketvalue.business.Detail.contract_company_project_term:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 28: miidas.user.marketvalue.business.Detail.contract_company_client_resident:type_name -> miidas.user.marketvalue.common.ValueText
	12, // 29: miidas.user.marketvalue.business.Detail.contract_company_resident:type_name -> miidas.user.marketvalue.common.ValueText
	7,  // 30: miidas.user.marketvalue.business.Detail.Industries.industries:type_name -> miidas.user.marketvalue.business.Detail.Industries.Industry
	12, // 31: miidas.user.marketvalue.business.Detail.Product.share:type_name -> miidas.user.marketvalue.common.ValueText
	14, // 32: miidas.user.marketvalue.business.Detail.Product.has_own_products:type_name -> miidas.user.marketvalue.common.FlagText
	8,  // 33: miidas.user.marketvalue.business.Detail.Product.tangibleness:type_name -> miidas.user.marketvalue.business.Detail.Product.Tangibleness
	9,  // 34: miidas.user.marketvalue.business.Detail.TargetCustomer.bto_b:type_name -> miidas.user.marketvalue.business.Detail.TargetCustomer.BtoB
	10, // 35: miidas.user.marketvalue.business.Detail.TargetCustomer.bto_c:type_name -> miidas.user.marketvalue.business.Detail.TargetCustomer.BtoC
	15, // 36: miidas.user.marketvalue.business.Detail.Product.Tangibleness.tangible:type_name -> miidas.user.marketvalue.common.Flag
	15, // 37: miidas.user.marketvalue.business.Detail.Product.Tangibleness.intangible:type_name -> miidas.user.marketvalue.common.Flag
	16, // 38: miidas.user.marketvalue.business.Detail.TargetCustomer.BtoB.industry_small_ids:type_name -> miidas.user.marketvalue.common.IntIdLabelPair
	16, // 39: miidas.user.marketvalue.business.Detail.TargetCustomer.BtoC.target_ids:type_name -> miidas.user.marketvalue.common.IntIdLabelPair
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_business_business_proto_init() }
func file_business_business_proto_init() {
	if File_business_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_business_proto_rawDesc), len(file_business_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_business_business_proto_goTypes,
		DependencyIndexes: file_business_business_proto_depIdxs,
		MessageInfos:      file_business_business_proto_msgTypes,
	}.Build()
	File_business_business_proto = out.File
	file_business_business_proto_goTypes = nil
	file_business_business_proto_depIdxs = nil
}
